.github/workflows/docker.yml
=> Build docker image in CI

.github/workflows/docker.yml
=> Tag docker images with git tag

.github/scripts/checkMembership.mjs
- This fixes the issue where the check membership is only checking the first 30 members of our organization.
**Tested + working**. Tested via: https://github.com/clockworklabs/SpacetimeDB/pull/197
=> Fix Check Membership

.github/pull_request_template.md
=> Add an option for ABI breaks to the PR template

crates/client-api/src/routes/identity.rs
This commit adds a new route to the `/identity` HTTP block, `/identity/:identity/verify`, which requires a SpacetimeDB auth header.
If the token in the authorization header is valid and corresponds to the identity in the path, it returns `NO_CONTENT`.
If the token in the authorization header is valid but does not correspond to the identity in the path, it returns `BAD_REQUEST`.
If the token in the authorization header is invalid or unsupplied, it returns `UNAUTHORIZED`.
=> Add `identity/:id/verify` route to verify identity/token pairs

.github/workflows/docker.yml
=> Build the Docker image only on most important branches

crates/cli/src/subcommands/logs.rs
Prior to this commit, the `logs` subcommand would print an unhelpfully generic HTTP error on failure. Notably, this error did not include the actual response body.
With this commit, the error includes the HTTP response body. For example, trying to print logs for a server you don't own shows:
```
Error: Identity does not own database, expected: 69c07c49846bcf11d7b7cb411018ded585a5a6d9045f8a1a39fa638e9db48436 got: 915cff645f94f52467c43734d54a26d565abb69c7506e30127dd616ca4790414
```
=> [CLI] Report text of error response in `logs`

crates/client-api/src/routes/subscribe.rs
Related to #224 -- though not sure if it completely fixes the 〈not being able to connect to the database〉 issue.
=> Fix logspam

.github/workflows/docker.yml
=> Add labels to docker containers

crates/core/src/control_db/tests.rs, crates/core/src/database_instance_context.rs, crates/core/src/db/message_log.rs, crates/core/src/db/relational_db.rs, crates/lib/src/address.rs
Add debug logs to show progress when loading a db into memory
=> Add debug logs with load progress

crates/core/src/db/cursor.rs, crates/core/src/sql/compiler.rs, crates/core/src/vm.rs, crates/vm/src/eval.rs, crates/vm/src/expr.rs
=> feat(297): generate index scans for range predicates

crates/core/src/sql/compiler.rs, crates/vm/src/expr.rs
=> perf(308): Push index scans below join

.github/workflows/docker.yml
Run docker builds on a dedicated server
=> Run docker builds on bare-metal

.github/workflows/docker.yml
Build spacetimedb-standalone on arm runner
=> Build spacetimedb-standalone on arm runner

crates/client-api/src/routes/subscribe.rs, crates/core/src/util/future_queue.rs
Written while I was backtracking the deadlock fix from yesterday.
=> Add some comments to `FutureQueue` and the `subscribe` route

.github/pull_request_template.md
As discussed in our 0.7.0 retrospective / post-mortem, add a section to the PR template requesting an estimate of complexity and risk in the changes. The template includes an explicit and somewhat verbose explanation of what is expected.
1; this is not a code change.
=> Add a section to the PR template requiring an estimate of complexity and risk

crates/core/src/host/module_host.rs, crates/core/src/host/wasm_common/module_host_actor.rs, crates/core/src/subscription/module_subscription_actor.rs, crates/core/src/subscription/query.rs, crates/core/src/subscription/subscription.rs
WIP correctness of incremental join query evaluation.
@joshua-spacetime Feel free to add changes 
=> Incremental Evaluation of JOIN queries

.github/workflows/docker.yml
=> Run docker build on tags too

crates/core/src/sql/compiler.rs, crates/core/src/vm.rs, crates/vm/src/eval.rs, crates/vm/src/expr.rs, crates/vm/src/typecheck.rs
#451 got merged into the wrong branch, resubmitting.
=> [Resubmit] vm: Make UPDATE actually update

.github/workflows/benchmarks.yml
=> Fix benchmarks please 100%

.github/workflows/benchmarks.yml
=> fix benchmarks run on master

test/tests/zz_docker-restart-module.sh, test/tests/zz_docker-restart-sql.sh
Restarting a database with indexes + sequences is more interesting, in particular it could have caught #569
1
=> test: Create indexes for restarting tests

crates/cli/src/subcommands/repl.rs, crates/client-api-messages/src/lib.rs, crates/core/src/db/datastore/locking_tx_datastore/mod.rs, crates/core/src/sql/ast.rs, crates/data-structures/src/slim_slice.rs, crates/lib/src/lib.rs, crates/sats/src/typespace.rs, crates/standalone/Dockerfile, rust-toolchain.toml
Update to Rust 1.74 & fix the new clippy lints.
1, routine toolchain bump
=> Update to rust 1.74

crates/core/src/subscription/query.rs
The query string in QueryDebugInfo is used as a label for certain metrics. And grafana cannot handle label values with newlines.
=> fix: Remove newlines from QueryDebugInfo

.github/workflows/ci.yml
=> fix: Temporarily disable flaky smoketests

Cargo.lock, Cargo.toml, crates/core/Cargo.toml, crates/core/src/db/db_metrics/mod.rs, crates/core/src/execution_context.rs, crates/core/src/host/mod.rs, crates/core/src/util/mod.rs, crates/core/src/worker_metrics/mod.rs, crates/lib/Cargo.toml, crates/lib/src/address.rs, crates/lib/src/identity.rs, crates/metrics/Cargo.toml, crates/metrics/src/lib.rs, crates/metrics/src/typed_prometheus.rs, crates/sats/Cargo.toml, crates/sats/src/hash.rs, docker-compose-release.yml, docker-compose.yml, tools/publish-crates.sh
=> refactor(metrics): Move metric builder macros into their own crate

Cargo.lock, Cargo.toml
The previous protocol is incompatible with the latest tracy client.
=> chore: Update tracy to 0.10.4

.github/workflows/benchmarks.yml
I noticed that master's benchmarks run are failing, this should fix it.
=> Fix master commit benchmarks run

test/tests/autoinc1.sh, test/tests/bitcraftmini-pretest.sh, test/tests/cancel-reducer.sh, test/tests/connect-disconnect-from-cli.sh, test/tests/describe.sh, test/tests/filtering.sh, test/tests/module-nested-op.sh, test/tests/new-user-flow.sh, test/tests/panic.sh, test/tests/permissions-call.sh, test/tests/permissions-delete.sh, test/tests/permissions-describe.sh, test/tests/permissions-logs.sh, test/tests/permissions-publish.sh, test/tests/register-domain.sh, test/tests/reverse-dns.sh, test/tests/setname.sh, test/tests/sql-format.sh, test/tests/upload-module-1.sh, test/tests/upload-module-2.sh, test/tests/zz_docker-restart-module.sh, test/tests/zz_docker-restart-repeating-reducer.sh, test/tests/zz_docker-restart-sql.sh
Debug now creates wasm artifacts which are bigger than what we can support currently.
1
=> test: Build modules in release mode

crates/cli/src/tasks/csharp.rs, crates/core/src/sql/compiler.rs, crates/core/src/vm.rs
Just reducing log level for internal details from debug to trace, as it gets particularly noisy to tests and not relevant to most users, only for deep debugging.
Also reducing verbosity of .NET compilation.
1
=> Lower log verbosity

.github/workflows/benchmarks.yml
=> Try bumping actions/checkout to fix benchmarks please

crates/core/src/host/wasmtime/wasmtime_module.rs
=> Fix _delete_by_rel

crates/core/src/subscription/module_subscription_actor.rs, crates/core/src/worker_metrics/mod.rs
=> perf(759): Track the number of active subscription queries

crates/vm/src/expr.rs
Prerequisite for #747.
Adds a boolean utility method that probes a QueryExpr for table references.
=> feat(query): Add a utility for checking table refs

crates/bench/README.md, crates/bench/benches/callgrind.rs, crates/bench/benches/generic.rs, crates/bench/callgrind-docker.sh, crates/bench/src/database.rs, crates/bench/src/lib.rs, crates/bench/src/schemas.rs, crates/bench/src/spacetime_module.rs, crates/bench/src/spacetime_raw.rs, crates/bench/src/sqlite.rs, modules/benchmarks/src/lib.rs
Add benchmarks for these.
Do not merge this yet I don't want to add to memarch rebase hell.
0
=> 1_000_000 insert + update benchmarks

Cargo.toml, crates/bench/Cargo.toml, crates/bench/benches/subscription.rs, crates/core/src/host/mod.rs
=> test: Add performance benchmark for incremental join query

crates/core/src/db/datastore/locking_tx_datastore/state_view.rs
=> chore(datastore): Remove debug instrumentation

crates/bench/benches/subscription.rs
=> test(829): Benchmark incremental update for table subscription

crates/core/src/db/relational_db.rs, crates/core/src/sql/compiler.rs, crates/core/src/subscription/query.rs, crates/core/src/subscription/subscription.rs
=> test: Deduplicate utilities for creating tables

Cargo.lock, crates/core/src/execution_context.rs, crates/core/src/host/mod.rs, crates/lib/src/address.rs, crates/lib/src/identity.rs, crates/metrics/Cargo.toml, crates/metrics/src/typed_prometheus.rs, crates/sats/src/hash.rs
Based on #811 for RPITIT (return-position impl trait in trait)
1
=> Reduce allocations for prometheus with_label_values

crates/bench/benches/subscription.rs
=> fix: Wrong algebraic type in query benchmarks

crates/core/src/db/datastore/locking_tx_datastore/datastore.rs, crates/core/src/db/datastore/locking_tx_datastore/tx.rs
=> fix: Record durations for aborted and read transactions

crates/core/src/subscription/module_subscription_actor.rs
Fix the consistency issue introduced by #807
1
=> Fix consistency issue

crates/core/src/host/host_controller.rs
Prior to this commit, we ran our Rayon threads within the Tokio blocking threadpool. This was bad for several reasons, of which the most obvious was that it ignored the Rayon `thread_name`.
Our Rayon threads still need access to the Tokio runtime (which I'm not super jazzed about; see comment), so this commit adds a custom `spawn_handler` which behaves like the Rayon default spawn handler, but also enters the Tokio runtime.
This commit also adds a comment about how we're over-allocating our available parallelism, and in the future we should not do that.
3 - our threadpools are (over)complicated, and ever touching them is scary.
=> HostThreadPool: don't run Rayon threads in Tokio blocking threads

crates/core/src/host/host_controller.rs
=> num_threads = available_concurrency

crates/core/src/client/client_connection.rs, crates/core/src/host/host_controller.rs, crates/core/src/host/module_host.rs, crates/core/src/subscription/module_subscription_actor.rs
=> Run initial subscriptions evals on rayon

crates/core/src/host/module_host.rs, crates/core/src/subscription/module_subscription_actor.rs
=> acquire remove subscription lock in spawn_blocking

crates/vm/src/rel_ops.rs
Fix the estimation of `RowCount`
1
=> Fix the RowCount estimation for select operator

crates/client-api-messages/protobuf/client_api.proto, crates/client-api/src/routes/database.rs, crates/core/src/client/client_connection.rs, crates/core/src/client/message_handlers.rs, crates/core/src/client/messages.rs, crates/core/src/host/mod.rs, crates/core/src/host/module_host.rs, crates/core/src/host/scheduler.rs, crates/core/src/host/wasm_common/module_host_actor.rs, crates/core/src/json/client_api.rs, crates/core/src/subscription/module_subscription_actor.rs, crates/lib/src/identity.rs, crates/sdk/src/background_connection.rs, crates/testing/src/modules.rs
Not intented to, but could be possible. Reviewer to have attention on this.
=> proto changes

crates/core/src/subscription/execution_unit.rs
=> chore: Remove instrumentation from subscription eval hot path

crates/vm/src/expr.rs
=> perf: Update magic constant for join rewrite

crates/client-api/src/routes/subscribe.rs, crates/core/src/util/future_queue.rs, crates/core/src/util/mod.rs
=> Also poll handle_queue while flushing

crates/core/src/subscription/query.rs
No functionality has been modified.
This patch just makes incremental eval test cases clearer and easier to extend.
1 - as long as tests pass
=> refactor: Incremental evaluation tests for index joins

crates/core/src/subscription/query.rs
Adds a test for a tx that generates inserts and deletes for both tables of the join.
Note, this test will fail currently, but will succeed on #957.
1 - Just an additional test.
=> test(954): Incremental evaluation for index joins

.github/pull_request_template.md
Updated the PR template to include a `Testing` section.
None
1
=> Add a `Testing` section to the PR template

crates/sats/src/relation.rs
Looking up a positional FieldName in a Header was broken.
so that you're confident that all the changes work as …
=> fix(1009): Multi-column index selection for query macro

.github/workflows/ci.yml, crates/core/Cargo.toml, crates/core/src/db/datastore/locking_tx_datastore/committed_state.rs, crates/core/src/db/datastore/locking_tx_datastore/datastore.rs, crates/core/src/db/datastore/locking_tx_datastore/state_view.rs, crates/core/src/db/datastore/locking_tx_datastore/tx.rs, crates/core/src/db/relational_db.rs, crates/lib/Cargo.toml, crates/lib/src/address.rs, crates/lib/src/identity.rs, crates/sats/Cargo.toml, crates/sats/src/hash.rs
=> refactor(1058): Remove feature flag for disabling metrics

crates/core/src/db/datastore/locking_tx_datastore/committed_state.rs, crates/core/src/db/datastore/locking_tx_datastore/datastore.rs, crates/core/src/db/datastore/locking_tx_datastore/state_view.rs, crates/core/src/execution_context.rs
Batching metrics in Iters leading to contention lock, to disable them temporarily
=> disable iter metrics

smoketests/__init__.py, smoketests/__main__.py, smoketests/tests/modules.py, smoketests/tests/servers.py
=> Fail CI on smoketest failures

crates/core/src/host/wasm_common/module_host_actor.rs, crates/core/src/util/prometheus_handle.rs, crates/core/src/worker_metrics/mod.rs
=> feat(1168): Track subscription query duration for each reducer

crates/standalone/src/control_db.rs
I found this useful on a branch I'm reworking and decided it should be its own PR.
none
0
=> Tiny change: slightly better logging of sled errors

crates/core/src/db/datastore/locking_tx_datastore/datastore.rs, crates/core/src/subscription/module_subscription_actor.rs
=> due cleanup in datastore test

Cargo.lock, Cargo.toml, crates/bindings-sys/Cargo.toml, crates/bindings-sys/src/lib.rs, crates/bindings/Cargo.toml, crates/bindings/src/lib.rs, crates/bindings/src/rng.rs, crates/bindings/src/rt.rs, crates/cli/src/tasks/rust.rs, modules/spacetimedb-quickstart/Cargo.toml, smoketests/tests/detect_wasm_bindgen.py
Implements the improved rng interface as proposed by @gefjon.
Only an API break if people were using the `getrandom` feature.
2
I'm probably gonna add a smoketest for this.
=> Implement new rand api

Cargo.lock, crates/fs-utils/Cargo.toml, crates/fs-utils/src/lib.rs
Fixes https://github.com/clockworklabs/SpacetimeDB/issues/1345
No
2
=> Fix `Config.save` failing if `/tmp` is on a different filesystem

crates/core/src/config.rs, crates/core/src/db/datastore/locking_tx_datastore/committed_state.rs, crates/core/src/db/datastore/locking_tx_datastore/datastore.rs, crates/core/src/db/datastore/system_tables.rs, crates/core/src/db/relational_db.rs, crates/core/src/subscription/module_subscription_actor.rs, crates/core/src/vm.rs, crates/sats/src/relation.rs
Closes #1329.
Used to persist global parameters for slow query logging and cardinality limits.
2
=> feat(1329): System table for system variables

crates/core/src/db/datastore/locking_tx_datastore/committed_state.rs, crates/core/src/db/datastore/locking_tx_datastore/datastore.rs, crates/core/src/db/datastore/locking_tx_datastore/mut_tx.rs, crates/core/src/db/datastore/locking_tx_datastore/tx.rs, crates/core/src/execution_context.rs
=> refactor: Record txn-level metrics in a single utility

crates/core/src/db/db_metrics/mod.rs, crates/core/src/worker_metrics/mod.rs
=> refactor: Reconfigure histogram buckets for certain metrics

crates/core/src/host/host_controller.rs, crates/core/src/host/module_host.rs
Removes or demotes logging to trace in host controller and module host.
No
1
=> core: Downgrade host log verbosity

crates/core/src/host/scheduler.rs
=> Drain scheduler Actor channel before start

.github/workflows/bottest.yml
We may want to do this once we have frozen ABI and we can be guaranteed it won't break on ABI changes, but we don't have that yet.
0
=> Don't run bot tests on every master commit whoops

LICENSE.txt
I'm updating the change date for the license. The change date is 5 years out, even though the code becomes open source after 4 years so that we don't have to constantly update the change date.
=> Updating the change date in anticipation of the anniversary

Cargo.lock, crates/schema/Cargo.toml, crates/schema/src/def.rs, crates/schema/src/def/validate/v9.rs, crates/schema/src/type_for_generate.rs
@jgilles for your consideration :) - merge base is #1661
=> Add utilities to ModuleDef for easier ues for codegen

crates/cli/src/subcommands/generate/rust.rs, crates/cli/tests/snapshots/codegen__codegen_rust.snap
Fixes the issue encountered by @kim, introduced in https://github.com/clockworklabs/SpacetimeDB/pull/1314.
=> Fix table codegen wrt table names

Cargo.lock, Cargo.toml, crates/lib/Cargo.toml, crates/lib/tests/serde.rs, crates/sats/src/de/serde.rs, crates/sats/src/ser/serde.rs
=> Make our sats<->serde translation compatible with RON

Cargo.lock, Cargo.toml, crates/planner/Cargo.toml, crates/planner/src/logical/bind.rs, crates/planner/src/logical/errors.rs, crates/planner/src/logical/expr.rs, crates/planner/src/logical/mod.rs, crates/planner/src/logical/stmt.rs, crates/planner/src/logical/ty.rs, crates/sql-parser/src/ast/mod.rs, crates/sql-parser/src/ast/sql.rs, crates/sql-parser/src/parser/errors.rs, crates/sql-parser/src/parser/mod.rs, crates/sql-parser/src/parser/sql.rs
=> refactor: Intern names in relation expressions

Cargo.lock, Cargo.toml, crates/bench/benches/subscription.rs, crates/core/Cargo.toml, crates/core/src/error.rs, crates/core/src/estimation.rs, crates/core/src/host/module_host.rs, crates/core/src/sql/ast.rs, crates/core/src/sql/compiler.rs, crates/core/src/sql/execute.rs, crates/core/src/subscription/module_subscription_actor.rs, crates/core/src/subscription/module_subscription_manager.rs, crates/core/src/subscription/query.rs, crates/core/src/subscription/subscription.rs, crates/core/src/util/slow.rs, crates/sqltest/src/space.rs
=> feat: Integrate type checking into current query code

crates/bindings-csharp/Codegen.Tests/fixtures/server/Lib.cs, crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#MultiTableRow.InsertMultiData.verified.cs, crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#Reducers.InsertData.verified.cs, crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#Reducers.ScheduleImmediate.verified.cs, crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#Test.NestingNamespaces.AndClasses.InsertData2.verified.cs, crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#Timers.Init.verified.cs, crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#Timers.SendScheduledMessage.verified.cs, crates/bindings-csharp/Codegen/Module.cs
Spent a bit of time investigating `#if`, but found that there's a better (and easier) way nowadays.
=> [C#] Mark experimental API

crates/bindings-csharp/BSATN.Runtime/Builtins.cs, crates/bindings-csharp/BSATN.Runtime/Repr.cs
These were accidentally exposed in top-level SpacetimeDB namespace. Move them to SpacetimeDB.Internal as they're not meant to be part of the public API.
so that you're confident that …
=> Hide "internal" datetime representation types

Cargo.lock, Cargo.toml, crates/cli/src/subcommands/project/rust/Cargo._toml
We have released RC1, so this PR bumps the version to RC2.
No. Just a version bump.
1
None
=> Bump version to 1.0.0-rc2

crates/physical-plan/src/compile.rs
=> Add typing context for lowering

crates/sdk/tests/test-client/src/main.rs, crates/sdk/tests/test.rs
Fixes https://github.com/clockworklabs/SpacetimeDB/issues/1950.
No
Negative risk, its just a test :)
The PR is a test.
=> Add test for light update

modules/quickstart-chat/README.md
Updated links in the Rust module quickstart-chat README.md 
None
1
I've clicked on each of the links and verified that they actually work.
=> Fixed issues with the Rust module quickstart-chat README.md

crates/bindings-csharp/BSATN.Runtime.Tests/Tests.cs, crates/bindings-csharp/BSATN.Runtime/Builtins.cs
=> Implement IComparable for Timestamp

crates/client-api/src/auth.rs
Remove out of date comment and `Credentials` impl.
1
=> Fixup comment for SpacetimeCreds

Cargo.lock, crates/core/Cargo.toml, crates/update/spacetime-install.sh, crates/update/src/cli/self_install.rs
Fixes flaky test by setting a fixed term width of 80.
1
=> Use fixed term width for cli help test

crates/client-api/src/routes/database.rs
This is a janky-short term way to restrict db creation in maincloud to users with spacetimedb accounts. We should replace this with more control over who is allowed to create new databases.
If the environment variable `TEMP_REQUIRE_SPACETIME_AUTH` is set, we will only allow database creation from users with credentials issued by `https://auth.spacetimedb.com`.
1
I tested this manually with a standalone instance.
=> hacky auth check for database creation.

crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
Adds test ensuring we follow set semantics with and without unique constraints.
None
1
This patch only adds test
=> test: set semantics in datastore

crates/standalone/Dockerfile
=> Install tls dependencies in standalone dockerfile

crates/commitlog/src/repo/fs.rs, crates/commitlog/src/stream/common.rs
Forgot to require this impl and it turns out it's needed.
1
=> Followup to #2504

crates/core/src/subscription/module_subscription_actor.rs
Adds tests asserting add_multi_subscription return errors to clients. Adds similar tests for remove_multi_subscription.
This patch also removes some redundant test utilities.
None
1
See the description
=> Add tests asserting add_multi_subscription return errors to clients

crates/commitlog/src/stream/common.rs, crates/commitlog/src/stream/reader.rs
Fix error related to fetch single commit with inclusive range.
Added test
1
=> Commitlog stream range fix.

crates/core/src/host/module_host.rs, crates/core/src/host/wasm_common/module_host_actor.rs
Part of the v8 stuff. AFAICT, none of this is actually dependent on the specific module implementation, nor is it ever going to be. If we're wrong, we can just move it back in the future.
1
=> Move init_database out of wasm_common

modules/quickstart-chat/README.md
Update URL of the Typescript SDK's exemple.
=> Update quickstart-chat README.md

crates/core/src/db/relational_db.rs
For it performs blocking I/O, and lengthily so.
1
Trivially wraps blocking code in `asyncify`
=> core: Asyncify commitlog compressor

crates/cli/src/subcommands/publish.rs
=> cli: Add value_parser for `num-replicas`

Cargo.lock, Cargo.toml, LICENSE.txt, crates/cli/src/subcommands/project/rust/Cargo._toml
Just bumping version numbers. I did **not** bump the C# bindings because we're just trying to release a server release.
None.
1
CI only
=> Bump version to 1.1.2

crates/core/src/subscription/module_subscription_actor.rs
We have instrumentation for `add_multi_subscription` but not `remove_multi_subscription`
None
0
n/a
=> add instrumentation to remove_multi_subscription

crates/core/src/client/client_connection.rs
=> Log when a websocket connection has ended

sdks/typescript/packages/sdk/package.json
Bumping this in preparation for an upcoming release.
None
1
None, just a version bump
=> TypeScript - Bump package version to 1.2.3

sdks/typescript/packages/sdk/src/client_cache.ts, sdks/typescript/packages/sdk/src/db_connection_impl.ts, sdks/typescript/packages/sdk/src/message_types.ts, sdks/typescript/packages/sdk/src/table_cache.ts
This just constrains the types of rows from `any` to `Record<string, any>`.
Not breaking, purely internal.
1
=> Added some additional typing to the TS SDK

docs/docs/spacetimeauth/index.md, docs/package.json
Minor docs change
None
1
None, trivial change
=> Small change to auth docs

crates/snapshot/src/lib.rs
Split `create_snaphot` method to expose `write_snapshot_file`.
Required for https://github.com/clockworklabs/SpacetimeDB/pull/3344
1
Exising tests
=> split create snapshot method
