clockworklabs/SpacetimeDB

crates/client-api/src/routes/database.rs

In identity recovery routes, use `IdentityForUrl`

---

crates/cli/src/subcommands/project/csharp/StdbModule._csproj

Apparently, unlike Cargo, NuGet defaults to installing *lowest* compatible version instead of *highest* one unless explicit `*` is set.
Changing this to avoid having to manually update templates on patch releases.

Auto-upgrade C# deps on installation

---

Cargo.lock
Cargo.toml
crates/bench/Cargo.toml
crates/bindings-macro/Cargo.toml
crates/bindings-sys/Cargo.toml
crates/bindings/Cargo.toml
crates/cli/Cargo.toml
crates/cli/src/util.rs
crates/client-api-messages/Cargo.toml
crates/core/Cargo.toml
crates/core/src/host/module_host.rs
crates/core/src/lib.rs
crates/lib/Cargo.toml
crates/replay/Cargo.toml
crates/sats/Cargo.toml
crates/sdk/Cargo.toml
crates/sqltest/Cargo.toml
crates/standalone/Cargo.toml
crates/testing/Cargo.toml
crates/vm/Cargo.toml
modules/benchmarks/Cargo.toml
modules/quickstart-chat/Cargo.toml
modules/rust-wasm-test/Cargo.toml
modules/spacetimedb-quickstart/Cargo.toml

Switch to [workspace cargo deps](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-dependencies-table) for better management & upgrades of deps.
Note: When 2 `.toml` have the same dependency but a different version, I pick the higher one.

Move cargo deps to the workspace

---

Cargo.lock
Cargo.toml
crates/bindings-macro/Cargo.toml
crates/bindings-macro/src/lib.rs
crates/bindings-sys/src/lib.rs
crates/core/src/db/datastore/traits.rs
crates/core/src/db/relational_db.rs
crates/core/src/host/wasmer/wasmer_module.rs
crates/core/src/sql/ast.rs
crates/lib/Cargo.toml
crates/lib/src/lib.rs
crates/lib/src/table.rs

(This is reopened #72 with some fixes.)
As we're adding more variants, it's getting harder to keep track of the "A implies B" relationships between enum variants and to correctly do checks like "is this column autoinc" in different places.
Using bitflags makes expressing those relationships more natural and checking simpler - e.g. you can just do `contains(AUTO_INC)` as a single bit operation instead of having to remember and list all possible variants that imply autoinc, especially if we're going to add more flags in the future.
Initially I was going to make this change just in C# module generator and convert between ABI enum and bitflags over there, but it seems better to do this at ABI level so it simplifies Rust handling as well.
*If the API is breaking, please state below what will …

Make ColumnIndexAttribute bitflags in the ABI

---

crates/client-api/src/lib.rs
crates/client-api/src/routes/identity.rs
crates/standalone/src/lib.rs

Corollary to https://github.com/clockworklabs/SpacetimeDB/pull/155.
This commit adds a new endpoint to the `/identity` block, which returns the public key STDB uses to decode JWTs. This will allow clients, incl. the CLI and SDKs, to verify multiple identity/token pairs without spamming STDB with requests.
The public key can also be used as a "fingerprint", to identify the server. This will allow clients to determine:
- When multiple URIs or addresses refer to the same STDB instance.
- When a STDB instance has rotated its keys, so past identities become invalid.
Downsides to consider:
- I'm not aware of a good way to encode in the response (MIME type?) that we are specifically returning an ECDSA key. All the response includes is the MIME type `application/pem-certificate-chain` (which …

Add `/identity/public-key` route to get ECDSA public key

---

crates/cli/src/subcommands/generate/csharp.rs
crates/cli/tests/snapshots/codegen__codegen_output.snap

Steve:
- Fixed json serializer settings getting re-created every reducer call, leading to gradual performance decline
John:
- During the review of this PR I figured out that option serialization support in the C# SDK was completely broken, which required some changes here to fix.
Requires this PR in order for the client to work: https://github.com/clockworklabs/spacetimedb-csharp-sdk/pull/51

Fixed json serializer getting progressively slower

---

crates/cli/src/config.rs

Aside from few more minor changes, this mostly refactors `identity_configs` and `server_configs` from `Option<Vec<_>>` to just `Vec<_>`.
As far as I can tell, they were `Option` just for (de)serialization purposes, but those can be achieved easier via Serde's `default` and `skip_serializing_if` attributes correspondingly.
As an upside, dealing with those collections everywhere else in the code becomes much simpler, since there's no more need to handle the separate `None` case or `.unwrap()` them (which actually caused some panics before).

Refactor Option<Vec<_>> in Config

---

.github/workflows/ci.yml
Cargo.lock
crates/cli/src/config.rs
crates/testing/Cargo.toml
crates/testing/src/lib.rs
crates/testing/src/sdk.rs

This switches tests from invoking a spacetimedb CLI found on PATH to always using up-to-date version by depending on the CLI crate as a library.

Avoid relying on global CLI in tests

---

crates/client-api-messages/protobuf/client_api.proto
crates/core/src/client/client_connection.rs
crates/core/src/client/message_handlers.rs
crates/core/src/client/messages.rs
crates/core/src/db/relational_db.rs
crates/core/src/host/module_host.rs
crates/core/src/host/wasm_common/module_host_actor.rs
crates/core/src/json/client_api.rs
crates/core/src/subscription/module_subscription_actor.rs
crates/core/src/subscription/query.rs

Support one-off queries without establishing a subscription. Took me a while to figure out all the routing. This is (NO LONGER) TOTALLY UNTESTED.
The SQL engine seems to support returning multiple tables so I've routed that through to the client, but I have no idea what queries would actually use that -- @mamcx ?
Also, I don't know how to validate that a query only SELECTs and doesn't do anything else.
@jdetter

One-off query support

---

Cargo.toml
crates/core/src/startup.rs

We don't want to write to disk on spacetimedb cloud. This PR allows disabling logging to disk

Allow disabling logging to disk

---

crates/core/src/db/relational_db.rs
crates/core/src/vm.rs
crates/vm/src/eval.rs
crates/vm/src/expr.rs

Fixes #311.
This change makes it so that our internal join representation can take arbitrary query expressions for its right argument.
Previously only base table references were supported.
This is will allow pushing operations like index scans below joins.

feat(311): Make right hand side of join generic

---

test/tests/permissions-private-table.sh

Test that tables whose name starts with '_' (underscore) can only be queried by the database owner.

Add smoke test for private tables

---

crates/bindings-macro/src/lib.rs
test/tests/filtering.sh

Remove Table::{update,delete}

---

crates/client-api/src/lib.rs
crates/client-api/src/routes/database.rs
crates/standalone/src/lib.rs

In the client API's `log_and_500`, return an `ErrorResponse` with a body derived from the error, rather than a bare 500 code.
Note that this exposes previously-internal error messages to users.
The error messages newly reported by the CLI are not beautiful, but they at least describe the failure. Also, this PR does not improve the status codes returned; errors in e.g. `/database/publish` always return 500 (`INTERNAL_SERVER_ERROR`), where they should often report more-specific errors, some of which put the client at fault rather than the server. Still, it's an improvement.
Attempting to publish to a name you don't own:
```
Error: Permission denied: `974ab31b518f46d0b59b0afee78abdf2dbf4df6e60a332dce9c373ab8bebcea6` does not own database `5ebd1221afb10aaf`
```
Attempting to publish a …

Return the formatted error from `log_and_500`, so the CLI can report it

---

crates/bench/benches/generic.rs

Based on my limited understanding of Criterion, I think we can get add transactions per second reporting to benchmarks using Criterion's Throughput::Elements tracking, by treating transactions as elements.
This is not ideal, as the output says e.g. `thrpt:  [38.763 Kelem/s 38.781 Kelem/s 38.799 Kelem/s]`, where we'd like `Ktx/s`, but it's not clear whether Criterion allows us that much customization.
Each of the benchmarks currently does one tx per iteration, so pass `Throughput::Elements(1)` for each of them. Do this as close to the test as possible, despite redundancy, in case we ever add benchmarks to the same group which do multiple transactions per iteration.

Benchmarks: report tx/s as elements/s

---

crates/sdk/tests/connect_disconnect_client/README.md
crates/sdk/tests/test-client/README.md

Add simple READMEs for SDK test clients

---

Cargo.lock
Cargo.toml
crates/testing/Cargo.toml
crates/testing/src/sdk.rs

We've had continual issues with test isolation when developing breaking changes. This commit doesn't fully address those, but is a step in the right direction: the SDK tests now create a tempdir as their `STDB_PATH`, rather than using `~/.spacetime`.

SDK tests use a tempdir as STDB_PATH, rather than ~/.spacetime

---

crates/bindings-sys/src/lib.rs
crates/bindings/src/lib.rs
crates/bindings/src/time_span.rs
crates/core/src/host/wasm_common.rs
crates/core/src/host/wasmer/wasm_instance_env.rs
crates/core/src/host/wasmer/wasmer_module.rs

At a high level, define a struct `Span` in `bindings` which manages a timing span, with methods `start` and `end` to begin and end timing, respectively. `Span::start` records the `Instant` of its call; `Span::end` computes the elapsed `Duration` and prints it to the module logs.
At a low level, add a slab of timing spans to WasmInstanceEnv, with ABI functions `_start_span` and `_end_span` to implement `Span::start` and `Span::end`.

Preliminary module-side interface for timing execution

---

crates/bindings-sys/src/lib.rs
crates/bindings/src/lib.rs
crates/core/src/host/instance_env.rs
crates/core/src/host/wasmer/mod.rs
crates/core/src/host/wasmer/wasm_instance_env.rs

Improve precision in the bindings, bindings-sys, wasm_instance_env docs.

Bindings: improve docs precision

---

.github/workflows/linux-client.yml

It was building Intel/AMD64 executables instead of ARM64.

Fix arm64 builds on Linux

---

.github/workflows/linux-build.yml

Fix errors with building CLI for Aarch64

Fix AMD64 dependency error in CLI Docker Build

---

crates/client-api/src/routes/subscribe.rs
crates/core/src/util/future_queue.rs

Ok I guess it was kinda a deadlock in the semaphore. I guess that's why they say FuturesUnordered is a footgun, huh. Basically, it was given the permit but not waking up because we weren't polling `handle_queue` anymore at that point. See [Status quo of an AWS engineer: Solving a deadlock](https://rust-lang.github.io/wg-async/vision/submitted_stories/status_quo/aws_engineer/solving_a_deadlock.html).

Fix deadlock

---

crates/bench/benches/generic.rs
crates/bench/benches/special.rs

Get `cargo bench --all` compiling again.

Get benchmarks type checking again

---

crates/bench/src/spacetime_module.rs

Imperfect workaround for #401 that caused clean rebuild of SpacetimeDB with all 3rd-party deps each time you do `cargo bench`.

Compile benchmarks in separate folder

---

crates/bindings-csharp/Runtime/bindings.c
crates/bindings-csharp/Runtime/build/SpacetimeDB.Runtime.targets
crates/bindings-sys/src/lib.rs
crates/bindings/src/lib.rs
crates/cli/src/subcommands/generate/mod.rs
crates/core/src/host/wasm_common.rs
crates/core/src/host/wasm_common/abi.rs
crates/core/src/host/wasm_common/module_host_actor.rs
crates/core/src/host/wasmer/mod.rs
crates/core/src/host/wasmer/wasmer_module.rs
crates/lib/src/lib.rs

Switch to using imported module idents for marking version requirements

---

.github/workflows/benchmarks.yml
crates/bench/benches/generic.rs
crates/bench/src/database.rs
crates/bench/src/lib.rs
crates/bench/src/spacetime_module.rs
crates/bench/src/spacetime_raw.rs
crates/bench/src/sqlite.rs

Attempting to address #401 #402 #403

Put out benchmark fires

---

Cargo.lock
Cargo.toml

By default cursive uses ncurses, which is Unix-only library. This led to build failures on Windows due to dependency on cursive in the workspace itself.
As a simple fix I'm switching it to a pure Rust cross-platform backend (crossterm).

Switch cursive to cross-platform backend

---

Cargo.lock
Cargo.toml
crates/core/Cargo.toml
crates/core/src/host/instance_env.rs
crates/core/src/host/wasm_common.rs
crates/core/src/host/wasmer/wasm_instance_env.rs

Initially we used iterator because we wanted to lazily pull values from the database when Wasm requests the next item, so that e.g. early stop works as expected and doesn't read too much data.
Unfortunately, we discovered that this leads to crashes when someone tries to iterate over the database and update/delete items inside the iteration since iteration itself held a lock. We added a workaround by collecting the iterator early into a Vec, and then returning a newly created iterator to the user. This fixed the issue, but at this point lazy iterator mechanism turned from an optimisation into pure overhead - if we want to collect Vec, we might as well do this early in the pipeline and avoid an extra dependency.
This slightly improves iteration of empty tables as it only reduces allocation …

Collect iterator into chunks early

---

crates/lib/src/error.rs
crates/lib/src/identity.rs
crates/lib/src/relation.rs
crates/vm/src/expr.rs

Make all mutating SQL operations require the caller to be the database owner.
1

Fix authorization check for CrudCode

---

crates/bindings-csharp/Runtime/Runtime.cs
crates/bindings-csharp/Runtime/bindings.c
crates/bindings-sys/src/lib.rs
crates/bindings/src/lib.rs
crates/core/src/host/instance_env.rs
crates/core/src/host/wasmer/wasmer_module.rs
crates/lib/src/lib.rs

I'm not sure why we're sending encoded schema as this special first element of iteration.
There is some commented out code that suggests it might have been used in the past, but at least nowadays modules (both Rust and C#) are strongly typed and already know the schema of the tables they asked to iterate over, and ignore the first element returned from the iteration.
As a result, we've been unnecessarily reading schema, encoding it into binary, taking care to allocate it as individual small blob, stored in list of buffers and sent it between Wasm and Rust just for it to be ignored.
Removing it simplifies code and if we ever want to get table schema, we can do that via a dedicated method rather than send it automatically on beginning of each iteration.
This is an ABI breaking change, but …

[ABI] Remove the special first element of iterator

---

.github/workflows/benchmarks.yml
crates/cli/src/tasks/mod.rs

Now that our ABI checks can handle binaries produced by wasm-opt, we can use it (if installed) to optimise produced Wasm binaries.
For now it's added as an optional step until we figure out a decent deployment strategy to automatically get it for the user. (There are some wrappers on crates.io, but they tend to lag behind modern versions and take a while to compile, whereas Binaryen provides official prebuilt binaries on Github.)
This gives an easy 8-10% performance boost in iteration benchmarks, much more for an empty table but that's less interesting.
1
but also to its …

Optimise binaries with wasm-opt

---

crates/core/src/db/datastore/locking_tx_datastore/mod.rs
crates/core/src/db/datastore/locking_tx_datastore/table.rs

We don't need row ranges, we only (loosely) care about stable iteration order, so we can switch to cheaper IndexMap (HashMap) instead of using a B-Tree.
This small change shows noticeable improvement to both iteration and insertion ops across the board as they all use `rows` (only extracted results for raw in-memory DB as the module ones are currently way too noisy even on CI):
| schema   | index type  | load | new latency      | old latency      | new throughput | old throughput | 
|----------|-------------|------|------------------|------------------|----------------|----------------|
| location | multi_index | 1000 | 24.7±0.81µs      | 29.4±0.79µs      | 39.6 Ktx/sec   | 33.2 Ktx/sec   | 
| location | non_unique  | 1000 | 16.4±0.04µs      | 19.4±0.08µs      | 59.5 Ktx/sec   | 50.4 …

Switch rows to IndexMap

---

crates/core/src/vm.rs
crates/lib/src/error.rs
crates/lib/src/relation.rs
crates/vm/src/eval.rs
crates/vm/src/expr.rs

There is no guarantee that a named field is in the supplied table header, nor that it is in the row. Panicking at this location can be disastrous, while all call sites are inside Result already. So, return Result.
1

lib: Don't panic in RelValueRef::get

---

crates/core/src/db/datastore/locking_tx_datastore/mod.rs
crates/core/src/db/datastore/traits.rs
crates/core/src/db/relational_db.rs
crates/core/src/host/instance_env.rs
crates/core/src/host/wasmer/wasm_instance_env.rs
crates/core/src/vm.rs

These functions and methods now clone less and collect keys/ids to rename/drop/delete rather than storing a cloned `ProductValue` that is then used to do the work.
2

Optimize `drop_table`, `rename_table`, `delete_by_col_eq`, and `clear_table`

---

crates/core/src/sql/compiler.rs
crates/core/src/vm.rs
crates/vm/src/eval.rs
crates/vm/src/expr.rs
crates/vm/src/typecheck.rs

Previously, an UPDATE statement would be the identity function. Fix this by threading through the assignments (SET clause) and transforming the rows matching the query.
2

vm: Make UPDATE actually update

---

Cargo.lock
Cargo.toml
crates/bench/Cargo.toml
crates/bench/benches/generic.rs
crates/bench/benches/special.rs
crates/cli/Cargo.toml
crates/cli/src/main.rs

We are doing a lot of allocations / clones, and I figured it might be worth looking into high-performance allocators as an easy win among other things.
mimalloc generally beats other allocators and would make the biggest difference in multi-threaded environment (such as an actual cloud) as it has separate per-thread pools.
However, it makes a noticeable difference even in our single-threaded benchmarks:
<details><summary>Benchmark results</summary>
Legend:
- `load`: number of rows pre-loaded into the database
- `count`: number of rows touched by the transaction
- index types:
- `unique`: a single index on the `id` column
- `non_unique`: no indexes
- `multi_index`: non-unique index on every column
- schemas:
- `person(id: u32, name: String, age: u64)`
- `location(id: u32, x: u64, y: u64)` …

Switch allocator to mimalloc for the DB CLI

---

crates/sdk/src/background_connection.rs
crates/sdk/src/callbacks.rs
crates/testing/src/sdk.rs

This error turns out to have been a legitimate, albeit rare, race condition, which could have (but apparently didn't) manifested in user code.
The cause, ultimately, was holding locks for too-short scopes while initializing the connection. It was possible for a new connection to receive and completely process its `IdentityToken` message before calling `maybe_set_credentials`, which would then clobber the received identity.
This is now fixed (hopefully) by holding the `CredentialStore` lock for the duration of `BackgroundDbConnection::connect`.
Two other locks, on `ClientCache` and `ReducerCallbacks`, are also newly held for the duration to avoid similar issues.
In addition, this commit adds a call to `disconnect` to the beginning of `connect`. This will prevent pathological user code …

Fix "identity not yet recieved" intermittent failure in tests

---

crates/core/src/db/commit_log.rs

Previously, constructing the commit payload to append to the message log was done without holding the lock on the latter. This meant that commits could be written to the log out-of-order.
Indeed, this could be observed on deployed databases by virtue of verifying the hash chain (the parent hash is computed in `generate_commit`).
To fix this, the lock is now acquired immediately and held until the message is written (and potentially fsync'ed).
2.5
The fix is fairly obvious, but will nevertheless require careful review due to the critical nature of the subsystem.

core: Fix commit log concurrency

---

.github/workflows/benchmarks.yml

See [the successful workflow run](https://github.com/clockworklabs/SpacetimeDB/actions/runs/6635475151/job/18026454949) and [the comment it posted](https://github.com/clockworklabs/SpacetimeDB/pull/457#issuecomment-1778457495)

Use gh actions for benchmarks please

---

crates/bindings-csharp/Codegen/Codegen.csproj
crates/bindings-csharp/Codegen/Utils.cs
crates/testing/tests/standalone_integration_test.rs
modules/spacetimedb-quickstart-cs/Lib.cs

At some point the code was switched to use the full type name helper to resolve types regardless of if they're in scope. The helper didn't include generic params which broke things like `List<...>` as reported in the chat.
This fixes the issue by... well, including generic params.
1

Fix C# generics support

---

crates/bindings-csharp/Runtime/Module.cs
crates/bindings-csharp/Runtime/bindings.c
crates/bindings/src/rt.rs
crates/client-api/src/routes/subscribe.rs
crates/core/src/client/messages.rs
crates/core/src/database_instance_context.rs
crates/core/src/database_logger.rs
crates/core/src/db/commit_log.rs
crates/core/src/db/datastore/locking_tx_datastore/mod.rs
crates/core/src/db/datastore/traits.rs
crates/core/src/db/db_metrics/mod.rs
crates/core/src/db/mod.rs
crates/core/src/db/relational_db.rs
crates/core/src/db/update.rs
crates/core/src/execution_context.rs
crates/core/src/host/instance_env.rs
crates/core/src/host/mod.rs
crates/core/src/host/module_host.rs
crates/core/src/host/wasm_common/module_host_actor.rs
crates/core/src/host/wasmer/wasm_instance_env.rs
crates/core/src/host/wasmer/wasmer_module.rs
crates/core/src/util/mod.rs
crates/core/src/util/typed_prometheus.rs
crates/lib/src/address.rs
crates/sats/src/product_value.rs

Simplify/deabstract module_host_actor and wasmer_module

---

crates/core/src/db/datastore/locking_tx_datastore/mod.rs
crates/core/src/db/datastore/traits.rs
crates/core/src/db/db_metrics/mod.rs
crates/core/src/db/relational_db.rs
crates/core/src/db/update.rs
crates/core/src/host/module_host.rs
crates/core/src/host/wasm_common/module_host_actor.rs
crates/core/src/vm.rs
crates/standalone/src/lib.rs

perf(468): Add metric counters for committed transactions and rollbacks

---

crates/cli/src/tasks/mod.rs

C# generates Wasm code that uses some of the newer performance features (notably, bulk memory ops) and wasm-opt rejects any such instructions by default (there were talks about changing this behavious upstream but that never went anywhere).
Activate all features so that wasm-opt works on anything produced by our compilers, as well as make any future failures a non-critical error just in case.
*If you answered more than a 2, explain what …

Fix wasm-opt for C# modules

---

crates/core/src/db/datastore/traits.rs
crates/core/src/db/update.rs

Reroll of #368 on top of #416
Mainly changes the database update logic to consider multi-column indexes defined in the module (previously, we would only create single-column indexes). Even though multi-column indexes are not fully landed yet, _some_ queries can utilize them.
Also adds tests.
1.5

Create multi-column indexes defined in modules

---

Cargo.lock
Cargo.toml
crates/cli/Cargo.toml
crates/cli/src/lib.rs
crates/cli/src/subcommands/mod.rs
crates/cli/src/subcommands/upgrade.rs
crates/cli/src/subcommands/version.rs

- Adds `spacetime upgrade` command, which allows you to upgrade your spacetime-cli version to the latest version, or a version of your choosing.
- If you already have the version that you're trying to upgrade to, then no action is performed
Note: Its possible to downgrade to a version of spacetimedb that doesn't have the `spacetime upgrade` command, which means in order to upgrade again you'll have to follow the installation instructions on the spacetimedb.com website.
This has been tested on all 3 platforms: macOS, Linux and Windows.
Try to upgrade to the latest version, 0.7.1:
```
> spacetime upgrade       
Finding version...done.
You are currently running version 0.7.2 of spacetime. The version you're upgrading to is 0.7.1. …
```

Spacetime Upgrade

---

crates/cli/src/subcommands/generate/csharp.rs

Generate the OptIn Json.NET attribute (https://www.newtonsoft.com/json/help/html/JsonObjectAttributeOptIn.htm) for autogenerated C# types.
This fixes a bug where user generated properties in partial classes get serialized to json as well. This caused a deserialization issue on the server, when a user generated property was the last one, resulting in the following error:
1
*If you answered more than a 2, explain what is complex about the …

Add OptIn serialization attribute for C# generated types

---

Cargo.lock
Cargo.toml
crates/core/Cargo.toml
crates/core/src/db/commit_log.rs
crates/core/src/db/messages/commit.rs
crates/core/src/db/messages/transaction.rs
crates/core/src/db/messages/write.rs

Use `sats::{BufReader, BufWriter}` for decoding / encoding of `Commit`
and associated types. This makes `decode` fallible (which is quite
desirable, instead of panicking).
As the `DecodeError` from sats is fairly sparse, also add some context
about where exactly decoding failed.
Also add documentation and property test.
1

Refactor commit encoding / decoding

---

Cargo.lock
crates/core/Cargo.toml
crates/core/src/db/messages/commit.rs
crates/core/src/db/messages/write.rs
crates/lib/Cargo.toml
crates/lib/src/data_key.rs
crates/lib/src/hash.rs

Allows to remove custom strategies for the commit log types (in core), and may become useful for future property testing efforts.
**This is stacked on top of #495. Do not merge until after #495 is landed.**
1

lib: Provide `Arbitrary` impls for `Hash` and `DataKey`

---

crates/testing/tests/standalone_integration_test.rs
modules/rust-wasm-test/src/lib.rs

Just adds usage of the multi column index macro feature
`

Added multi column index usage to the rust-wasm-test module

---

crates/core/src/host/module_host.rs
crates/core/src/util/lending_pool.rs
crates/core/src/worker_metrics/mod.rs

Track instance_queue_length by reducer

---

crates/core/src/db/commit_log.rs
crates/core/src/db/message_log.rs

~~Prerequisite for being able to truncate log segments without seeking, e.g. while replaying up until a corrupted record.~~
Above did not turn out to be feasible, but I think the additional error context is worthwhile.
1

core: Track the number of bytes read when iterating over the WAL

---

crates/core/src/host/instance_env.rs
crates/core/src/host/wasmer/wasm_instance_env.rs

Fixes an issue that BitCraft were having (spamming INFO messages).
No breakage as the ABI of u32 and the non-zero variant are the same.
1 - trivial simple diff with low risk.

`InstanceEnv::delete_by_col_eq`: return `u32` instead of `NonZeroU32`

---

crates/core/src/db/message_log.rs

Adds a method `reset_to(offset)` to `MessageLog`, which allows to truncate the log to the given message offset.
Note that this currently requires to iterate over the last segment until the message offset is found -- we may in the future maintain an offset index (a la Kafka) to be able to seek closer to the desired message offset.
`reset_to` subsumes the unused `reset_hard` method, and is itself not yet used (this will be added in a later patch).
**Note** The first commit is submitted separately in #496 
3

core: Add truncation to message log

---

.github/workflows/docker.yml

This PR disables tagging with `latest` tag

Disable latest docker tag

---

crates/core/src/db/commit_log.rs
crates/core/src/db/message_log.rs
crates/core/src/db/relational_db.rs
crates/core/src/error.rs

When replaying the log, stop if a commit is encountered which cannot be decoded. As this implies a corrupted log, truncate the log to the known-good prefix.
**Depends on #526**
3 -- the risk of truncating the commit log wrongly is data loss.

core: Replay database prefix

---

crates/core/src/db/datastore/locking_tx_datastore/mod.rs

It is significant for forensics to differentiate the source of the row data being decoded. Change the error messages to that end.
1

core: Refine panic message when decoding fails during replay

---

crates/core/src/database_instance_context.rs
crates/core/src/db/commit_log.rs
crates/core/src/db/relational_db.rs

Makes `CommitLog` a read-only handle and introduces `CommitLogMut`,
allowing to append. This better encapsulates the error detection and
trimming logic, and enforces it to be executed before being able to
mutate the log.
~~**Stacked on top of #527**~~
~~[Compare](https://github.com/clockworklabs/SpacetimeDB/compare/kim/truncate-log-in-replay...kim/move-replay-to-commit-log)~~
-
2

core: Move replay + error correction logic to commit log

---

crates/core/src/db/commit_log.rs

Prevent writing `DataKey::Inline` data to the odb redundantly. _May_ reduce memory pressure, and will help with keyspace traversals.
2

core: Only write actual large objects to odb

---

crates/core/src/host/wasm_common/abi.rs
crates/core/src/host/wasmtime/mod.rs

helps with the 0.7 -> 0.8 transition

Error for no abi version

---

crates/cli/src/subcommands/publish.rs
crates/core/src/host/host_controller.rs
crates/core/src/messages/control_db.rs
crates/standalone/src/lib.rs

Per @kim's comment:
> I’d prefer if we just named the host type Wasm — it seems very unlikely that we’ll support multiple runtime implementations ever. That is, if we gain another variant it will be Csharp or whatever.
That does make sense to me - the decision to name the host type Wasmer/Wasmtime was made about a year ago, in case we wanted to have both at the same time, and we never took advantage of that and I don't think we ever will (and I think we've pretty conclusively settled on wasmtime as our runtime). I was more or less content having it be like that but if other people feel it's worth changing I'm happy for it.
2 - in a similar way to #457 this is sorta theoretically an http API breaking change to the `/publish` route, but that doesn't actually ever get exercised anyway. And …

Rename HostType::Wasmtime to just Wasm

---

crates/core/src/db/commit_log.rs
crates/core/src/db/datastore/locking_tx_datastore/mod.rs
crates/core/src/db/ostorage/memory_object_db.rs
crates/core/src/db/relational_db.rs
crates/core/src/error.rs

Instead of deferring object storage loads to when they're needed, load them in the `Replay` iterator. This allows to handle log trimming logic uniformly for the situation when a commit happened to be flushed to disk, but object storage didn't.
Nein.
3
Trims the log if the missing object is within the last segment. Previously, missing objects manifested as a panic.

core: Load large objects eagerly during log replay

---

crates/core/src/db/db_metrics/mod.rs
crates/core/src/worker_metrics/mod.rs

perf(610): More granular histogram buckets for timing metrics

---

crates/core/src/db/commit_log.rs
crates/core/src/db/relational_db.rs
crates/core/src/error.rs

See the main code comment.
I think until we have a better log format, or at the very least, better diagnostic tooling, we shouldn't ignore OutOfOrder errors.
It's not apparent that we'll see such errors in practice due to the the more lenient fsync policy.

fix(CommitLog): Do not truncate the log on out of order errors

---

crates/core/src/db/datastore/locking_tx_datastore/mod.rs

I am trying to see if we can remove the optional `MutTxId` since it's stored inside the `MutTxId` and it never really makes sense for it to be `None`, if my understanding is correct. I'm 90% sure it is.
It is not.
2

Removed the tx_state lock from the MutTxId, since it's no longer needed

---

.github/workflows/ci.yml
crates/bindings-csharp/Codegen/Codegen.csproj
crates/bindings-csharp/Codegen/Module.cs
crates/bindings-csharp/Runtime/Module.cs
crates/bindings-csharp/Runtime/RawBindings.cs
crates/bindings-csharp/Runtime/Runtime.cs
crates/bindings-csharp/Runtime/Runtime.csproj
crates/bindings-csharp/Runtime/bindings.c
crates/bindings-csharp/Runtime/build/SpacetimeDB.Runtime.targets
crates/bindings-csharp/Runtime/driver.h
crates/cli/src/subcommands/project/csharp/StdbModule._csproj
crates/cli/src/tasks/csharp.rs
modules/sdk-test-connect-disconnect-cs/StdbModule.csproj
modules/spacetimedb-quickstart-cs/StdbModule.csproj

.NET 8 shipped last week with built-in WASI support. It's still marked as experimental because some things - like better import/export handling that we could use - are still being worked on, but it's already better than using the `Wasi.Sdk` package which is now soft-deprecated and has a number of bugs that nobody's going to fix anymore.
This change is pretty big because it tries to move from custom Mono C APIs to native C# marshalling as much as possible, because it's now supported, it's safer, and it's more future-proof. We should be able to eventually remove the `bindings.c` layer altogether once `UnmanagedCallersOnly` and `DllImport` are handled automatically and generate Wasm imports/exports by .NET's PInvoke, which is already available in .NET alpha channel. It also provides better …

Move to .NET 8 WASI support

---

Cargo.lock
Cargo.toml
crates/core/Cargo.toml
crates/core/src/database_instance_context_controller.rs
crates/core/src/worker_metrics/mod.rs

These metrics are already tracked via kubernetes.
And sys-info does not appear to be accurate on virtual systems anyway.
Furthermore what we really want are disk and memory usage metrics per database.
We already track disk usage for the wal, objectdb, and module logs.
Tracking memory usage per database requires a custom allocator.
and what …

refactor: Remove global disk and memory tracking

---

crates/core/src/db/db_metrics/mod.rs
crates/core/src/util/typed_prometheus.rs
crates/core/src/worker_metrics/mod.rs

Prometheus metric builders should not have any outside dependencies, other than prometheus.

refactor(metrics): Remove dependencies of metric builder macros

---

Cargo.lock
crates/bench/src/spacetime_module.rs
crates/bindings-csharp/Runtime/Filter.cs
crates/core/src/database_logger.rs
crates/testing/Cargo.toml
crates/testing/src/modules.rs
crates/testing/tests/standalone_integration_test.rs
modules/spacetimedb-quickstart-cs/Lib.cs
modules/spacetimedb-quickstart/src/lib.rs

Unlike Rust, previously this would only accept literal constants and not field captures.
Unlike Rust, this will now accept not only constants and captures, but arbitrary expressions - we can either do the same in Rust or limit this similarly in the future.
Some of the changes here are just to add queries to primary integration tests too and make checking logs a bit easier, feel free to review on per-commit basis.
2 - this is using special C# dynamic evaluation API to evaluate non-constant RHS expressions, but tests show it works as expected in practice.
where 1 is a trivial change, and 5 is a deep-reaching and complex …

Support arbitrary RHS in C# Query

---

crates/core/src/db/message_log.rs

Not great, but potentially TERM will let finalizers run usually.
Seems to fix the zz-* smoketests.

Try to fsync message log on drop

---

Cargo.lock
crates/core/src/db/commit_log.rs
crates/core/src/db/datastore/locking_tx_datastore/mod.rs
crates/core/src/db/db_metrics/mod.rs
crates/core/src/db/relational_db.rs
crates/lib/Cargo.toml
crates/lib/src/lib.rs
crates/lib/src/metrics.rs

Query optimization will soon need this metric.
Therefore it must be moved out of core and into lib. Eventually we might want to move all metrics into lib.

refactor(metrics): Move table size metric into lib

---

crates/bindings-csharp/Runtime/Runtime.csproj
crates/bindings-csharp/Runtime/build/SpacetimeDB.Runtime.props
crates/bindings-csharp/Runtime/build/SpacetimeDB.Runtime.targets
modules/Directory.Build.props
modules/Directory.Build.targets
modules/sdk-test-connect-disconnect-cs/StdbModule.csproj
modules/spacetimedb-quickstart-cs/StdbModule.csproj

As usual, NuGet / MSBuild behaving differently for local projects vs published ones causes build issues that are not revealed by testing...
This is published to NuGet now and verified to work on an empty project.
Also changed the way `SpacetimeDB.Runtime.{props,targets}` are referenced locally by test projects by moving them to `Directory.Build.{props,targets}` at the top level of `modules/` directory.
This should simulate behaviour of published NuGet packages a bit more closely - in particular, I verified that it can reproduce the bug in question before the fix, while the previous `<Import />` approach succeeded regardless - and also makes it easier to share the same configs between multiple projects. …

Fixes for SpacetimeDB.Runtime package

---

crates/core/src/database_instance_context.rs
crates/standalone/src/lib.rs

Instantiation of a database is inherently fallible, so should take down the whole process.

core: Remove unwraps from DatabaseInstanceContext

---

crates/core/src/sql/compiler.rs
crates/core/src/subscription/query.rs
crates/core/src/subscription/subscription.rs
crates/core/src/vm.rs
crates/sats/src/relation.rs
crates/vm/src/expr.rs

Before this patch we made reference to the "lhs" and the "rhs" of an index join, in the context of incremental evaluation.
This patch further generalizes the incremental evaluation of index joins, by replacing such references with either the probe side or the index side. This is in preparation for adding more types of incremental evaluation plans.
but also to its interactions with existing and future …

refactor(subscriptions): Support returning either side of a join

---

crates/core/src/subscription/subscription.rs

If an index join has a delta table on its probe side, the plan is already optimal,
so do not reorder the index and probe sides of the join.

test(compiler): Optimizing index join with virtual probe table is no-op

---

crates/core/src/vm.rs
crates/vm/src/expr.rs

This patch removes the invalid translation from IndexJoin to JoinExpr, since there is no way to capture the implicit projection of IndexJoin. Instead we translate from IndexJoin directly to QueryExpr.
and what other components it interacts with in potentially concerning …

test(compiler): From index to inner join

---

crates/core/src/db/datastore/locking_tx_datastore/mod.rs
crates/core/src/db/datastore/traits.rs
crates/core/src/db/relational_db.rs
crates/core/src/sql/ast.rs
crates/core/src/sql/compiler.rs
crates/core/src/sql/execute.rs
crates/core/src/vm.rs

1. moving from concrete type to use of associate type for tx, this wil help to adapt different type of transaction later
i.e to use   `relational_db::MutTx` instead of MutTxId, and `realtional_db::Tx` for `compiler.rs` as that is suppose to work with read only tx.
2. changed `traits::MutTxId` -> `traits::MutTx`, similarly for `traits::TxId` as none of them mean to refer to any id.
1

Use associate type for tx

---

crates/core/src/database_instance_context.rs
crates/core/src/database_instance_context_controller.rs
crates/standalone/src/lib.rs

Access to the DatabaseInstanceContextController is racy, as another `get` may occur while a new DatabaseInstanceContext is initializing. Because the database acquires filesystem locks, this will lead to errors.
To fix this, the context value is wrapped in a OnceCell.

core: Initialize the database context only once

---

crates/core/src/db/update.rs
test/tests/update-module.sh

The `TableDef` type is nominally the same for the database schema and
the schema description from a module, but only the former contains
information about indexes and sequences. This would cause all indexes to
be dropped when updating a database, because none of the existing
indexes would ever be present in the module's schema definition.
It is unclear if the functionality could be recovered, but it does not
seem to be robust without a dedicated schema manipulation language
either way.
We still want to allow module updates which do not change the schema at
all, or only introduce new tables, as otherwise users may be forced to
re-run expensive initialisation steps even though they only introduced
debugging code or somesuch.
To make this work, a somewhat dubious equivalence comparison is …

core: Remove index update when updating a database

---

crates/core/src/db/datastore/locking_tx_datastore/mod.rs
crates/core/src/db/datastore/traits.rs
crates/core/src/db/relational_db.rs
crates/core/src/host/module_host.rs

This commit changes the `MutTxDatastore` trait's method `table_name_from_id_mut_tx` method to return a `Cow<str>` rather than an `&str`, abstracting away whether the underlying datastore stores a contiguous `str` table name.
As with PR #691, our current datastore has a `String` to which it can return an `&str`, but the mem-arch-prototype stores a new representation where strings are not necessarily contiguous, so it must extract the table name and return an owned `String` rather than an `&str`.
1
*This complexity rating applies not only to the …

`MutTxDatastore::table_name_from_id_mut_tx`: return `Cow<str>`

---

Cargo.lock
Cargo.toml
crates/client-api/Cargo.toml
crates/client-api/src/auth.rs
crates/client-api/src/routes/database.rs
crates/client-api/src/routes/subscribe.rs
crates/client-api/src/util.rs
crates/client-api/src/util/websocket.rs
crates/standalone/src/subcommands/start.rs

Had this on the backburner for a bit, whoops. This brings us to depending on Hyper 1.0.
Hyper 0.14 is still in the dependency tree, but once reqwest updates we'll be
fully moved over.
2

Update to axum 0.7

---

crates/core/src/host/wasm_common.rs
crates/core/src/host/wasm_common/module_host_actor.rs
crates/sats/src/typespace.rs

Database is currently unable to handle algebraic type references in table fields - that especially covers recursive types, but breaks even simple cases like type aliases that are stored in the typespace and referenced from multiple other types.
This was breaking C# SDK tests (upcoming in a separate PR to keep things simple to review), and it's relatively easy to make a repro that would break Rust modules too.
A proper support for arbitrary references and mutual recursion would be complex and out of scope, so for now we talked with @gefjon and agreed on a simpler workaround where all type references in tables are recursively inlined as their destination types during init. This allows to gracefully report errors on any recursion and support type references otherwise.
If this is an API or …

Inline typerefs

---

crates/cli/src/subcommands/generate/mod.rs

This is a minor change but has bothered me for as long as I remember - I believe there is no reason to error out if directory doesn't exist; most users will expect the tool to create the output dir, so we can do just that.
1

Create output directory in `generate` if it doesn't exist

---

crates/standalone/src/lib.rs

Fixes #707.
Previously the table size metric definition was moved to a different crate. This was to facilitate its use in query optimization. However as part of that change it was never added back into the prometheus registry. This resulted in the metric no longer being collected by prometheus. This patch reintroduces it back into the registry, forcing its collection, again.
but also to its …

fix(707): Collect table size metrics again

---

crates/core/src/db/datastore/locking_tx_datastore/mod.rs
crates/core/src/db/db_metrics/mod.rs
crates/core/src/subscription/query.rs
crates/core/src/subscription/subscription.rs

Fixes #684.
Prometheus does not reset metrics.
It only updates them with new values that it collects. If it does not receive a new value for a metric, it will keep the old value.
Therefore it is important to periodically reset certain metrics. Namely gauge metrics that only receive updates occasionally.
Maximum reducer duration is one such example,
since some reducers run much more infrequently than others.
*This complexity rating applies not only to the complexity apparent in …

fix(684): Reset max value metrics

---

.github/workflows/benchmarks.yml
.github/workflows/callgrind_benchmarks.yml

This fixes two things:
Specifically, we chmod the git repo directory to a+rw after we touch it in the callgrind benchmarks action.
This is needed because the callgrind benchmarks run as root in a docker container. Github Actions tries to reuse the resulting directory (and I guess stores it on the host?) afterwards, but now the git repo is owned by root and can't be modified, which causes other benchmarks to break.
This issue was pointed out by @coolreader18.
(Note: we can't just chown the git repo, because we're inside a docker image, so who would we chown to?)
I pulled out the `markdown-report[-callgrind]` commands from the `benches/summarize` bin in my last callgrind PR -- they've moved to another repo -- but there were residual references to them in these ymls, despite the resulting …

Fix benchmark actions

---

crates/core/src/db/db_metrics/mod.rs
crates/core/src/db/relational_db.rs
crates/core/src/worker_metrics/mod.rs

chore: Remove unused metrics

---

crates/core/src/db/db_metrics/mod.rs
crates/core/src/subscription/query.rs

Query metrics have very high cardinality.
The current metrics store does not handle high cardinality particulary well. Query compilation contributes very little to overall resource consumption. Therefore they have been disabled until the cardinality issue has been addressed.
*If you answered more than a 2, explain what is complex about the …

chore: Disable query compilation metrics

---

crates/core/src/host/scheduler.rs
crates/core/src/worker_metrics/mod.rs

Max value metrics are currently reset to zero after each collection period. However this won't be reflected in the metrics store immediately.
Once the database records new values for said metrics, only then will the reset be reflected in the metrics store.
This subtlety is imperceptible for metrics that are frequently updated. But if a metric is not frequently updated,
or for periods of reduced load in general,
the metrics store may present stale max value metrics.
This anomaly was thought to have been fixed by #709. However it only fixed it for DB_METRICS.
This patch removes the anomaly for WORKER_METRICS as well.
*How …

fix: Reset max queue length and reducer wait time metrics

---

crates/core/src/subscription/module_subscription_actor.rs

Made `broadcast_commit_event` multithreaded to leverage read locks.

made subscription broadcast multithreaded

---

.github/workflows/ci.yml
crates/core/Cargo.toml
crates/core/src/db/commit_log.rs
crates/core/src/db/datastore/locking_tx_datastore/committed_state.rs
crates/core/src/db/datastore/locking_tx_datastore/mod.rs
crates/core/src/db/datastore/locking_tx_datastore/mut_tx.rs
crates/core/src/db/datastore/locking_tx_datastore/state_view.rs
crates/core/src/db/relational_db.rs
crates/core/src/host/wasmtime/wasm_instance_env.rs
crates/core/src/subscription/subscription.rs

Closes #748.
This patch adds a temporary feature flag for enabling table metrics.
Table metrics are potentially recorded many times within a transaction. This recording is synchronous and therefore can have a noticable impact on latency.
This new flag will be enabled by default.
With it, table metrics will be recorded; without it, they won't.
Note this flag is temporary.
It will be removed once metrics are recorded async.
*This complexity rating applies not only to the complexity …

feat(748): Add compile time feature flag for table metrics

---

crates/cli/src/subcommands/server.rs

solves: https://github.com/clockworklabs/SpacetimeDB/issues/310
No. CLI change.
1

Handle returned status codes instead of Rust values

---

crates/core/src/subscription/subscription.rs

A call site for record_query_duration_metrics was missed in #749.

fix: Put query metrics behind feature flag

---

crates/primitives/src/attr.rs
crates/sats/src/db/auth.rs
crates/sats/src/relation.rs
crates/vm/src/expr.rs

feat(query): Make current plan type hashable

---

crates/table/src/bflatn_from.rs
crates/table/src/layout.rs
crates/table/src/lib.rs
crates/table/src/read_column.rs
crates/table/src/row_hash.rs
crates/table/src/table.rs

This commit defines `trait ReadColumn`, which is implemented for types that can be stored in a table column and can be read out of said table column.
Its interesting method is `read_column(row: RowRef<'_>, idx: usize) -> Result<Self, TypeError>`, which attempts to read the `idx`th column of `row` as a value of type `Self`, returning a `TypeError` if the row in question does not have the appropriate types.
`ReadColumn` is implemented for Rust equivalents of all non-compound `AlgebraicType`s, i.e. integers, floats, `bool` and `String`. It is also implemented for all SATS value types, including those which represent values of compound types, i.e. `AlgebraicValue`, `ProductValue`, `SumValue`, `ArrayValue` and `MapValue`.
Note that this commit does not use the `ReadColumn` interface anywhere, …

`trait ReadColumn`, to read a single column from a `RowRef`

---

crates/core/src/db/datastore/locking_tx_datastore/committed_state.rs
crates/core/src/db/datastore/locking_tx_datastore/mut_tx.rs
crates/primitives/src/col_list.rs
crates/table/src/btree_index.rs
crates/table/src/table.rs

Rewrite of Tyler's #771, because I thought this would be easier than rebasing.
This commit hoists branching on key types outside of comparisons and searches in `BTreeIndex`, so that in many cases we can use e.g. `u64::cmp` instead of the much slower `AlgebraicValue::cmp`.
This design is kind of ugly, and will likely change in the future, but for now it's good enough, and is a meaningful performance improvement.
No external interfaces change.
2 - ugly code with lots of repetitive matching may open us up to copy/paste errors.

BTreeIndex: Specialize on primitive key types for great performance

---

crates/core/src/db/datastore/locking_tx_datastore/mod.rs

Exposes `MutTxId` more than crate-local, which was causing SpacetimeDBPrivate to fail.
This is an unbreaking change :upside_down_face: 

Fix private not building with latest master

---

crates/core/src/db/datastore/locking_tx_datastore/committed_state.rs
crates/core/src/db/datastore/locking_tx_datastore/mut_tx.rs
crates/primitives/src/col_list.rs
crates/table/src/btree_index.rs
crates/table/src/read_column.rs
crates/table/src/table.rs

Prior to this commit, `BTreeIndex::insert` and `BTreeIndex::delete` took a `&ProductValue`, the row to be inserted or deleted, as an argument, and extracted the indexed column value(s) from it.
With this commit, we instead take a `RowRef` referring to the row to be inserted or deleted, and access the indexed column value(s) using `ReadColumn`. For specialized indexes, we extract them directly as native types, rather than as `AlgebraicValue`.
Making this change involved a nasty split borrow problem, as we now need to have a `RowRef` to the inserted/deleted row coexisting with a mutable borrow of the index to be modified. This required introducing a `TableInner` struct,
which is the referent of `RowRef`.
No external interfaces broken.
2 - minimal `unsafe`, semantics of `Table`, `RowRef` and …

BTreeIndex: use `ReadColumn` instead of `ProductValue` fields

---

crates/core/src/sql/execute.rs
crates/core/src/subscription/module_subscription_actor.rs
crates/core/src/subscription/query.rs
crates/core/src/subscription/subscription.rs
crates/core/src/vm.rs

Simple change to remove an unnecessary mut reference and therefore simplify how the tx for broadcast_commit_event gets created.

Simplify broadcast_commit_event

---

crates/client-api/src/routes/subscribe.rs
crates/core/src/client/client_connection.rs
crates/core/src/client/message_handlers.rs
crates/core/src/host/module_host.rs
crates/core/src/host/wasm_common/module_host_actor.rs
crates/core/src/subscription/module_subscription_actor.rs
crates/core/src/subscription/subscription.rs

Fixes that issue. From a comment I added in module_subscription_actor:
> Take a lock on our subscriptions [before we commit the tx]. Otherwise, we could have a race condition where we commit the tx, someone adds a subscription and receives this tx as an update, and then receives the update again when we broadcast_event.
2

Add a RwLock around module subscriptions to prevent a race condition

---

crates/vm/src/eval.rs

For a table scan of 1M rows, this clone was over 30% of the total execution time.

perf(query): Moves Code::Block instead of cloning during eval

---

crates/core/src/subscription/module_subscription_actor.rs
crates/core/src/worker_metrics/mod.rs

perf(subscriptions): Add metric counter for subscribe calls

---

crates/core/src/host/instance_env.rs
crates/core/src/host/wasm_common/module_host_actor.rs
crates/core/src/host/wasmtime/wasmtime_module.rs
crates/core/src/util/mod.rs

This was one of the main reasons I was excited for 1.76 and I forgot lol.

ResultInspectExt is obsolete

---

modules/benchmarks/src/lib.rs

Fix benchmarks

---

crates/core/src/db/datastore/locking_tx_datastore/state_view.rs

Prior to this commit, `ScanIterByColRange::next` called `RowRef::to_product_value` and then `ProductValue::project_not_empty` on every row in the table to get a key, which it compared to the sought range. This always allocated at least a `ProductValue`, even when seeking a range of primitive type like `u64`. It also unnecessarily deserialized (and potentially allocated) columns not relevant to the search for rows which did not match the range.
With this commit, we call `RowRef::project_not_empty` directly. When the sought range is a single column, this avoids allocating a `ProductValue`. Even when seeking a multi-column range, this avoids deserializing unrelated columns of non-matching rows.
Non-indexed `IterByColEq` is always going to be slow, so this probably doesn't matter, but it's a …

`ScanIterByColRange`: Avoid unnecessary `ProductValue` allocations

---

Cargo.lock
tools/upgrade-version/Cargo.toml
tools/upgrade-version/src/main.rs

Fixing after #802. Please let me know if there's anything you'd like me to change about this; I didn't wanna try extending the custom toml parsing going on so I just pulled in `toml_edit`; it does the right thing and the code is clearer. (also made `process_license_file` use regex replace_all, cause while testing the file renaming was failing for me. lemme know if I should revert that). I also, instead of doing the walkdir for `Cargo._toml`, just specify `crates/cli/src/subcommands/project/rust/Cargo._toml`, since that's gonna be the only ever one afaik.

Update upgrade-version tool

---

crates/core/src/db/datastore/locking_tx_datastore/committed_state.rs
crates/core/src/db/datastore/locking_tx_datastore/state_view.rs
crates/core/src/vm.rs
crates/vm/src/iterators.rs
crates/vm/src/rel_ops.rs

Closes #836.
The tracing library does not fully remove all instrumentation at compile time. And since tracing is not zero cost,
it must be removed from the hot path of query execution.

chore(836): Remove tracing instrumentation from database iterators

---

crates/core/src/client/client_connection.rs
crates/core/src/host/module_host.rs
crates/core/src/host/wasm_common/module_host_actor.rs
crates/core/src/subscription/module_subscription_actor.rs

Moves RwLock from `SubscriptionManager` to its specific field `subscriptions` so that most of the heavy lifting part i.e `eval` of `add_susbcription` can be done concurrently.
3, It has potential to introduce concurrency bugs.

To make eval subscription concurrent

---

crates/cli/src/subcommands/project/rust/pre-publish.duck

Just removing the long-unused `pre-publish.duck` file.
Nope
1

Remove unused pre-publish.duck file

---

crates/cli/src/subcommands/project/rust/pre-publish.duck
crates/cli/src/tasks/rust.rs

Allow users to run `spacetime publish` even if `rustup` is not present on their system. Typically we use it to install the `wasm32-unknown-unknown` target.
Addresses https://github.com/clockworklabs/SpacetimeDB/issues/799
These are CLI-only changes that don't affect our ABI.
1

Fix: Publish fails if rustup not present

---

crates/core/Cargo.toml

I seem to be unable to build `core` directly on master, though building the workspace root, i.e. `cli`, works. This is caused by `core` depending on `spacetimedb-lib.workspace`, which has `default-features = false`, excluding serde support.
This commit correctly specifies the `"serde"` feature for core's dependency on lib, so it is now possible to `cd crates/core && cargo check`.
N/a
1
and what other components it interacts with …

Core: depend on "serde" from lib

---

tools/merge-docker-images.sh

When building a release for a tag we have to build a multi arch image ourselves. So far we tagged it with a tag `<short-sha>-full`. This is nice to keep the history of all the tagged commits, but it's not very usable as usually we just want the latest build for a given tag. This commit introduces tagging the build with a git tag
Very low, only a CI change

Use a version label for tag builds

---

crates/bindings-macro/src/lib.rs
crates/bindings/src/lib.rs
modules/rust-wasm-test/src/lib.rs

- Refactor `bindings::query::delete_by_field` to require `FilterableValue` and return `u32` count of deleted rows.
- Add `bindings::query::delete_by_unique_field` with the previous behavior of `delete_by_field`, i.e. requiring `UniqueValue` and returning `bool` with `true = deleted`. This is implemented in terms of `delete_by_field`.
- Macro-generated unique filter funcs call `delete_by_unique_field` rather than `delete_by_field`.
- The table macro now generates non-unique delete functions alongside the existing non-unique filter functions for non-unique fields with primitive types.
- Add uses of `::delete_by_{field}` for both unique and non-unique columns to the `rust-wasm-test` module, so we can see that they compile as expected.
Note that this PR does not include any host-side changes; …

Add `delete_by_{nonunique_column}` method to `#[spacetimedb(table)]`

---

.github/workflows/ci.yml
crates/table/benches/page.rs
crates/table/benches/page_manager.rs
crates/table/benches/var_len_visitor.rs

This doesn't affect much in practice, but rust-analyzer checks all crate targets by default and it's annoying to see errors in the status bar from something unrelated to what I'm working on.
1

Fix bench errors and include in CI

---

crates/core/src/db/relational_db.rs
crates/sats/src/bsatn.rs
crates/sats/src/hash.rs

```
cargo bench --bench=subscription --profile=profiling -- full-scan --exact
full-scan               time:   [418.07 ms 418.83 ms 419.62 ms]
change: [-8.7500% -8.2453% -7.7598%] (p = 0.00 < 0.05)
Performance has improved.
```

chore: Remove instrumentation from DataKey deserializers

---

.github/workflows/check-merge-labels.yml

Added a GitHub workflow to check for PRs with a `Do not merge` label, for ad-hoc PR blocking.
**Note:** A repo admin must [make this](https://github.com/clockworklabs/SpacetimeDB/settings/branches) a merge-blocking check!
No runtime changes.
1

Add GitHub workflow to check for PRs with merge-blocking labels

---

tools/perf.sh

Add a script to the tools directory, `perf.sh`, for running `perf`.
1

Script to run perf against SpacetimeDB

---

crates/client-api/src/routes/subscribe.rs
crates/core/src/client/client_connection.rs
crates/core/src/client/message_handlers.rs
crates/core/src/db/db_metrics/mod.rs
crates/core/src/worker_metrics/mod.rs
crates/testing/src/modules.rs

Adds a new metric to measure end to end time of reducer, subscription and one_off_query call.
based on ticket https://github.com/orgs/clockworklabs/projects/22/views/21?pane=issue&itemId=53199356

Metric for request RTT

---

crates/core/src/client/client_connection.rs
crates/core/src/host/host_controller.rs
crates/core/src/host/module_host.rs
crates/core/src/subscription/module_subscription_actor.rs

Reverts clockworklabs/SpacetimeDB#888 due to a deadlocking issue with multiple clients connected.

Revert "Run initial subscriptions evals on rayon"

---

crates/vm/src/expr.rs

Closes #890.
This changes the magic constant from 1000 to 3000 rows,
which means if the indexed table in an index join has 3000 rows or less,
we make it the probe table instead.

refactor(890): Improve magic constant for index join selection

---

crates/core/src/client/messages.rs
crates/core/src/sql/compiler.rs
crates/core/src/sql/execute.rs
crates/core/src/subscription/query.rs
crates/core/src/subscription/subscription.rs
crates/core/src/vm.rs
crates/sats/src/db/def.rs
crates/sats/src/relation.rs
crates/vm/src/dsl.rs
crates/vm/src/eval.rs
crates/vm/src/expr.rs
crates/vm/src/iterators.rs
crates/vm/src/rel_ops.rs
crates/vm/src/relation.rs

Re: #834 . In the VM, wrap `Header` in `Arc` everywhere it's held by a relational operator, so we can `Arc::clone` instead of `Header::clone`.
In support of this change, remove the `Clone` impl on `Header`. For slow paths where cloning is acceptable, define a method `Header::clone_for_error`, which behaves the same as the derived `Clone` would, but better communicates intent.
N/a.
2 - Internal changes to the VM whose performance impacts must be verified, but no (intentional) semantic changes.
*If …

VM: Wrap `Header` in `Arc` to avoid cloning

---

crates/bench/benches/subscription.rs
crates/core/src/subscription/module_subscription_actor.rs
crates/core/src/subscription/query.rs
crates/core/src/subscription/subscription.rs

Closes #832.
The database already operates under set semantics, so unless multiple queries return rows from the same table, deduplication of the result set is not necessary.
```
> cargo bench --bench=subscription --profile=profiling -- full-scan --exact
full-scan               time:   [251.71 ms 251.99 ms 252.28 ms]
change: [-43.284% -43.172% -43.062%] (p = 0.00 < 0.05)
Performance has improved.
```

perf(832): Remove redundant row deduplication in subscriptions

---

.github/workflows/benchmarks.yml

The Yaml was misconfigured to still look for "callgrind please" comments, this fixes that. This is the last change needed to get the better benchmark reports in.
0

Adjust benchmarks yaml to run callgrind + with better comments

---

crates/core/src/host/host_controller.rs
crates/core/src/host/mod.rs
crates/standalone/src/lib.rs
test/tests/update-module.sh

Previously, `spawn_module_host` would unconditionally insert the new module into the controller state, and not remove it if the lifecycle hooks (`init_database` / `update_database`) returned an error.
This would mean that the module code was replaced with the new one, even if it should be rejected because the schema was not updated or the init / update reducer failed.
Fix this by starting the module, and later "committing" it to the controller state in two phases.

core: Fix host controller to not replace module if lifecyle hooks failed

---

Cargo.lock
crates/core/Cargo.toml
crates/core/src/client.rs
crates/core/src/host/module_host.rs
crates/core/src/host/wasm_common/module_host_actor.rs
crates/core/src/startup.rs
crates/core/src/subscription/execution_unit.rs
crates/core/src/subscription/mod.rs
crates/core/src/subscription/module_subscription_actor.rs
crates/core/src/subscription/module_subscription_manager.rs
crates/core/src/subscription/query.rs
crates/core/src/subscription/subscription.rs
crates/lib/src/identity.rs

Previously we would evaluate each and every subscription on each and every row update.
If N subscriptions had a query Q in common, Q would be evaluated N different times.
With this change, queries are evaluated once, and the results transmitted to each client.
So in the example above, Q would be evaluated once, with the results duplicated to N different clients.
Some things to note:
1. It's currently single threaded
In principle evaluating row updates should be very fast.
On the order of microseconds.
In that case parallelizing eval probably just adds overhead.
However if we didn't have to aggregate the different table updates before sending to the client, it might be beneficial.
2. It's evaluated on a rayon thread.
Again, if eval_incr is on the order of microseconds, is this just adding …

perf(747): Single query execution for multiple subscriptions 

---

Cargo.lock
Cargo.toml
crates/client-api/Cargo.toml
crates/client-api/src/routes/subscribe.rs

This batches messages onto the websocket instead of sending them one at a time. This might help latency with clients being paused for a long time, but I'm still unsure about the root cause of that issue so I wouldn't count much on it.
Supersedes #902
1

Use recv_many in ws_client_actor

---

crates/core/src/db/commit_log.rs
crates/core/src/db/message_log.rs
crates/core/src/db/relational_db.rs
crates/core/src/host/wasm_common/module_host_actor.rs
crates/core/src/host/wasmtime/wasm_instance_env.rs
crates/core/src/sql/ast.rs
crates/core/src/sql/compiler.rs
crates/core/src/sql/execute.rs
crates/core/src/subscription/query.rs
crates/core/src/vm.rs
crates/vm/src/eval.rs
crates/vm/src/program.rs

Removes most instrumentation from RelationalDB,
but keeps all pre-existing instrumentation of the wasm api.
None
1

chore: Remove debug instrumentation from hot path

---

crates/core/src/subscription/execution_unit.rs
crates/core/src/subscription/query.rs
crates/core/src/subscription/subscription.rs

As an optimization,
because we do not support strict projections in subscription queries, selections may always assume that the op_type field is last, when removing it.

perf: Make op_type special case fast for selections

---

crates/sdk/tests/test-counter/src/lib.rs

We're seeing intermittent failures of the SDK tests in CI due to timeouts. The timeout is meant only to fail if an expected event never happens; the SDK tests are not interested in measuring performance at all.
This commit doubles the timeout from 30 to 60 seconds, in the hopes that we will see fewer false failures.
N/a
1

Increase sdk tests' timeout to 60 seconds

---

Cargo.lock
Cargo.toml
crates/core/Cargo.toml
crates/core/src/db/update.rs

It turns out that the changes introduced in #734 do not result in more reliable detection of incompatible schema updates. This is because the datastructures involved can be converted into each other, but that conversion is not bijective.
Fix this by manually adjusting the schema of the existing table to be comparable to the proposed table.
Also log details about a schema mismatch to the user-retrievable database log, in unified diff format.
*This complexity rating applies not …

core: Fix schema checks in database updates, again

---

crates/core/Cargo.toml
crates/core/src/db/datastore/locking_tx_datastore/mut_tx.rs
crates/core/src/db/db_metrics/mod.rs

Adds a warning to `iter_by_col_range` when there is no applicable index and the table has >1000 rows. Should make it easier for us to debug BitCraft performance. This is an obviously suboptimal implementation which is intended as a stopgap until we can properly implement this warning.
- Warnings go to the host logs, not the module logs. This will clearly need to change before 1.0.
- Simply don't generate `filter_by_{col}` methods unless there's an index.
- This won't stop unindexed queries via the `query!` macro, but will catch the vast majority of cases.
- This will not allow unindexed filters on small tables.
- Generate the above methods, but mark them `#[deprecated]`.
- The point would not be to actually remove them, but because that's the only mechanism Rust exposes (AFAIK) for …

Log a warning when doing `iter_by_col_range` without an index

---

crates/bench/src/spacetime_raw.rs
crates/core/src/db/cursor.rs
crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
crates/core/src/db/datastore/locking_tx_datastore/mut_tx.rs
crates/core/src/db/datastore/locking_tx_datastore/state_view.rs
crates/core/src/db/datastore/system_tables.rs
crates/core/src/host/instance_env.rs
crates/core/src/sql/compiler.rs
crates/core/src/subscription/execution_unit.rs
crates/core/src/subscription/subscription.rs
crates/core/src/vm.rs
crates/sats/src/relation.rs
crates/vm/src/eval.rs
crates/vm/src/expr.rs
crates/vm/src/program.rs
crates/vm/src/rel_ops.rs
crates/vm/src/relation.rs

Fixes #833 
Perf numbers on my machine:
```
Benchmarking incr-join: Collecting 100 samples in estimated 5.01
incr-join               time:   [5.0575 µs 5.0914 µs 5.1521 µs]
change: [-19.535% -18.714% -17.870%] (p = 0.00 < 0.05)
Performance has improved.
Benchmarking query-indexes-multi: Collecting 100 samples in esti
query-indexes-multi     time:   [1.0330 µs 1.0387 µs 1.0457 µs]
change: [-13.574% -12.820% -12.213%] (p = 0.00 < 0.05)
Performance has improved.
```
None
1
No changes semantically; should be covered by existing tests.

perf(833): Do not clone query plan during execution

---

crates/bench/benches/subscription.rs
crates/core/src/client/messages.rs
crates/core/src/host/module_host.rs
crates/core/src/subscription/execution_unit.rs
crates/core/src/subscription/module_subscription_actor.rs
crates/core/src/subscription/query.rs
crates/core/src/subscription/subscription.rs

- Fixes https://github.com/clockworklabs/SpacetimeDB/issues/813.
```
Benchmarking full-scan: Collecting 100 samples in estimated 
full-scan               time:   [162.84 ms 164.37 ms 166.88 ms]
change: [-47.765% -47.089% -46.260%] (p = 0.00 < 0.05)
Performance has improved.
Benchmarking query-indexes-multi: Collecting 100 samples in 
query-indexes-multi     time:   [1.1162 µs 1.1202 µs 1.1274 µs]
change: [-6.4601% -5.3782% -4.0002%] (p = 0.00 < 0.05)
Performance has improved.
```
None
2

perf(813): Avoid materialization of product values in subscriptions

---

crates/core/src/client/client_connection.rs
crates/core/src/client/message_handlers.rs
crates/core/src/client/messages.rs
crates/core/src/host/module_host.rs
crates/core/src/subscription/module_subscription_actor.rs
crates/core/src/subscription/module_subscription_manager.rs

"Cache" the BSATN serialization in incremental updates for subscribers using the same query.
Unfortunately, we have to deal with JSON as a possibility because of the website, so we have to thread through a bunch of `Either`s.
None
2

perf(933): Clone bsatn instead of product values in incremental update

---

crates/core/src/db/relational_db.rs
crates/core/src/host/instance_env.rs
crates/core/src/vm.rs
crates/sqltest/src/db.rs

There were two bugs that prevented us from using multi-col indexes in `query!`.
None of these were in `find_sargable`, rather, they were in:
1. `InstanceEnv::iter_filtered_chunks`: it didn't call `q.optimize(...)` (so we may potentially see other improvements now).
2. `Header::column` would not find the `Column` due to `FieldName::Pos` being passed.
I've verified that the query ends up being optimized to a `Query::IndexScan` and that this actually reaches the index with the right name in `BTreeIndex::seek`.
None
2 - There are other users of `Header::column_pos_idx`.

fix: Optimize query plan in iter_filtered_chunks

---

crates/core/src/client/client_connection.rs
crates/core/src/subscription/module_subscription_actor.rs

If a subscription drops its read lock on the database too early, that is before it sends its updates to the client, this test will fail.
*Describe any testing you've done, and any testing you'd …

test: Subscriptions should not drop read lock early

---

crates/client-api/src/routes/subscribe.rs
crates/core/src/client/client_connection.rs
crates/core/src/client/message_handlers.rs
crates/core/src/client/messages.rs
crates/core/src/subscription/module_subscription_actor.rs
crates/core/src/subscription/module_subscription_manager.rs

Closes #1024.
Before this change,
we would serialize messages **before** inserting into the send queue.
Because we commit the tx only after inserting into the send queue, this meant we were holding onto the database lock unnecessarily.
After this change,
we serialize messages **after** inserting into the send queue. This means we serialize only after committing the tx.
but also to its interactions …

perf(1024): Remove serialization from tx execution thread

---

crates/core/src/db/commit_log.rs
crates/core/src/db/datastore/locking_tx_datastore/committed_state.rs
crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
crates/core/src/db/datastore/locking_tx_datastore/mut_tx.rs
crates/core/src/db/datastore/traits.rs

Fixed an issue which caused metrics to only be recorded for on-disk databases.
Note to reviewer: I'm not sure that it makes sense to pass the ExecutionContext so deep, but this works.
None
2

Fixed an issue which caused metrics to only be recorded for on-disk databases

---

Cargo.lock
Cargo.toml
crates/core/Cargo.toml
crates/core/src/client/messages.rs
crates/sdk/Cargo.toml
crates/sdk/src/websocket.rs

Simpler solution to #1022 , compared to #1021 or #1023 .
With this commit, all outgoing messages using the binary protocol (i.e. Protobuf) are Brotli-compressed at level 1 (fastest, least compression).
Unsure which breakage label is correct. Breaks the binary WebSocket API, and so will require changes to:
- https://github.com/clockworklabs/spacetimedb-typescript-sdk/pull/41 .
- https://github.com/clockworklabs/spacetimedb-typescript-sdk/pull/42 .
3 - breaking the WebSocket API is scary.
*This complexity rating applies not only to the complexity …

Binary WebSocket API: Brotli-compress all outgoing messages

---

Cargo.lock
Cargo.toml
crates/commitlog/Cargo.toml
crates/commitlog/LICENSE
crates/commitlog/src/commit.rs
crates/commitlog/src/commitlog.rs
crates/commitlog/src/error.rs
crates/commitlog/src/lib.rs
crates/commitlog/src/payload.rs
crates/commitlog/src/repo/mem.rs
crates/commitlog/src/repo/mod.rs
crates/commitlog/src/segment.rs
crates/commitlog/src/tests.rs
crates/commitlog/src/tests/bitflip.rs
crates/commitlog/src/tests/helpers.rs
crates/commitlog/src/tests/partial.rs

First in a series of patches to implement the new commitlog format.
This patch implements the base format, leaving the transaction payload generic. Segment handling, writing and reading is implemented based on an in-memory backend, which greatly simplifies testing.
As a notable deviation from the previous implementation, segments are never implicitly trimmed. Instead, faulty commits are ignored if and only if the next commit in the log sequence is valid and has the right offset. On the write path, this entails closing the active segment when an (I/O) error occurs, but retaining the commit in memory such that it is written to the next segment.
Note that this patch does not define the final public API.
5

(1/3) Commitlog: Base implementation "sans I/O"

---

Cargo.lock
crates/commitlog/Cargo.toml
crates/commitlog/src/commitlog.rs
crates/commitlog/src/error.rs
crates/commitlog/src/lib.rs
crates/commitlog/src/repo/fs.rs
crates/commitlog/src/repo/mod.rs
crates/commitlog/tests/io.rs
crates/commitlog/tests/random_payload/mod.rs

Provides a commitlog backing store based on files, and defines the exported `Commitlog` type which fixes the store to the file-based one.
**NOTE: This PR is stacked on top of #919**
1

(2/3) Commitlog: Add I/O based on regular files

---

Cargo.lock
Cargo.toml
crates/bindings-macro/src/lib.rs
crates/bindings/Cargo.toml
crates/bindings/src/rt.rs
crates/core/Cargo.toml
crates/lib/Cargo.toml
crates/lib/src/address.rs
crates/lib/src/identity.rs
crates/sats/Cargo.toml
crates/sats/src/hash.rs
crates/sdk/Cargo.toml
modules/rust-wasm-test/Cargo.toml
modules/rust-wasm-test/src/lib.rs

I noticed that somehow `protobuf` got into the transitive dependencies of `spacetimedb-bindings`. This brings the dependency count from 99 back to a respectable 56.
This makes modules compile quicker, which is good for our CI as well as first impressions of SpacetimeDB as a product. Speaking for myself, I know that I do often judge crates on dependency bloat, and I think 56 transitive dependencies is much more reasonable for a bindings crate than 99 (esp. when a lot of those had no need to be in there).
1

Prune deps from bindings dependency tree

---

Cargo.lock
Cargo.toml

Now we're fully onto hyper 1.0 in our deps tree!
1

Bump to reqwest 0.12 (uses hyper 1.0)

---

crates/cli/src/subcommands/call.rs
crates/cli/src/subcommands/describe.rs
crates/cli/src/subcommands/publish.rs
crates/cli/src/subcommands/sql.rs

Prior to this commit, some subcommands used `--as-identity` as the long, some of them used `-I` as the short, and there was no clear pattern.
With this commit, we just use `--identity` as the long everywhere, and `-i` as the short.
Breaking change to CLI arg parsing.
2 - I may have missed an arg, or some tool which depends on the previous arg format.

Consistently use `--identity` `-i` for identity args to CLI

---

Cargo.lock
crates/core/src/sql/execute.rs
crates/core/src/vm.rs
crates/vm/Cargo.toml
crates/vm/src/expr.rs
crates/vm/src/rel_ops.rs

This commit fixes a panic caused by unsatisfiable range bounds on an index query, e.g. `WHERE x < 5 AND x > 5`. These unsatisfiable bounds made Rust's `BTreeMap` angry (See https://doc.rust-lang.org/src/alloc/collections/btree/search.rs.html#106-124), and panicked. They also represent probable bugs, as it's silly to write a query which statically will return no rows.
With this commit, we detect statically unsatisfiable bounds in two cases:
- When compiling queries, we log a message at `WARN` containing the offending query.
- When evaluating queries, we silently construct an `EmptyRelOps` rather than a real query iterator.
This commit also adds a test that the offending queries can be compiled and executed without panicking, and select no rows.
N/a
If this is an API or ABI breaking change, …

Detect unsatisfiable range queries; warn and short-circuit.

---

crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
crates/core/src/db/relational_db.rs

I am now including the time it takes to commit the transaction in the in the transaction duration. Commitlog appending is still not measured but should be measured separately in the future.
2
None yet.

Metrics were not measuring the time it took to commit the tx

---

crates/core/src/db/db_metrics/mod.rs
crates/core/src/db/relational_db.rs
crates/core/src/host/wasmtime/wasm_instance_env.rs
crates/core/src/subscription/query.rs

This patch:
(1) Disables unused WasmInstanceEnv metrics,
(2) Removes unused query compilation metrics,
(3) Removes unused RelationalDB metrics
*Describe any testing you've done, and any testing …

fix: Disable unused metrics

---

crates/commitlog/src/lib.rs

Does what the title says.
N/a.
1
Completely untested.

Drop commitlog logging to `trace` to avoid spamming host logs

---

Cargo.lock
Cargo.toml
crates/commitlog/src/lib.rs
crates/commitlog/src/payload.rs
crates/durability/Cargo.toml
crates/durability/LICENSE
crates/durability/src/imp/local.rs
crates/durability/src/imp/mod.rs
crates/durability/src/lib.rs

Defines traits intended to abstract over the kind of persistence a
database utilizes. The only implementation is (host-)local durability in
terms of the new commitlog crate.
The trait definitions may not be considered stable yet, but are in their
tentative form needed for further integration of the new commitlog.
**NOTE: This PR is stacked on top of #921**

Durability: Traits and implementation in terms of commitlog

---

crates/table/src/bflatn_to_bsatn_fast_path.rs
crates/table/src/layout.rs
crates/table/src/row_type_visitor.rs

Partially implements #1006. I haven't ensured we're actually doing the relevant memcpy optimizations yet.
Is BFLATN public ABI yet? It will be once we have snapshots I suppose. 
So, a breaking change on the BFLATN ABI.
3
I want to run this under miri but haven't done so yet.

Swap the location of tags in the BFLATN encoding

---

crates/bench/benches/subscription.rs
crates/core/src/db/datastore/locking_tx_datastore/committed_state.rs
crates/core/src/db/datastore/locking_tx_datastore/mut_tx.rs
crates/core/src/db/datastore/traits.rs
crates/core/src/db/relational_db.rs
crates/core/src/host/module_host.rs
crates/core/src/host/wasm_common/module_host_actor.rs
crates/core/src/subscription/query.rs
crates/core/src/subscription/subscription.rs

`TxData` is the representation of a transaction after it was committed,
and is passed around for evaluation of subscription queries and sending
the result to clients.
With the new commitlog, it can be represented more compactly, such that
copies for writing to the log can be avoided.
~~Note that this patch stops short of refactoring `DatabaseUpdate`, which
is another representation of the same information as sent to clients.
This means that `ProductValue`s need to be cloned from `TxData`, just as
before.~~ ProductValues are now `Arc<[ProductValue]>`, eliminating expensive clones.
**NOTE: This PR is stacked on top of #926**

core: More compact TxData

---

crates/commitlog/src/payload/txdata.rs
crates/core/src/db/relational_db.rs

Fix a minor bug where completely empty transactions would still be
written to the commitlog. The bug is minor because, once we start
logging inputs, all transactions will be non-empty.
The check is done in relational DB rather than the durability crate,
because in principle empty transactions are permissible, and may be used
in the future (e.g. to confirm a certain offset).
1
modify rows (where previously it was present).

core: Don't persist empty transactions

---

crates/core/src/subscription/module_subscription_actor.rs
crates/core/src/subscription/module_subscription_manager.rs

Closes #1115.
Previously subscribers were only identified by their Identity. However the same Identity can be associated to different Addresses.
*Describe any testing you've done, and any testing …

fix(1115): Identify subscribers by Identity AND Address

---

crates/cli/src/util.rs

When a server key rotation is suspected, suggest to make the new identity the default.
This usually happens during development using an ephemeral instance. If one follows the instructions, the `default_identity` is not set for the existing server, which makes the CLI generate a fresh identity every time.
See also: #333
1
- Spin up an ephemeral stdb
- Try to do something using the CLI
- Observe that it complains about a rotated key 
- Run `spacetime identity new --no-email --server <the server>` (**without** `--default`)
- Try more things using the CLI
- Observe that a fresh identity is created every time
- Run `spacetime identity new …

cli: Suggest to make new identity the default for server

---

crates/core/src/util/mod.rs

Avoids an unnecessarity roundtrip through `Vec<u8>` in private#731.
0

core: AnyBytes from boxed slice

---

crates/cli/src/subcommands/server.rs

Previous command:
```
spacetime server fingerprint <server>
```
New command:
```
spacetime server fingerprint -s <server>
```
if no `-s <server>` is supplied, the default server will be fingerprinted.
Technically yes, just a CLI change
and what other components it …

Fix an inconsistency with spacetime server fingerprint

---

crates/bindings-csharp/Codegen/Type.cs
crates/bindings-csharp/Codegen/Utils.cs
crates/bindings-csharp/Runtime/AlgebraicType.cs
crates/bindings-csharp/Runtime/Filter.cs
crates/bindings-csharp/Runtime/Module.cs
crates/bindings-csharp/Runtime/RawBindings.cs
crates/bindings-csharp/Runtime/Runtime.cs

While looking through the large diffs while splitting out small PRs out of my refactor branch, I noticed that quite a lot of noise is from me working on a formatted code and using primary constructors while the one in master is not.
As such, I'm splitting out just those automated / non-functional changes into a separate PR to make subsequent functional diffs easier to read.
1
*If you answered more than a 2, …

NFC: format C# module SDK code

---

crates/cli/src/subcommands/generate/csharp.rs
crates/cli/src/subcommands/generate/mod.rs
crates/cli/src/subcommands/generate/python.rs
crates/cli/src/subcommands/generate/rust.rs
crates/cli/src/subcommands/generate/typescript.rs
crates/sats/src/relation.rs

CLI `generate` code is a particularly heavy user of format-based macros, and so it benefits most from inlining format args where possible.
This is done by adding `#![warn(clippy::uninlined_format_args)]` + running `cargo clippy --fix` followed by `cargo fmt`, so shouldn't require manual review.
This is a follow-up to #1142 and, like that PR, is mainly done to make generate's code a bit cleaner and diffs simpler.
*This complexity rating applies not only to the complexity apparent …

NFC: inline format args in `generate` code

---

crates/cli/src/subcommands/init.rs

* doc: Link directly to cargo install on missing
Most modern terminals parse links for you -- let's skip redundant research for the user.

Dylan/doc: Link directly to cargo install on missing

---

crates/bindings-csharp/Codegen/Type.cs

Const members shouldn't count as table or type fields in `[SpacetimeDB.Type]`.
1

Ignore const members in C# types

---

crates/core/src/host/module_host.rs
crates/core/src/host/wasm_common/module_host_actor.rs
crates/lib/src/lib.rs
smoketests/tests/permissions.py

Disallow calling random lifecycle reducers

---

crates/core/src/db/db_metrics/mod.rs
crates/core/src/db/relational_db.rs
crates/core/src/host/wasm_common/module_host_actor.rs
crates/core/src/host/wasmtime/wasm_instance_env.rs
crates/core/src/worker_metrics/mod.rs

chore: Remove unused server metrics

---

crates/core/src/host/module_host.rs
crates/core/src/util/lending_pool.rs
crates/core/src/worker_metrics/mod.rs

Fixes #1170.
Also updates the bucket values for the queue length histogram. Also removes the max queue length metric, since the histogram should suffice.
*Describe any testing you've done, and …

fix(1170): Use scope guard to decrement reducer queue length

---

crates/core/src/host/module_host.rs
crates/core/src/host/scheduler.rs
crates/core/src/worker_metrics/mod.rs
crates/standalone/src/lib.rs

Fixes #1173.
Previously we were only recording this metric for scheduled reducers. We were also recording it before we acquired access to the module instance. Now we record it for all reducers after we acquire access to the module instance.
This patch also removes max wait time since the histogram should suffice.
*If you answered more than …

fix(1173): Record wait time for all reducers

---

.github/workflows/check-merge-labels.yml
.github/workflows/check-pr-base.yml

CI change - block PRs from merging if not based on `master`
No
In a test repo:
- https://github.com/clockworklabs/SpacetimeDB/pull/1184
- https://github.com/clockworklabs/SpacetimeDB/pull/1185

Add PR status check that fails unless based on `master`

---

Cargo.lock
Cargo.toml
crates/table/benches/page.rs
crates/table/benches/page_manager.rs
crates/table/benches/var_len_visitor.rs
crates/table/src/bflatn_from.rs
crates/table/src/bflatn_to.rs
crates/table/src/bflatn_to_bsatn_fast_path.rs
crates/table/src/eq.rs
crates/table/src/eq_to_pv.rs
crates/table/src/fixed_bit_set.rs
crates/table/src/indexes.rs
crates/table/src/page.rs
crates/table/src/read_column.rs
crates/table/src/row_hash.rs
crates/table/src/row_type_visitor.rs
crates/table/src/util.rs
crates/table/src/var_len.rs

Per discussion on the snapshotting proposal, this PR changes the type of `Page.row_data` to `[u8; _]`, where previously it was `[MaybeUninit<u8>; _]`.
This turns out to be shockingly easy, as our serialization codepaths never write padding bytes into a page. The only place pages ever became `poison` was the initial allocation; changing this to `alloc_zeroed` causes the `row_data` to always be valid at `[u8; _]`.
The majority of this diff is replacing `MaybeUninit`-specific operators with their initialized equivalents, and updating comments and documentation to reflect the new requirements.
This change also revealed a bug in the benchmarks introduced when we swapped the order of sum tags and payloads (#1063 ), where benchmarks used a hardcoded offset for the tag which had not been updated. …

Make `Page` always fully init

---

crates/bindings-csharp/Codegen/Module.cs
crates/bindings-csharp/Runtime/Module.cs
crates/bindings-csharp/Runtime/Runtime.cs
modules/sdk-test-connect-disconnect-cs/Lib.cs
modules/sdk-test-cs/Lib.cs

This is no longer an event type, so remove subclassing and rename to match the Rust API.
1

C#: rename DbEventArgs to ReducerContext

---

.github/workflows/benchmarks.yml
Cargo.toml
crates/core/src/host/wasmtime/wasm_instance_env.rs
crates/core/src/util/notify_once.rs
crates/data-structures/src/slim_slice.rs
crates/sdk/tests/test-client/src/pk_test_table.rs
crates/sdk/tests/test-client/src/simple_test_table.rs
crates/sdk/tests/test-client/src/unique_test_table.rs
crates/standalone/Dockerfile
crates/table/benches/page_manager.rs
crates/testing/src/sdk.rs
rust-toolchain.toml

1.78 brings `#[diagnostic::on_unimplemented]`, which lets you customize error messages when a type doesn't implement a trait. I have a branch that uses it to improve reducer & table type errors.
MSRV bump, but that's usually not a big deal. understandable if we wanna hold off on it for a bit.
1

Bump to Rust 1.78

---

crates/cli/src/subcommands/generate/csharp.rs
crates/cli/tests/snapshots/codegen__codegen_output.snap

We talked about this for a while, so decided to do this in a separate PR.
Users will need to subscribe to OnInsert / OnUpdate / OnDelete separately.
1
so that you're confident that all …

Remove RowUpdate event from C#

---

crates/bindings-csharp/Codegen/Module.cs
crates/bindings-csharp/Codegen/README.md
crates/bindings-csharp/Codegen/Type.cs
crates/bindings-csharp/Codegen/Utils.cs
crates/bindings-csharp/Runtime/AlgebraicType.cs
crates/bindings-csharp/Runtime/Attrs.cs
crates/bindings-csharp/Runtime/Filter.cs
crates/bindings-csharp/Runtime/Module.cs
crates/bindings-csharp/Runtime/Runtime.cs
modules/sdk-test-cs/Lib.cs

With C# records - which are available since C# 9, so covers Unity requirements as well - we can use subclassing and pattern matching to get sum types that look a lot more like Rust tagged enums than my previous approach.
For example, the following Rust code:
```rust
let foo = match some_tagged_value {
MyEnum::A(x) => ...,
MyEnum::B(y) => ...
};
```
can now be expressed via almost equivalent C# code
```cs
var foo = someTaggedValue switch {
MyEnum.A(var x) => ...,
MyEnum.B(var y) => ...,
// main difference is that, unlike in Rust, they're not exhaustive so you need to handle edge cases yourself
_ => throw new ArgumentException(...)
};
```
This is a breaking change but IMO worth it for the better API going forward.
corresponding …

Switch to a better API for tagged enums for C#

---

crates/commitlog/src/commitlog.rs
crates/commitlog/src/payload.rs
crates/commitlog/src/payload/txdata.rs
crates/core/src/db/datastore/locking_tx_datastore/datastore.rs

The documentation promised to not collect payload values during folds (i.e. replaying), but the code did so anyway. This patch makes it so only values required to satisfy the `Visitor` trait are allocated when folding.
1

commitlog: Allow folds to not allocate `Mutations` values

---

crates/commitlog/src/commitlog.rs
crates/commitlog/src/lib.rs
crates/commitlog/src/segment.rs
crates/durability/src/imp/local.rs

Does what it says in the title.
N/a.
1
Completely untested.

Drop various logs to `trace` for less noise

---

.github/workflows/check-pr-base.yml

#1180 added a GitHub status check for PRs; this check fails if a PR is based on any branch besides `master`.
It turns out that this check runs, and fails, on commits that are not part of a PR at all.
I believe this PR fixes that.
No runtime changes.
1
Not super satisfying, but the check currently passes on this PR :shrug:

Fix #1180: Add PR status check that fails unless based on master

---

crates/cli/src/config.rs
crates/cli/src/lib.rs
crates/cli/src/main.rs
crates/cli/src/subcommands/build.rs
crates/cli/src/subcommands/generate/mod.rs
crates/cli/src/subcommands/init.rs
crates/cli/src/subcommands/local.rs
crates/cli/src/subcommands/upgrade.rs
crates/cli/src/subcommands/version.rs
crates/testing/src/lib.rs

In the past, we've had issues where multiple concurrent CLI processes would race to read and write the CLI config file,
leading to data loss.
We considered using `flock`/`LockFileEx` and blocking until the file became available, but unfortunately it's not possible to atomically create and lock a nonexistent file, which we need to do in the case where the configuration doesn't yet exist.
Instead, we opt for a classic lockfile-based scheme: Before opening a config file `foo.conf`, attempt to exclusively create `foo.lock`, and panic if the exclusive creation fails. Once it becomes clear that we will not write the config any more, i.e. in `Config::drop`, delete the lockfile, allowing another process to operate.
This means that attempting to run multiple concurrent Spacetime CLI processes with …

Create a lockfile when opening config files

---

.github/CODEOWNERS

Adds a `CODEOWNERS` entry for `rust-toolchain.toml`.
This is to prevent surprise changes to the Rust version, which may have adverse downstream impacts.
No.
0

Add CODEOWNERS for `rust-toolchain.toml`

---

crates/bench/benches/subscription.rs
crates/core/src/subscription/module_subscription_actor.rs
crates/core/src/subscription/query.rs
crates/sdk/tests/test-client/src/main.rs
crates/sdk/tests/test.rs

We should really remove this.
Fixes #1199

Fix select * from *

---

crates/cli/src/config.rs
crates/cli/src/subcommands/identity.rs

Small refactors to some CLI code around identity management, to make review for https://github.com/clockworklabs/SpacetimeDB/pull/1140 easier.
These changes **do not change any behavior**.
- `Config.name_exists` now just uses `Config.get_identity_config_by_name`
- Added `Config.identity_exists` for parity (currently unused, used in https://github.com/clockworklabs/SpacetimeDB/pull/1140)
- Added `Config.can_set_name` (just used in one place, used more in https://github.com/clockworklabs/SpacetimeDB/pull/1140)
No
1

CLI - Small refactors to identity code

---

.github/CODEOWNERS

Adds a `CODEOWNERS` entry for all `LICENSE.txt` files.
This also makes sure that @cloutiertyler signs off on any **version bumps**, which update the root `LICENSE.txt`.
This means that @cloutiertyler is the signoff on every release.
No.
0

Add CODEOWNERS for `LICENSE.txt`

---

.github/CODEOWNERS

Make sure @cloutiertyler has to sign off on all changes to `CODEOWNERS` itself!
No
0

Add `CODEOWNERS` for `CODEOWNERS`

---

crates/cli/src/subcommands/publish.rs
smoketests/__init__.py
smoketests/tests/permissions.py

Making this change in response to a request from the BitCraft team.
`spacetime publish -c` now asks for confirmation, unless a new `--force` is passed as well.
This **will break** any automation using `spacetime publish -c`.
I think that's an acceptable level of break? @jdetter ?
2
```
Basic publish still works fine, with no input:
$ echo | spacetime …
```

`spacetime publish`: Add confirmation for `-c`

---

crates/core/src/client/client_connection.rs

Closes #1229.
And log warning when client channel capacity is exceeded.
so that you're confident that all the …

feat(1229): Double client channel capacity

---

crates/core/src/db/datastore/locking_tx_datastore/tx.rs
crates/core/src/db/relational_db.rs
crates/table/src/table.rs

Meta data field in `Table` struct for row count.
N/A
2

row_count field to table

---

crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
crates/core/src/db/datastore/locking_tx_datastore/mut_tx.rs
crates/core/src/db/relational_db.rs
crates/core/src/host/wasm_common/module_host_actor.rs
crates/core/src/subscription/module_subscription_actor.rs
crates/core/src/subscription/module_subscription_manager.rs

Also, move the logic with committing and taking the subscription lock into module_subscription_actor. Best reviewed ignoring whitespace.
before/after:

Atomically downgrade lock when committing tx to prevent deadlock

---

Cargo.lock
Cargo.toml
crates/table/Cargo.toml
crates/table/src/bflatn_to.rs
crates/table/src/fixed_bit_set.rs
crates/table/src/indexes.rs
crates/table/src/page.rs
crates/table/src/table.rs

Fixes https://github.com/clockworklabs/SpacetimeDB/issues/1244.
None
2
Tests are amended to cover clearing the hash and whatnot.

Add `PageHeader::unmodified_hash`, a BLAKE3 hash for snapshotting

---

crates/core/src/db/datastore/locking_tx_datastore/committed_state.rs
crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
crates/core/src/db/datastore/system_tables.rs
crates/core/src/vm.rs

Reserves an unreasonably large number of sequence values for use by system tables. This means that user-created tables will draw id values starting from the reserved range + 1, as opposed to number of values taken by system tables + 1.
Adding new system tables is thus unlikely to interfere with already-assigned values in existing databases.
Breaks existing databases due to id conflicts.
1
Should be covered by smoke tests.

Reserve sequence range for system tables

---

crates/bindings-macro/src/lib.rs
crates/bindings/src/impls.rs

Mostly already consistent with the proposal (#1256), except:
- Remove filtering functions for custom Hash type.
- Allow filtering over `i128` and `u128` fields.
- Allow filtering over `Address` fields.
Removing filtering over `Hash` in Rust modules.
1
so that you're …

Consistent filtering rules for Rust bindings

---

.github/workflows/ci.yml

Add `workflow_dispatch` event support to `ci.yml`.
This allows us to trigger workflow runs manually (see [benchmarks](https://github.com/clockworklabs/SpacetimeDB/actions/workflows/benchmarks.yml)).
No
2

CI workflows support `workflow_dispatch` event

---

crates/cli/src/subcommands/logs.rs

Fixes https://github.com/clockworklabs/SpacetimeDB/issues/1297.
No
1

fix(1297): `spacetime logs -f` should not start at the very beginning

---

crates/cli/src/config.rs

Previous error text:
```
thread 'main' panicked at crates/cli/src/config.rs:911:58:
called `Result::unwrap()` on an `Err` value: Unable to acquire lock on config file {config_path:?}: failed to create lockfile {path:?}
Caused by:
File exists (os error 17)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
New error message:
```
thread 'main' panicked at crates/cli/src/config.rs:911:58:
called `Result::unwrap()` on an `Err` value: Unable to acquire lock on config file "/home/lead/.spacetime/config.toml": failed to create lockfile "/home/lead/.spacetime/config.lock"
Caused by:
File exists (os error 17)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Nope
1
*Describe any testing you've done, and any testing you'd like your …

CLI - Fix `Lockfile` error message format strings

---

crates/cli/src/subcommands/logs.rs

Previously, if a user called `spacetime logs`, the `Config` lock would be held until the program closed.
In the case of `spacetime logs --follow`, this could be arbitrarily long, and would prevent the user from calling any other `spacetime` functions, e.g. `spacetime call`.
Also, using Ctrl-C to exit `spacetime logs -f` would cause the lockfile to stick around (not get dropped properly).
This PR drops the Config lock earlier, which fixes both issues.
Nope
1

CLI - Drop Config lock earlier for `spacetime logs`

---

crates/core/src/config.rs
crates/core/src/db/relational_db.rs
crates/core/src/estimation.rs
crates/core/src/subscription/execution_unit.rs
crates/core/src/subscription/module_subscription_actor.rs
crates/core/src/subscription/subscription.rs
crates/core/src/vm.rs

Closes #1231.
Queries that are estimated to exceed this row limit are rejected. And the same holds for subscriptions.
1
1. Issued `set row_limit = 5` from the SQL repl
2. Queried a table with > 5 rows using the owner identity (succeeded)
3. Queried a table with <= 5 rows using a different identity (succeeded)
4. Queried a table with > 5 rows using a different identity (failed)

feat(1231): Add a configurable row limit for queries

---

crates/bindings-csharp/Runtime/RawBindings.cs

The new `record struct` construct is the same as `struct`, but automatically derives equality and hashing by walking through the fields - exactly what we need for those 2 types.
*Describe any …

NFC: use record struct for auto-equality in C#

---

crates/cli/src/subcommands/generate/csharp.rs
crates/cli/tests/snapshots/codegen__codegen_csharp.snap

Fixes regression accidentally introduced in #1277: if FindBy returns null, FilterBy will return an iterable with a single null item instead of an empty iterable.
so that you're …

Fix FilterBy regression in C#

---

crates/bindings-csharp/Runtime/RawBindings.cs
crates/bindings-csharp/Runtime/build/SpacetimeDB.Runtime.props

Looks like these constants got missed during upgrade, making AOT version ABI-incompatible.
Unfortunately, there's no way to use a central constant here, and we don't have the Windows + Emscripten setup for testing the AOT variant yet, so we probably should add it to some "steps to do during ABI version bump" doc.
and what other components it …

Bump ABI version for C# AOT

---

crates/core/src/db/datastore/locking_tx_datastore/committed_state.rs
crates/core/src/db/datastore/locking_tx_datastore/mut_tx.rs
crates/core/src/db/db_metrics/mod.rs
crates/table/benches/page.rs
crates/table/src/bflatn_to.rs
crates/table/src/page.rs
crates/table/src/pages.rs
crates/table/src/table.rs

- Add metric `rdb_table_size` : The number of bytes in a table with a precision of page size
- Add `blob_store_bytes` in `Table` struct.
-  Inspired from `write/read` sys calls.  Make changes in few `insert`, `delete` Page relate apis to return number of blobs_byte written or deleted.
- Use `Number Of Pages * PAGE_DATASIZE` to calculate space occupying by table in pages for reporting to metrics.
1

metric for table size

---

crates/commitlog/src/commitlog.rs
crates/commitlog/src/payload.rs
crates/commitlog/src/payload/txdata.rs
crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
crates/core/src/db/relational_db.rs

Prior to this commit, `fold_transactions_from` on a durability backed by a commitlog would discard the requested offset and unconditionally yield all txes in the relevant segments.
This commit changes that behavior so that `fold_transactions_from` skips commitlog commits (which contain many txes) less than the reqested offset, and skips txes using `consume_record`.
N/a
3 - commitlog code is complicated. Is my test correct and sufficient? Did I correctly use `decode_record` and `consume_record`? Have I accidentally broken replay? Do I have an off-by-one error in my comparison operators?

Fix commitlog `fold_transactions_from` ignoring requested offset

---

Cargo.lock
Cargo.toml
crates/cli/Cargo.toml
crates/cli/src/config.rs
crates/fs-utils/Cargo.toml
crates/fs-utils/src/lib.rs
crates/fs-utils/src/lockfile.rs

The snapshot crate will need to create lockfiles. Rather than duplicating code to do so, we choose to move our definition of `Lockfile` into a crate that can be depended on by both `cli` and `snapshot`. No existing crate seems like an obvious choice for this -- a `Lockfile` is not really a data structure, so `data-structures` seems wrong -- so we add a new crate, `fs-utils`. Currently this contains only `Lockfile` and `create_parent_dir`, but a follow-up PR will add `DirTrie`, a Git-like on-disk object store.
N/a
1

Create new crate `fs-utils`; move `Lockfile` and `create_parent_dir`

---

crates/core/src/db/datastore/locking_tx_datastore/committed_state.rs
crates/core/src/db/datastore/traits.rs
crates/core/src/db/relational_db.rs

Prior to this commit, `CommittedState::next_tx_offset` got out of sync with the commitlog/durability's notion of the tx offset, because the former counted all committed TXes, while the latter excluded certain empty TXes (namely, empty TXes which were not `__identity_connected__` or `__identity_disconnected__` reducers).
With this commit, the skipping logic is moved earlier into `CommittedState`, so that it can maintain a counter consistent with that used by the commitlog.
N/a
2 - I may have inadvertently changed the logic of whether to skip a TX while moving it.
Nothing comes to mind as useful.

Make both TX offset counters agree

---

crates/commitlog/proptest-regressions/tests/bitflip.txt
crates/commitlog/src/tests/bitflip.rs

The test sometimes fails. As a proptest, we'll be able to seed it with failing inputs.
Fixes: #1167
1.8
0.8 for the proptest generator

commitlog: Make bitflip test a proptest

---

Cargo.lock
crates/fs-utils/Cargo.toml
crates/fs-utils/src/dir_trie.rs
crates/fs-utils/src/lib.rs

It's the git object store, but defined in our code, for 32-byte hashes! This will be used by snapshotting; each snapshot contains a `DirTrie` of its pages and large blobs.
N/a.
2 - new code, touches the FS. Not integrated anywhere yet, so it can't break anything, but future uses should be able to rely on the merged version being correct.

Define `DirTrie`, a git-like on-disk object store

---

Cargo.lock
Cargo.toml
crates/fs-utils/src/dir_trie.rs
crates/snapshot/Cargo.toml
crates/snapshot/src/lib.rs
crates/table/src/blob_store.rs
crates/table/src/page.rs
crates/table/src/pages.rs
crates/table/src/table.rs

- Requires making `BlobHash` be `Serialize` and `Deserialize`. For arcane macro-ology reasons, this requires writing `BlobHash::SIZE` instead of `Self::SIZE` (it gets embedded in a visitor struct or something).
- Requires adding two new operators to `BlobStore`.
- Adds a return value to `Page::save_content_hash`, for convenience.
- Impls `DerefMut` for `Pages`.
- ~~**Scary change:** adds `Table::pages_mut`. I think possibly this operator should be `unsafe`, since write access to the `Pages` allows an undisciplined caller to violate the `Table`'s assumptions by corrupting a `Page`. It seems like an anti-pattern to mark a method `unsafe` on the grounds that misusing its return value can cause UB, but I don't see a plausible alternative without making most methods on `Page` unsafe. Open to …

Add the `snapshot` crate, which implements snapshotting at a low level

---

Cargo.lock
crates/cli/src/config.rs
crates/cli/src/lib.rs
crates/cli/src/subcommands/build.rs
crates/cli/src/subcommands/generate/mod.rs
crates/cli/src/subcommands/init.rs
crates/cli/src/subcommands/local.rs
crates/cli/src/subcommands/logs.rs
crates/cli/src/subcommands/upgrade.rs
crates/cli/src/subcommands/version.rs
crates/fs-utils/Cargo.toml
crates/fs-utils/src/lib.rs
crates/fs-utils/src/lockfile.rs
crates/testing/src/lib.rs

Fixes https://github.com/clockworklabs/SpacetimeDB/issues/1339.
I updated `Config::save` to use an atomic write, so we no longer have the race condition that the `Lockfile` was originally created to address.
Correspondingly, I've removed `Config`'s usage of `Lockfile` entirely.
Nope
2

Fix bug with `Lockfile` sticking around

---

modules/quickstart-chat/src/lib.rs
modules/spacetimedb-quickstart/src/lib.rs

Update `quickstart-chat` and `spacetimedb-quickstart` to have public tables. They were previously public, but became implicitly private as of https://github.com/clockworklabs/SpacetimeDB/pull/1278.
I did not update other modules in this directory, e.g. `benchmarks`.
I sure hope not.
1
Just the CI

Update quickstart modules to have public tables

---

Cargo.lock
Cargo.toml
crates/bindings/Cargo.toml
crates/bindings/tests/deps.rs
crates/bindings/tests/snapshots/deps__duplicate_deps.snap
crates/bindings/tests/snapshots/deps__spacetimedb_bindings_dependencies.snap
crates/core/Cargo.toml
crates/lib/Cargo.toml
crates/lib/src/address.rs
crates/lib/src/identity.rs
crates/lib/src/lib.rs
crates/primitives/Cargo.toml
crates/primitives/src/ids.rs
crates/sats/Cargo.toml
crates/sats/src/hash.rs

I've added a snapshot test for the dependency tree of the `bindings` crate - that way, we'll know if we accidentally do something like pull in `rayon` (like we did). You can see the actual deps changes I did by looking at the diff of the second commit.
1

Prune bindings deps

---

.jenkins/Jenkinsfile.internal

Adds a Jenkinsfile which is used to kick-off internal automation.
For those who do not have experience with Jenkins, the new Jenkinsfile automatically performs the following functions:
1. Sets a Github Status Check to `Pending`
2. Starts internal automation within Jenkins
3. Waits for the internal automation to finish executing
4. Updates the Github Status Check with a `Success` or `Failure` message depending on the results.
n/a …

Add Jenkinsfile to run internal automation

---

crates/client-api/src/lib.rs
crates/client-api/src/routes/database.rs
crates/client-api/src/routes/identity.rs
crates/core/src/database_instance_context.rs
crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
crates/core/src/db/datastore/system_tables.rs
crates/core/src/db/datastore/traits.rs
crates/core/src/db/relational_db.rs
crates/core/src/db/update.rs
crates/core/src/host/disk_storage.rs
crates/core/src/host/host_controller.rs
crates/core/src/host/module_host.rs
crates/core/src/host/wasm_common/module_host_actor.rs
crates/core/src/messages/control_db.rs
crates/durability/src/lib.rs
crates/sats/src/hash.rs
crates/standalone/src/control_db.rs
crates/standalone/src/control_db/tests.rs
crates/standalone/src/energy_monitor.rs
crates/standalone/src/lib.rs
crates/testing/src/modules.rs
crates/testing/tests/standalone_integration_test.rs

This patch changes the `st_module` system table to store the compiled module directly in the database, where previously we would only store its hash. This allows to start up a database + module from just the commitlog, without requiring external storage (note: still required for initialization).
While we're changing `st_module`, we also store the database's address and owner identity, useful for snapshotting.
As a consequence, the `Database` struct stored in the control db becomes effectively immutable, as it only needs to refer to the **initial** (or: genesis) program. The number of replicas can be adjusted when publishing, or -- in the future -- through a `scale` command which doesn't require to provide a new program.
Collaterally, the long-standing TODO of threading through the module …

core: Store address, owner and program bytes in st_module

---

crates/bindings-csharp/Codegen/Module.cs
crates/bindings-csharp/Runtime/Attrs.cs
crates/bindings-csharp/Runtime/Module.cs
modules/sdk-test-connect-disconnect-cs/Lib.cs
modules/sdk-test-cs/Lib.cs
modules/spacetimedb-quickstart-cs/Lib.cs

After this change, tables must be marked with `Public = true` if they're meant to be exposed to clients.
Note that the syntax is different from Rust because attributes are not macros with arbitrary syntax, but must be actual expressions.
For now boolean should work well enough, but we might revisit specific attribute structure in the future - e.g. if Rust changes to separate `#[spacetimedb(table)] #[spacetimedb(public)]`, then it should be easy enough to change C# to use 2 attributes as well.
Fixes #1347.
where 1 is a trivial change, and 5 is a …

Add explicit parameter for table visibility

---

crates/durability/src/imp/local.rs

Make the local durability impl compare offsets and skip flush / fsync if
nothing changed.
1

durability: Skip fsync if nothing changed

---

crates/bindings-csharp/BSATN.Codegen/Utils.cs
crates/bindings-csharp/Codegen/Module.cs

Minor simplifications to type checks in Roslyn codegen.
1

[NFC] [C#] Minor simplifications to type checks in Roslyn codegen

---

crates/bindings-csharp/BSATN.Codegen/Type.cs
crates/bindings-csharp/BSATN.Codegen/Utils.cs
crates/bindings-csharp/Codegen/Module.cs

This fixes issues with nullability annotations (see the removed TODO), inconsistent field selection between `[SpacetimeDB.Type]` and `[SpacetimeDB.Table]`, as well as should be more efficient overall as it gets the type model for the structure in one go instead of individually for each field.
1
and what other components it interacts with in …

[C#] [NFC] Use semantic model's type where possible

---

crates/core/src/db/db_metrics/mod.rs
crates/core/src/worker_metrics/mod.rs

Closes #1409.
Grafana expects the names of counter metrics to end in _total.
1

fix(1409): Counter metric names

---

crates/core/src/subscription/module_subscription_actor.rs
crates/core/src/worker_metrics/mod.rs

We already track subscription requests through the rdb_num_txns counter.
1

chore: Remove already tracked subscription counter

---

crates/bindings-csharp/BSATN.Codegen/BSATN.Codegen.csproj

Previously BSATN.Codegen was ignored during the `nuget pack` command. During the release preparation of v0.10.0, it was discovered that this is required by the SDK. This includes the change to start building that csproj when we build and release nuget packages.
n/a
0 - Minimal Risk or Complexity. It is only a configuration change for nuget packages.
[x] This diff was used in the v0.10.0 release preparation and I was able to `nuget pack` and push this C# Project successfully.

Include BSATN.Codegen in nuget pack

---

crates/client-api/src/routes/subscribe.rs
crates/core/src/client/messages.rs
crates/core/src/host/module_host.rs
crates/core/src/worker_metrics/mod.rs

Closes #1351.
Also label row count and message size metrics by db address and workload.
1

perf(1351): Add a row count metric for subscriptions

---

crates/bindings-csharp/Runtime/Module.cs
crates/bindings-csharp/Runtime/Runtime.cs

Adds `Runtime.Random` property which contains an instance of `System.Random` that is reseeded by each reducer's timestamp.
The API is different from Rust implementation due to underlying differences between random APIs.
Fixes #1259.
1
*Describe any testing you've done, …

Implement the module rng proposal for C#

---

Cargo.lock
Cargo.toml
LICENSE.txt
crates/cli/src/subcommands/project/rust/Cargo._toml

We've [released v0.10.0](https://github.com/clockworklabs/SpacetimeDB/releases/tag/v0.10.0-beta), so any changes happening now must be in 0.10.1 (or higher).
None
1
None

Bump version to 0.10.1

---

crates/bindings-csharp/BSATN.Codegen/BSATN.Codegen.csproj
crates/bindings-csharp/BSATN.Runtime/BSATN.Runtime.csproj
crates/bindings-csharp/Codegen.Tests/Codegen.Tests.csproj
crates/bindings-csharp/Codegen/Codegen.csproj
crates/bindings-csharp/Directory.Build.props
crates/bindings-csharp/Runtime/Runtime.csproj
crates/cli/src/subcommands/project/csharp/StdbModule._csproj
smoketests/tests/csharp_module.py

Since the 0.10 release and before this change we had 5 NuGet packages that need to be pushed on each release:
- **SpacetimeDB.BSATN.Codegen**: Roslyn codegen for handling `[SpacetimeDB.Type]` attributes and generating [de]serialization code for marked types.
- **SpacetimeDB.BSATN.Runtime**: Runtime API for [de]serialization.
- **SpacetimeDB.Runtime**: Runtime APIs for interacting with SpacetimeDB host.
- **SpacetimeDB.Codegen**: Roslyn codegen for handling `[SpacetimeDB.Table]` and `[SpacetimeDB.Reducer]` attributes and generating module definitions, reducer schedulers and table APIs on marked types and method. It also automatically included **SpacetimeDB.BSATN.Codegen** to generate ser/de APIs as well.
- **SpacetimeDB.ClientSDK**: Client C# SDK.
C# users had to explicitly include:
- Both …

Restructure NuGet packaging

---

.github/workflows/ci.yml
smoketests/tests/zz_docker.py

(Re-)enables the `zz-docker` tests with some tweaking to increase the chances that a restart actually works.
Adds a smoketest which tests that clients are auto-disconnected after unclean shutdown.
Depends-on: #1343

Smoketest auto-disconnect after restart

---

crates/core/src/host/host_controller.rs

When updating a `Host`, replace its `Scheduler` with the new one.
This is only a minor fix: the `Host` only uses the `Scheduler` to create a
fresh `Scheduler` with the same underlying database, while the actual
scheduling happens elsewhere. By not dropping the old `Scheduler`, we'd
leak a channel with no receivers and a pointer to the database.
1

core: Replace host scheduler on update

---

crates/cli/src/config.rs
crates/cli/src/subcommands/identity.rs

We have help text in several places that suggests `spacetime server fingerprint $SERVER` without the `-s` parameter we added in https://github.com/clockworklabs/SpacetimeDB/pull/1131.
Nope. Just help text.
1
Nope. Just help text.

CLI - Update help text suggesting `spacetime server fingerprint` to have the correct `-s` param

---

crates/cli/src/subcommands/generate/csharp.rs
crates/cli/tests/snapshots/codegen__codegen_csharp.snap

Trivial
- Added two cases to code gen switch that parses args based on reducer name
- "__identity_disconnected__" - another client disconnects
- "" (empty string) - when calling UPDATE / DELETE from CLI
Complexity: 1/5
Risk: 1/5

Fixed exceptions in C# SDK when someone disconnects or when a transaction originates from CLI

---

.github/workflows/macos-build.yml

The `spacetime` binary in the MacOS build's tarball is not flagged as executable.
This makes it executable.
n/a
It only affects future release automation. I assume there is next to no risk.
Untested as this specific CI is only ran on `master`, `release` branches, and tags.

Ensure MacOS builds from CI are executable

---

crates/bindings-csharp/BSATN.Codegen/BSATN.Codegen.csproj
crates/bindings-csharp/BSATN.Runtime/BSATN.Runtime.csproj
crates/bindings-csharp/Codegen/Codegen.csproj
crates/bindings-csharp/Runtime/Runtime.csproj
crates/cli/src/subcommands/project/csharp/StdbModule._csproj
smoketests/tests/csharp_module.py

https://github.com/clockworklabs/SpacetimeDB/pull/1440 restructured our NuGet packages, and correspondingly updated the `.csproj` files we generate. However, since we haven't actually published the restructured NuGet packages, `.csproj`s expecting the _new_ NuGet package structure will be broken, including the smoketests.
It seems like this behavior was _sometimes_ causing smoketests to fail. It's unclear why it's only sometimes, but our best guess is "something something caching", so this PR forcibly clears the NuGet package cache.
Additionally, we bump the versions of the local NuGet packages to 0.11, so that they cannot be found on the NuGet servers. This means that the smoketests can _only_ find them in local directories, so they do not get confused about where to get these packages. …

Fix C# module smoketests

---

smoketests/tests/modules.py

The test establishes a subscription, updates the module (`clear=False`) and asserts that the subscription was not terminated and received an update made using the new module.
---
Depends-on: ~~#1343~~ #1367

smoketests: Add test for module hotswapping

---

crates/cli/src/common_args.rs
crates/cli/src/lib.rs
crates/cli/src/subcommands/call.rs
crates/cli/src/subcommands/delete.rs
crates/cli/src/subcommands/describe.rs
crates/cli/src/subcommands/dns.rs
crates/cli/src/subcommands/energy.rs
crates/cli/src/subcommands/identity.rs
crates/cli/src/subcommands/list.rs
crates/cli/src/subcommands/logs.rs
crates/cli/src/subcommands/publish.rs
crates/cli/src/subcommands/server.rs
crates/cli/src/subcommands/sql.rs
crates/cli/src/subcommands/subscribe.rs
crates/cli/src/subcommands/tracelog.rs

Created a `crates/cli/src/common_args.rs` file that currently just contains the most common form of the `--server`/`-s` param and the `--identity`/`-i` param.
None
1
- Confirmed:
```
$ spacetime energy set-balance --help
Update the current budget balance for a database
Usage: spacetime energy set-balance [OPTIONS] <balance> [identity]
Arguments:
<balance>
The balance value to set
[identity]
The identity to set a balance for. If no identity is provided, the default one will be used.
Options:
-s, --server <server>
The nickname, host name or URL of the server on which to update the identity's balance
-q, --quiet
Runs command in silent mode
-h, --help
Print help (see a summary with '-h')
```

CLI: Put some common params in a central place

---

.github/workflows/ci.yml

Added a CI step that checks out `spacetimedb-csharp-sdk` and runs its test suite.
In the current PR incarnation, if the local major/minor package versions are bumped, the C# SDK tests will continue to use the old ones. This is because the C# SDK repo will still have its version numbers pointed to e.g. `0.10.*` rather than e.g. `0.11.*`. Is this a bug or a feature?
I kind of think that the current behavior is correct - if we bump the major/minor version numbers, we're explicitly aware that we're releasing a breaking change. This effectively tests the experience of a current _user_ of the C# SDK (on `master`). In that case, we can make this a required check.
On the other hand, if we decide we want the C# SDK to _always_ use the local versions, then this should **not** be made a required …

CI - SpacetimeDB PRs run the C# SDK tests

---

.github/workflows/discord-posts.yml

The post-to-discord workflow was firing any time a PR merged, which included PRs merging to non-`master` branches. That's a bit noisy.
Nah
1
- https://github.com/clockworklabs/SpacetimeDB/pull/1521
- Workflow shows as correctly skipped: https://github.com/clockworklabs/SpacetimeDB/actions/runs/9961094449

CI - Post-to-discord workflow only fires if the PR merged to `master`

---

crates/client-api/src/routes/identity.rs

https://github.com/clockworklabs/SpacetimeDB/issues/1371
Swap out the previous 404 for a default response.
Changes the behavior in case of an empty email match, going from a client error to an empty success for its response.
0
```
λ curl localhost:3000/identity?email=me@example.com
{"identities":[]}
λ curl -I localhost:3000/identity
HTTP/1.1 400 Bad Request
```

Return empty success from /identity GET

---

crates/cli/src/subcommands/identity.rs
crates/client-api/src/routes/database.rs
crates/client-api/src/routes/identity.rs
crates/standalone/src/routes/mod.rs

https://github.com/clockworklabs/SpacetimeDB/issues/1372
Added `control_routes` to identity, based off database's.
Moved the recovery code APIs there.
Switched them to expect POST.
Changes both the request method and the router endpoints of the recovery code API.
0
```
curl -X POST "localhost:3000/identity/request_recovery_code?email=me@example.com&identity=1234567890123456789012345678901234567890123456789012345678901234"
curl -X POST "localhost:3000/identity/confirm_recovery_code?email=me@example.com&identity=1234567890123456789012345678901234567890123456789012345678901234&code=1"
```
Assuming the previous handler code is correct, this validates the routes and request method switches.

Moving recovery code APIs under /identity and using POST

---

crates/table/src/table.rs

Shuffle around checks in `Table::is_row_present` to avoid panicing on out-of-bounds index in `Table::page_and_offset`.
N/a.
1.

`Table::is_row_present`: don't panic

---

crates/core/src/db/update.rs

When checking for schema compatibility before an update, we erroneously considered sequence allocations to be an incompatible change. This means that any module which contained at least one sequence/`autoinc` column which had allocated more than 4096 values would be impossible to ever update.
With this change, we permit updates where the proposed sequence allocation is less than the known sequence allocation, and use the larger known sequence allocation as the value. This makes it possible to update modules which contain `autoinc` columns that have allocated more than 4096 values.
N/a.
1

Ignore some sequence allocation mismatches when checking for compatible updates

---

crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
crates/core/src/db/datastore/traits.rs
crates/core/src/db/relational_db.rs
crates/core/src/host/host_controller.rs
crates/core/src/host/wasm_common/module_host_actor.rs

Passing around the pair of (hash, bytes) in the host controller proved confusionary. Also, the `TxDatastore::program_bytes` method would in one instance require to compute the hash unnecessarily.
Thus, refactor to always load the hash and bytes together, and introduce a named pair `Program` containing both.
Depends-on: #1538 
Changes datastore traits.
1

core: Load program hash alongside bytes

---

crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
crates/core/src/db/datastore/traits.rs
crates/core/src/db/relational_db.rs
crates/core/src/host/host_controller.rs
crates/core/src/host/wasm_common/module_host_actor.rs

When updating a host, that host may not currently be running, in which case it is launched. However, it may (or may not) be initialized already. In either case, it is initialized before updating.
However, the host controller handled the not-running case without considering the auto-initialization -- that is, it took the module the host was launched with to perform the update, instead of the new module.
This meant that the schema was the same, so no actual update was performed.
This patch fixes this by handling both cases uniformly, which always instantiates a module from the supplied program bytes.
It also passes the correct program hash to `launch_module`, so as to fix the diagnostic output.
Depends-on: #1532

core: Fix module update

---

crates/cli/src/subcommands/generate/mod.rs

https://github.com/clockworklabs/SpacetimeDB/pull/1077 made it required to provide either the `--project-path` or `--wasm-file` arg.
This PR reverts that, so that if none of those arguments are provided, we use the default of `--project-path .`
An "un-breaking" change
1
```
$ cargo run -- generate --project-path . --wasm-file . --json-module .
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.22s
Running `target/debug/spacetime generate --project-path . --wasm-file . --json-module .`
error: the argument '--project-path <project_path>' cannot be used with:
--wasm-file <wasm_file>
--json-module [<json_module>]
Usage: spacetime generate --lang <LANG> --out-dir <DIR> [--project-path <DIR> | --wasm-file <PATH>]
For more information, try '--help'.
```
```
$ cargo run -- generate …
```

`spacetime generate` - make the source args optional

---

crates/bindings-csharp/BSATN.Codegen/Type.cs
crates/bindings-csharp/BSATN.Codegen/Utils.cs
crates/bindings-csharp/Codegen.Tests/Sample.cs
crates/bindings-csharp/Codegen/Module.cs

Some of the recent changes broke BitCraft which relies on being able to add extra fields to structures marked with `[SpacetimeDB.Type]`.
It wants those fields to be available in runtime, but ignored for BSATN and table purposes, which is a usecase I didn't consider in the past so it caused a few issues here and there. This one in particular is a regression from #1401.
1
*If you answered more than a 2, explain …

C#: ignore fields in partial declaration not marked with BSATN attribute

---

crates/cli/src/subcommands/generate/csharp.rs
crates/cli/tests/snapshots/codegen__codegen_csharp.snap

This using was added in the protobufectomy PR to all autogenerated files, even though it's unused in all of them but one (SpacetimeDBClient.cs).
As a result, it makes the autogen diff very noisy on large projects like BitCraft for no benefit.
This PR fixes it by only adding using in that single file where it's necessary.
and what other …

C#: remove `using SpacetimeDB.ClientApi;`

---

crates/bindings-macro/src/lib.rs
crates/client-api/src/routes/database.rs
crates/core/src/db/update.rs
crates/core/src/host/host_controller.rs
crates/core/src/host/mod.rs
crates/core/src/host/module_host.rs
crates/core/src/host/wasm_common.rs
crates/core/src/host/wasm_common/module_host_actor.rs
crates/standalone/src/lib.rs
modules/rust-wasm-test/src/lib.rs
smoketests/tests/modules.py

Remove support for the `update` reducer
In favor of migrations providing similar and more powerful functionality.
Also remove traces of the `migrate` reducer, for the same reasons.
Modules using `#[spacetimedb(update)]` will no longer compile.
2
Should work as before.

Remove support for the `update` reducer

---

crates/schema/Cargo.toml
tools/publish-crates.sh

Some tiny tweaks to the `schema` crate that make it publish properly to crates.io in our release process.
Nah
1
I ran `tools/publish-crates.sh` during the release process and it worked successfully (but not without these changes).

Make `schema` crate publishable

---

crates/sats/proptest-regressions/typespace.txt
crates/sats/src/algebraic_type.rs
crates/sats/src/product_type.rs
crates/sats/src/proptest.rs
crates/sats/src/sum_type.rs
crates/sats/src/typespace.rs

Introduces a notion of "nominal normal form" for `Typespace`s, which requires that `Sum` and `Product` types always be referred to via `Ref`s. The intention is that this lets us validate that the `Typespace` is in a format that makes sense for performing codegen in a nominal language, where each `Ref` corresponds to a fresh type. (Or type alias, if the `Ref` points to a `Ref`.)
This is used in my upcoming module validation PR. Note that in a module, we also have names attached to these slots via `MiscModuleExport`, but this code doesn't care about that.
The module bindings should automatically produce `Typespace`s satisfying this requirement.
We could strengthen this in various ways:
- Require that *all* types be referred to via `Ref`s.
- We could additionally require that each `Builtin` …

`Typespace::is_nominal_normal_form`

---

Cargo.lock
Cargo.toml
LICENSE.txt
crates/bindings-csharp/BSATN.Codegen/BSATN.Codegen.csproj
crates/bindings-csharp/BSATN.Runtime/BSATN.Runtime.csproj
crates/bindings-csharp/Codegen/Codegen.csproj
crates/bindings-csharp/Runtime/Runtime.csproj
crates/cli/src/subcommands/project/rust/Cargo._toml

Bump version to 0.12.0, in SpacetimeDB as well as the C# packages. (API/ABI-breaking changes have merged in SpacetimeDB itself, as well as in the C# portion of the repo: https://github.com/clockworklabs/SpacetimeDB/pull/1559).
No, this mainly "tracks" the existing breakage.
1
Literally none. Well, we have CI.

Bump version to 0.12.0

---

crates/bindings-csharp/Codegen.Tests/TestInit.cs

Verify tests already open diff windows for any changes, and the dump of raw source file in the console only adds unnecessary noise instead of being helpful. Hence, disabling.
so that …

C#: disable verbose test output in console

---

crates/data-structures/src/error_stream.rs

This updates `CollectAllErrors` to be more composable and adds some helper methods + a testing macro.
Extracted from #1572.
Technically API break, but nobody is using this yet.
0
Added tests.

Add helpers and change `CollectAllErrors` to be more composable

---

crates/core/src/db/datastore/locking_tx_datastore/mut_tx.rs

Committed transactions were being labeled as rollbacks.
None
1

fix: Correctly label transactions as committed

---

crates/core/src/db/datastore/locking_tx_datastore/mut_tx.rs
crates/core/src/execution_context.rs
crates/core/src/subscription/module_subscription_actor.rs

Previously we were not releasing downgraded transactions for incremental subscription updates.
None
1

fix: Always remember to release a read only tx

---

crates/core/src/host/scheduler.rs

find out scheduler Actor queue allows duplicate entries. this duplication happen when updating a timer row without changing `scheduled_id` in timer table as `insert` abi gets called again.
Added a check to remove an old entry from scheduler queue before adding new one.
N/A.
1

Dedup schedueler queue

---

smoketests/tests/permissions.py

When updating a database as an unauthorized user, also test that this is rejected without -c

smoketests: Test unauthorized publish without -c

---

smoketests/__init__.py
smoketests/tests/add_remove_index.py
smoketests/tests/permissions.py

This should fix it - now it'll only error if the initial update was never printed, i.e. the subscription never started. I'm about 90% sure that this should fix any race condition issues, but if there's any flakiness we can just go back to the fix from before.

Fix flaky smoketest due to race condition in subscribe

---

Cargo.lock
Cargo.toml
crates/sql-parser/Cargo.toml
crates/sql-parser/src/ast/mod.rs
crates/sql-parser/src/ast/sql.rs
crates/sql-parser/src/ast/sub.rs
crates/sql-parser/src/lib.rs
crates/sql-parser/src/parser/errors.rs
crates/sql-parser/src/parser/mod.rs
crates/sql-parser/src/parser/sql.rs
crates/sql-parser/src/parser/sub.rs

The first step towards updating the parsing of `SQL` to match the spec for `SpacetimeDB`, as asked by ticket #1563.
This is the syntactic parser, without being integrated yet into the codebase, to be done later.
1

Update SQL AST in accordance with the SQL spec

---

.rustfmt.toml

When invoked standalone (i.e. not through `cargo fmt`), `rustfmt` does not respect the edition (or any other configuration) in `Cargo.toml`, instead relying solely on `rustfmt.toml` or `.rustfmt.toml`. My editor automatically invokes `rustfmt` on individual files on save. Unless `rustfmt` sees a specified edition, it assumes 2018, and rejects any code that uses `async`. This is a huge pain.
Specify `edition = "2021"` in `.rustfmt.toml` so that standalone `rustfmt` works.
N/a
0
N/a

Add edition to .rustfmt.toml

---

crates/commitlog/src/commit.rs
crates/commitlog/src/lib.rs

Useful for alternate traversals, in particular in async contexts.
1

commitlog: Make commit module public, and allow access to header fields

---

crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#PrivateTable.verified.cs
crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#PublicTable.verified.cs
crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#Timers.SendMessageTimer.verified.cs
crates/bindings-csharp/Codegen/Module.cs

This shouldn't be a public API visible in autocomplete and such, so make it an explicit interface implementation.

C#: hide ReadGenFields from the public API

---

crates/schema/src/auto_migrate.rs
crates/schema/src/def.rs
crates/schema/src/def/validate/v9.rs
crates/schema/src/lib.rs

Implements planning, does not yet integrate.
N/A
0
See added tests.

Automatic migration planning

---

crates/bindings-csharp/.editorconfig
crates/bindings-csharp/BSATN.Codegen/Type.cs
crates/bindings-csharp/BSATN.Runtime/Attrs.cs
crates/bindings-csharp/BSATN.Runtime/BSATN/Runtime.cs
crates/bindings-csharp/BSATN.Runtime/Builtins.cs
crates/bindings-csharp/BSATN.Runtime/Internal/ByteArrayComparer.cs
crates/bindings-csharp/Codegen.Tests/fixtures/client/Lib.cs
crates/bindings-csharp/Codegen.Tests/fixtures/server/Lib.cs
crates/bindings-csharp/Codegen/Module.cs
crates/bindings-csharp/Directory.Build.props
crates/bindings-csharp/SpacetimeSharpSATS.sln

This is a follow-up to #1567:
- Add `.editorconfig` to Visual Studio solution, otherwise devs on VS don't see same code style suggestions as VSCode and/or MSBuild. Note that Visual Studio automatically regenerates `.editorconfig` with all the properties explicitly set, hence the larger file than before.
- Configure and auto-fix few more minor code style deviations.
*If you answered more than a 2, explain what is …

NFC: enforce more C# code style + enable it in Visual Studio

---

crates/snapshot/src/lib.rs

In order to serve a snapshot over the network, memory and CPU (validation) requirements for the server should be minimized.
Expose methods to allow implementing different strategies than materializing an entire `ReconstructedSnapshot`.
0

snapshot: pub access to snapshot file + object repo

---

.github/workflows/discord-posts.yml

The Discord post for merged PRs now includes the status of the `Internal tests` check.
No
2
Tested in the `github-tooling-test` repo here: https://github.com/clockworklabs/github-tooling-test/actions/workflows/post-pr-merge.yml.

CI - Discord PR merge notification includes status of `Internal tests` check

---

Cargo.lock
Cargo.toml
crates/lib/src/lib.rs
crates/planner/Cargo.toml
crates/planner/src/lib.rs
crates/planner/src/logical/bind.rs
crates/planner/src/logical/errors.rs
crates/planner/src/logical/expr.rs
crates/planner/src/logical/mod.rs
crates/sats/src/algebraic_type/fmt.rs
crates/sql-parser/src/ast/mod.rs

Defines the logical query plan and implements lowering from ast to logical plan which includes variable binding and type checking. DML is still left to do.
None
3

feat: sql type checking and logical plan

---

.github/workflows/discord-posts.yml

The CI check will ping the `DEV_OPS_ROLE_ID` in Discord if the specified CI check fails (in this case, `Internal tests`).
CI only.
1
I tested in the [github-tooling-test repo](https://github.com/clockworklabs/github-tooling-test/blob/default/.github/workflows/discord-posts.yml):

CI - Discord post will ping a particular role if CI check was not successful

---

crates/cli/src/config.rs

Fixes https://github.com/clockworklabs/SpacetimeDB/issues/1672.
Nope!
1
```
$ cargo run -- call foo bar
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.21s
Running `target/debug/spacetime call foo bar`
Saving config to /home/lead/.spacetime/config.toml..
Error: The dns resolution of `foo` failed.
```

CLI - Print out config path when saving

---

crates/bindings-csharp/BSATN.Codegen/Utils.cs
crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#PublicTable.verified.cs
crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#Timers.SendMessageTimer.verified.cs
crates/bindings-csharp/Codegen/Codegen.csproj
crates/bindings-csharp/Codegen/Module.cs
modules/benchmarks-cs/StdbModule.csproj
modules/sdk-test-connect-disconnect-cs/StdbModule.csproj
modules/sdk-test-cs/StdbModule.csproj
modules/spacetimedb-quickstart-cs/StdbModule.csproj

Currently, we have to copy-paste and hardcode property names and types from the runtime in the codegen, which is pretty error-prone, and is getting harder as our API is going to rapidly expand.
In this PR I'm implementing a basic helper that allows to reuse original attribute classes from the runtime in the codegen by taking the syntax data and reconstructing the same attribute instance via reflection.
This ensures that we have all the same typechecked properties on both sides instead of having to extract them manually by name + explicit casts.
where 1 …

[C#] [NFC] Reuse attribute classes from runtime

---

crates/planner/src/logical/bind.rs
crates/planner/src/logical/errors.rs
crates/planner/src/logical/expr.rs
crates/planner/src/logical/mod.rs
crates/planner/src/logical/ty.rs

A `RelExpr` now holds type ids instead of types.
This reduces the size of `RelExpr`.
It avoids copying and cloning types during type checking. Comparisons are also cheaper for primitive types.

perf: Use type ids for type checking

---

Cargo.lock
crates/bindings/tests/snapshots/deps__duplicate_deps.snap
crates/bindings/tests/snapshots/deps__spacetimedb_bindings_dependencies.snap
crates/commitlog/Cargo.toml
crates/commitlog/src/commitlog.rs
crates/commitlog/src/index/indexfile.rs
crates/commitlog/src/index/mod.rs
crates/commitlog/src/lib.rs
crates/commitlog/src/repo/fs.rs
crates/commitlog/src/repo/mem.rs
crates/commitlog/src/repo/mod.rs
crates/commitlog/src/segment.rs
crates/commitlog/src/tests/partial.rs
tools/upgrade-version/src/main.rs

Implements Commitlog offset proposal -https://github.com/clockworklabs/SpacetimeDBPrivate/pull/867
Reader integration is left to do in another PR.
N/A
- unit tests, and manual run for integration testing

Commitlog offset index

---

crates/cli/src/config.rs

Remove support for project-specific spacetime config files. The global Spacetime config files are unchanged.
We plan to add these back once we have a more principled approach to configs.
Fixes https://github.com/clockworklabs/SpacetimeDB/issues/1666.
Breaks anybody using project-specific config files.
2
Just existing smoketests

CLI - Remove project-specific config files

---

smoketests/__init__.py
smoketests/__main__.py

Adds a CLI option `--skip-dotnet`, which skips all dotnet tests.
If not given, and no dotnet was found, exit nonzero.
This is useful in environments where dotnet is not installed, but is
deliberately opt-in so that those tests don't rot.
1
smoketests in CI should still run all the dotnet tests

smoketests: Allow to skip tests requiring dotnet

---

crates/planner/Cargo.toml
crates/planner/src/logical/bind.rs
crates/planner/src/logical/errors.rs
crates/planner/src/logical/mod.rs
crates/planner/src/logical/stmt.rs
crates/planner/src/logical/ty.rs
crates/sql-parser/src/ast/sql.rs
crates/sql-parser/src/parser/sql.rs

Added type checking and name resolution for SQL DML statements
2

feat: Type check DML

---

crates/commitlog/src/index/indexfile.rs
crates/commitlog/src/segment.rs

Offset Index responds error if it gets 0 as key to append, Refactored a code a bit to not call offset index append if there has been no commit since last append.
Downlevelling `info!()` -> `debug!()`
N/A
1

Downlevel some info messages

---

crates/bindings-csharp/BSATN.Codegen/Utils.cs
crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#PublicTable.verified.cs
crates/bindings-csharp/Codegen.Tests/fixtures/server/snapshots/Module#Timers.SendMessageTimer.verified.cs
crates/bindings-csharp/Codegen/Module.cs
crates/bindings-csharp/Runtime/Attrs.cs
crates/bindings-csharp/SpacetimeSharpSATS.sln
modules/Directory.Build.props

A follow-up to #1719:
- Hide `ColumnAttrs` and base `ColumnAttribute` classes into `SpacetimeDB.Internal` since they shouldn't be accessed by user.
- Remove legacy `PrimaryKeyIdentity` alias as `ColumnAttrs` is no longer part of the public API.
- Extend `ParseAs` helper to support abstract classes by accepting an explicit type.
- Reuse `ParseAs` in couple of places instead of manual parsing.
- Combine attributes by table early during parsing to reduce number of stored elements that need to be cached and iterated over.
- Stringify ColumnAttrs as variant name again.
where 1 is a trivial change, and 5 is a deep-reaching and …

Minor attribute cleanups for C# module

---

.github/workflows/ci.yml
smoketests/tests/csharp_module.py

Before this, we couple of times ran into issues where a version in SpacetimeDB template was outdated, or NuGet sources were in incorrect order, and so on, which led to either tests failing with misleading error (https://github.com/clockworklabs/SpacetimeDB/commit/2b09c8d1f8868c22f8d3b6af30a492ef1ac9569c being most recent example), or, worse, quietly passing even when code or versions are actually broken.
Apparently, NuGet has a package source mapping feature which allows to ensure that specific packages are only pulled from specific custom sources, which is exactly what we want here. It allows us to ensure that SpacetimeDB.* pacakges for smoketests are pulled from our local build folders, and not from nuget.org.
corresponding …

Tighten package sources in C# smoketests

---

crates/cli/src/config.rs

We have resolved to change the default server back to `local` for the time being.
Mostly no. This changes the behavior of e.g. any automation that creates a fresh CLI install, but that doesn't seem very widespread.
1
Literally none

CLI - Change default server back to `local`

---

crates/cli/src/common_args.rs
crates/cli/src/subcommands/call.rs
crates/cli/src/subcommands/describe.rs
crates/cli/src/subcommands/publish.rs
crates/cli/src/subcommands/sql.rs
crates/cli/src/subcommands/subscribe.rs
smoketests/__init__.py

Updates `--anon-identity` to be `--anonymous`. We also remove the shorthand `-a` because we're planning to make identities much more robust, so this should be much less frequent.
Yes, it changes a CLI arg.
2
Existing smoketests have been updated

CLI - `--anon-identity` -> `--anonymous`

---

crates/bindings-sys/src/lib.rs
crates/bindings/src/table.rs
crates/core/src/host/mod.rs
crates/core/src/host/wasm_common.rs
crates/core/src/host/wasmtime/wasm_instance_env.rs

I left the implementations in `instance_env`, but removed them in `wasm_instance_env`. This is probably pending the csharp sdk switching over to btree_scan functions.
Yes.
2

Remove abi functions that are no longer needed

---

crates/cli/src/util.rs

If an identity has become invalid, we advise users to call `spacetime identity remove ${IDENTITY}`.. but it should be `spacetime identity remove -i ${IDENTITY}` since https://github.com/clockworklabs/SpacetimeDB/pull/1482/ landed.
Nope, just helptext.
1
Literally none

CLI - Fix identity removal helptext

---

crates/cli/src/config.rs
crates/cli/src/main.rs

We used to unconditionally call `config.save()` at the start of every CLI command, in order to ensure that a default version of the config is written to disk if it wasn't already there.
This PR updates the behavior to only save to disk _if_ the file didn't exist.
This addresses https://github.com/clockworklabs/SpacetimeDB/issues/1762.
None.
2
```
$ cargo run -- server list
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.25s
Running `target/debug/spacetime server list`
DEFAULT  HOSTNAME                                              PROTOCOL  NICKNAME                    
***  127.0.0.1:3000                                        http      local                       
testnet.spacetimedb.com                               https     testnet …
```

CLI - Remove the always-save-config behavior

---

crates/cli/src/subcommands/upgrade.rs

I missed making this change in https://github.com/clockworklabs/SpacetimeDB/pull/1752. This PR migrates `spacetime upgrade` to `--yes` as well.
Yes, this breaks `spacetime upgrade --force`.
1
```
$ cargo run -- upgrade 0.12.0 --yes
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.22s
Running `target/debug/spacetime upgrade 0.12.0 --yes`
Finding version...done.
You're already running the latest version: 0.12.0
Skipping confirmation due to --yes
You are currently running version 0.12.0 of spacetime. The version you're upgrading to is 0.12.0.
This will replace the current executable at /mnt/nutera/work/localhd-symlinks/SpacetimeDBPrivate/public/target/debug/spacetime.
Skipping confirmation due to --yes
Downloading update... 18.64MiB/18.64MiB (0s)
```

CLI - `spacetime upgrade` takes `--yes` instead of deprecated `--force`

---

crates/commitlog/src/commitlog.rs
crates/commitlog/src/index/indexfile.rs
crates/commitlog/src/index/mod.rs
crates/commitlog/src/repo/fs.rs
crates/commitlog/src/repo/mod.rs
crates/commitlog/src/segment.rs

1. Create `IndexFile`: a wrapper around `IndexFileMut` for exposing only read apis.
2. Update `Repo` trait to get `IndexFile`
3. Refactoring: Method naming changes to show clear distinction between read and write version of `IndexFile`
4. Modify `Commits` iterator to lookup through Index for initial commit. 
N/A
Did some manual testing

offset index read integration

---

Cargo.lock
crates/commitlog/src/commitlog.rs
crates/commitlog/src/lib.rs
crates/commitlog/src/payload.rs
crates/commitlog/src/payload/txdata.rs
crates/commitlog/src/repo/mod.rs
crates/durability/Cargo.toml
crates/durability/src/imp/local.rs

This provides access to the checksum, which may be of interest.
Leaving the `History` trait as-is, as there is no immediate need for the
checksum.
Also fix rustdoc warnings.

commitlog: Yield `StoredCommit` in iterators

---

.github/CODEOWNERS

I made @bfops @jdetter and @cloutiertyler the CODEOWNERS for the CLI crate's `src/` subdirectory.
None
1
Eh :shrug:

Add CODEOWNERS for CLI crate

---

crates/cli/src/subcommands/generate/mod.rs
crates/cli/src/subcommands/publish.rs

Fix https://github.com/clockworklabs/SpacetimeDB/issues/1852.
Nope
1
New helptext below. Unfortunately, clap still shows the example using a space, but hopefully the helptext helps.
```
Usage: spacetime publish [OPTIONS] [name|address]
Arguments:
[name|address]
A valid domain or address for this database
Options:
-c, --delete-data
When publishing to an existing address, first DESTROY all data associated with the module
--build-options <build_options>
Options to pass to the build command, for example --build-options='--skip-println-checks'
[default: ]
-p, --project-path <project_path>
The system path (absolute or relative) to the module project
[default: .]
-b, --bin-path <wasm_file>
The system path (absolute or relative) to the compiled wasm binary we should publish, instead of building …
```

CLI - Add helptext for `--build-options`

---

Cargo.lock
Cargo.toml
crates/core/src/host/wasm_common.rs

Our wasmtime version is pretty old, it'd be good to bump it before 1.0.
2 - wasmtime is well tested and I don't see a reason why a version bump would break anything.

Upgrade wasmtime dependency

---

Cargo.lock
Cargo.toml
crates/bindings-macro/src/lib.rs
crates/bindings-macro/src/module.rs
crates/bindings/Cargo.toml
crates/bindings/src/rt.rs
crates/bindings/tests/ui.rs
crates/bindings/tests/ui/reducers.rs
crates/bindings/tests/ui/reducers.stderr
crates/bindings/tests/ui/tables.rs
crates/bindings/tests/ui/tables.stderr
crates/sats/src/typespace.rs

Wahoo Rust 1.78! Also, the symbol for a reducer in backtraces should now be something like `spacetime_module::myreducer::invoke` instead of `<spacetime_module::myreducer as spacetimedb::rt::Reducer>::INVOKE`
1 - just diagnostic changes

Improve bindings diagnostics and add ui tests

---

Cargo.lock
crates/client-api/src/routes/prometheus.rs
crates/core/src/db/relational_operators.rs
crates/core/src/subscription/module_subscription_manager.rs
crates/core/src/subscription/subscription.rs
crates/durability/src/lib.rs
crates/lib/src/relation.rs
crates/schema/src/type_for_generate.rs
crates/sdk/src/spacetime_module.rs
crates/table/src/btree_index.rs
crates/table/src/table.rs
crates/testing/src/sdk.rs
crates/vm/src/expr.rs
crates/vm/src/rel_ops.rs

`hashbrown` updated their default hasher - https://github.com/rust-lang/hashbrown/blob/master/CHANGELOG.md#v0150---2024-10-01.
Which is conflicting with `DefaultHashBuilder` in our custom types.
start initialising using `::default()` to fix this.
N/A
1
Successful compiling should be enough.

Fix Build: Use default() to init custom hash based datastructures 

---

crates/cli/src/subcommands/server.rs
smoketests/tests/servers.py

`spacetime server edit` had a bug during renames, where it would try to access the server config by the old name, causing an error.
This must have been broken for a long time. The code has been in this state for a while, looks like about a year from the git history (a1e9984840ff60d77023f04927e50929cc7e0102).
No. Bugfix.
1
I added a smoketest.

CLI - Fix `spacetime server edit` failing on renames

---

Cargo.toml
crates/bench/src/lib.rs
crates/bindings-csharp/BSATN.Runtime/Builtins.cs
crates/bindings/src/rt.rs
crates/cli/src/subcommands/subscribe.rs
crates/core/src/client/messages.rs
crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
crates/core/src/db/datastore/system_tables.rs
crates/core/src/host/wasmtime/wasmtime_module.rs
crates/core/src/sql/compiler.rs
crates/core/src/sql/type_check.rs
crates/lib/proptest-regressions/address.txt
crates/lib/src/address.rs
crates/lib/src/identity.rs
crates/lib/tests/serde.rs
crates/lib/tests/snapshots/serde__json_mappings-2.snap
crates/lib/tests/snapshots/serde__json_mappings.snap
crates/sats/src/algebraic_type.rs
crates/sats/src/hash.rs
crates/sats/src/product_type.rs
crates/standalone/src/control_db.rs
crates/standalone/src/control_db/tests.rs
smoketests/tests/identity.py

Redefines `Address` as `u128`.
Breaks the stored type of `Address` in system tables and in user tables.

Redefine Address as `U128` + `Identity` and Hash as `U256`

---

crates/bindings-csharp/Runtime/Internal/Autogen/RawScheduleDefV9.cs
crates/bindings-csharp/Runtime/Internal/Autogen/RawTableDefV9.cs
crates/bindings-macro/src/lib.rs
crates/bindings/src/lib.rs
crates/bindings/src/rt.rs
crates/bindings/src/table.rs
crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
crates/core/src/db/datastore/locking_tx_datastore/mut_tx.rs
crates/core/src/db/datastore/system_tables.rs
crates/core/src/db/relational_db.rs
crates/core/src/host/instance_env.rs
crates/core/src/host/scheduler.rs
crates/lib/src/db/raw_def/v9.rs
crates/schema/src/auto_migrate.rs
crates/schema/src/def.rs
crates/schema/src/def/validate/v8.rs
crates/schema/src/def/validate/v9.rs
crates/schema/src/schema.rs

Resolves #1816. Also changes `primary_key` to be a `ColList` for future compat reasons.
Breaking, yes, but so we can be compatible with future changes.

Have the scheduled_id/at columns be specified in the schema, not by the column name

---

crates/commitlog/src/commitlog.rs

Fix iterating over transactions to yield transaction decode errors.
Due to `Itertools::flatten_ok` relying on `IntoIterator::into_iter` for flattening, we would just drop those errors.
Note that this is used for tooling only, database replaying uses folding.

commitlog: Fix transactions iterator

---

.github/CODEOWNERS

I removed CODEOWNERS for the `generate/` subdirectory of the CLI code, since this logic is pretty separate from the rest of the CLI.
**However** I keep the codeowners on `generate/mod.rs` because this includes the "interface" itself. I'm fine with somebody moving more code-generation code out of `mod.rs` so that it doesn't require codeowner review.
No code changes.
1

Remove CODEOWNERS from CLI codegen

---

crates/cli/src/config.rs
crates/cli/src/subcommands/identity.rs
crates/cli/src/subcommands/server.rs

Fix helptext that should have been updated in https://github.com/clockworklabs/SpacetimeDB/pull/1845.
No
1
None, just error messages have been updated.

CLI - Fix helptext after #1845

---

crates/client-api/src/lib.rs
crates/client-api/src/routes/database.rs
crates/client-api/src/util.rs
crates/lib/src/identity.rs
crates/testing/src/modules.rs
smoketests/__init__.py
smoketests/tests/auto_migration.py
smoketests/tests/describe.py
smoketests/tests/domains.py
smoketests/tests/new_user_flow.py
smoketests/tests/permissions.py
smoketests/tests/sql.py
smoketests/tests/zz_docker.py

Removed more references to addresses. Fixed how identities are created for databases.
Technically breaks the API of the `database/info` route
2
Just the unit and integration tests.

Small naming fixes. Fixes database identity creation.

---

crates/execution/Cargo.toml
crates/execution/src/iter.rs

* Adds a non-unique (constraint) index join iterator
* Abstracts over index key projections in order to reuse code between unique and non-unique index joins

feat: Add non-unique index join iterator

---

crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
crates/core/src/db/relational_db.rs

Introduces a method on `Locking` to take a snapshot of the current committed state. Additionally a static method, so that the snapshot worker can use the same code.
This is useful for tooling, where it usually does not make sense to spin up a `RelationalDB`.

core: Expose snapshot taking on `Locking` datastore

---

crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
crates/core/src/db/relational_db.rs

Required by tooling to be able to iterate over transactions, starting from the offset after a (potential) snapshot restore.
**NOTE**: On top of #1898, because the tooling work depends on the whole series.

core: Expose `next_tx_offset` of the `Replay` decoder

---

crates/commitlog/src/commit.rs
crates/commitlog/src/commitlog.rs
crates/commitlog/src/payload.rs
crates/commitlog/src/segment.rs

The `*_from` style traversals have historically yielded commits or transactions before the given from-offset, leaving it to downstream consumers to handle skipping.
While folding handles it internally, this behavior is not great for transaction iterators, due to the statefulness of decoding -- it is usually necessary to call `Decoder::skip_record` until the desired offset is found.
We would also yield all commits from the start of the nearest segment boundary, which can be quite confusing when using the commit iterators directly.
This patch fixes the situation by:
* Setting the desired offset as the inital next offset in the `Commits` iterator, instead of the nearest segment boundary.
* Looping instead of recursing in the `Commits` iterator while skipping commits, so we can skip until the …

commitlog: Improve skipping behavior of traversals

---

crates/bindings-csharp/BSATN.Runtime/Builtins.cs

Looks like this was marked as resolved in review on #1616 by mistake. https://github.com/clockworklabs/SpacetimeDB/pull/1616#discussion_r1724978832
so that you're confident that all the …

NFC: Remove obsolete BytesWrapper

---

crates/bindings-csharp/BSATN.Codegen/BSATN.Codegen.csproj
crates/bindings-csharp/BSATN.Runtime/BSATN.Runtime.csproj
crates/bindings-csharp/Codegen/Codegen.csproj
crates/bindings-csharp/Runtime/Runtime.csproj
crates/cli/src/subcommands/project/csharp/StdbModule._csproj

The C# bindings still seem to be on 0.12.0. This PR updates them to be 1.0.0 like the rest of our repo.
No. This just updates version numbers.
1
None / existing tests.
SDK tests will be fixed by https://github.com/clockworklabs/com.clockworklabs.spacetimedbsdk/pull/180.

Bump C# bindings to 1.0.0

---

crates/bench/benches/subscription.rs
crates/bench/src/spacetime_raw.rs
crates/client-api/src/routes/database.rs
crates/core/src/db/datastore/locking_tx_datastore/committed_state.rs
crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
crates/core/src/db/datastore/locking_tx_datastore/mut_tx.rs
crates/core/src/db/datastore/locking_tx_datastore/state_view.rs
crates/core/src/db/datastore/locking_tx_datastore/tx.rs
crates/core/src/db/datastore/system_tables.rs
crates/core/src/db/datastore/traits.rs
crates/core/src/db/relational_db.rs
crates/core/src/db/update.rs
crates/core/src/estimation.rs
crates/core/src/execution_context.rs
crates/core/src/host/instance_env.rs
crates/core/src/host/module_host.rs
crates/core/src/host/scheduler.rs
crates/core/src/host/wasm_common/module_host_actor.rs
crates/core/src/host/wasmtime/wasm_instance_env.rs
crates/core/src/sql/compiler.rs
crates/core/src/sql/execute.rs
crates/core/src/subscription/execution_unit.rs
crates/core/src/subscription/module_subscription_actor.rs
crates/core/src/subscription/module_subscription_manager.rs
crates/core/src/subscription/query.rs
crates/core/src/subscription/subscription.rs
crates/core/src/util/slow.rs
crates/core/src/vm.rs
crates/sqltest/src/space.rs

As a preparatory step for further PRs, like those related to the new `Query Engine`, most usages of `ExecutionContext` as an additional context in database calls are removed and put inside the `Tx` contexts instead.
* This pr touches everything related to the db
* It could change the metrics. There were many places where the `ExecutionContext` was overwritten and now it should provide more exact measurements.
* Is necessary to check if it passes correctly the `Identity` & `Address` of replicas
3

Put `ExecutionContext` inside the Tx context

---

crates/cli/src/subcommands/generate/csharp.rs
crates/cli/tests/snapshots/codegen__codegen_csharp.snap

Make the static fields indexing primary keys instance fields.
Codegen compiles. Same code as before but going through a `this` pointer instead of a `static` .
Context from Boppy: The Unity testsuite exercises this feature in the testsuite: https://github.com/clockworklabs/com.clockworklabs.spacetimedbsdk/pull/168

C# codegen making state relative to a DbConnection

---

crates/bindings-csharp/Runtime/Internal/ITable.cs

Clickbait title, but there is no other way to say this. It must be the weirdest way I optimised anything yet.
I was suspicious that a lot of benchmarks, in particular those that deal with iteration - which we have for C# as of recently - take about the same amount of time. After digging in for a bit, I narrowed it down to merely presence of this destructor. Looks like the way destructors are implemented for the Wasm target somehow deoptimises the execution to the point where simply removing it speeds up benchmarks by 15x or more.
We don't really need it anyway, it was more of a nice-to-have in case user does something weird, since regular iterator usage like `foreach` always calls `Dispose()` correctly.
Further investigation and an upstream issue to .NET coming up, but meanwhile here are …

Optimise C# in a ridiculous way

---

Cargo.lock
crates/execution/Cargo.toml
crates/execution/src/iter.rs

Defines an execution plan that is cached for subscription evaluation. This will be the lowering target for the physical plan.

Cached query execution plan

---

crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
crates/core/src/db/datastore/locking_tx_datastore/mut_tx.rs
crates/core/src/db/datastore/locking_tx_datastore/tx.rs
crates/core/src/execution_context.rs

So that we can correlate subscription updates with reducers

Use previous reducer context when downgrading a tx

---

crates/commitlog/proptest-regressions/tests/bitflip.txt
crates/commitlog/src/commit.rs
crates/commitlog/src/commitlog.rs
crates/commitlog/src/lib.rs
crates/commitlog/src/payload/txdata.rs
crates/commitlog/src/repo/mod.rs
crates/commitlog/src/segment.rs

Adds a field `epoch` typed u64 to the commit header. It signifies the
term number of the leader when writing to a commitlog in a distributed
setting.
It will help detecting and recovering from divergent logs, a situation
which can arise during a leader failover.

commitlog: Introduce epoch

---

crates/cli/src/util.rs

The `token show` command was decoding tokens in a way that required the identity field to be set. When we parse tokens from clients, we can compute the identity from the other claims. This PR fixes the `token show` command to do the same.
1
@bfops tested this manually.

Decode identity correctly

---

.github/workflows/benchmarks.yml

I thought we had already done this.
0
I am about to run CI by clicking the "Create Pull Request" button...

Clean up benchmark .spacetime in CI

---

crates/physical-plan/src/compile.rs
crates/physical-plan/src/plan.rs

refactor: encode type info implicitly in the physical plan

---

crates/cli/src/config.rs

I removed the `default_identity` member and the associated functions, since they're not currently used anywhere.
None
1
Existing tests only

CLI - Remove unused `default_identity` stuff

---

crates/cli/src/subcommands/login.rs

Currently, `spacetime login` just silently returns if the user is already logged in.
This PR adds a message informing the user that they are already logged in.
None
1
```
$ cargo run -- login
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.27s
Running `target/debug/spacetime login`
You are already logged in.
If you want to log out, use spacetime logout.
```

CLI - Tell users if they're already logged in

---

crates/cli/src/util.rs

Update stale help text that referred to `spacetime identity` (which has been removed).
No breaking changes
1
Existing tests only

CLI - Fix stale helptext instructing users to use `spacetime identity`

---

crates/bindings-csharp/BSATN.Codegen/BSATN.Codegen.csproj
crates/bindings-csharp/BSATN.Runtime/BSATN.Runtime.csproj
crates/bindings-csharp/Codegen/Codegen.csproj
crates/bindings-csharp/Runtime/Runtime.csproj

Bump the C# packages to version `1.0.0-rc1-hotfix1`, so they can be published to nuget.
No
1
Existing CI only.

Bump C# versions to `-hotfix1`

---

crates/bindings-macro/src/table.rs
crates/bindings/src/table.rs
crates/commitlog/src/payload.rs
crates/sats/src/buffer.rs
crates/standalone/src/control_db.rs

Not really important, just something I noticed could be cleaner.
Comparison for `integrate_generated_columns` for:
```rust
pub struct TestE {
#[primary_key]
#[auto_inc]
id: u64,
#[index(btree)]
name: String,
}
```
<details><summary>LLVM IR before this change:</summary>
```ll
; <rust_wasm_test_module::_::test_e__TableHandle as spacetimedb::table::Table>::integrate_generated_columns
; Function Attrs: noinline nounwind nonlazybind
define internal fastcc void @"<rust_wasm_test_module::_::test_e__TableHandle as spacetimedb::table::Table>::integrate_generated_columns"(ptr noalias nocapture noundef align 8 dereferenceable(32) %_row, ptr noalias noundef nonnull readonly align 1 %0, i64 noundef %1) unnamed_addr #5 personality ptr @rust_eh_personality {
start:
%self1.i.i = alloca …
```

Optimize integrate_generated_columns

---

Cargo.lock
crates/cli/src/util.rs
crates/client-api/Cargo.toml
crates/client-api/src/auth.rs
crates/client-api/src/lib.rs
crates/client-api/src/routes/identity.rs
crates/core/Cargo.toml
crates/core/src/auth/identity.rs
crates/core/src/auth/mod.rs
crates/core/src/auth/token_validation.rs
crates/standalone/src/lib.rs

This is an attempt to clean up auth-related code. To summarize the main changes:
1. We don't use a global OIDC key cache any more.
2. The 4 JWT related functions in the `NodeDelegate` trait were removed, and the functionality was put in the `JwtAuthProvider` trait. `NodeDelegate` now just has one function to return an auth provider. This should make it easier to change this in the future. The new trait also exposes functions for signing and verifying keys, rather than giving the concrete keys.
3. `SpacetimeIdentityClaims2` is now the only `SpacetimeIdentityClaims`.
4. Instead of using `jsonwebkey` in the token validation tests, we use the same key generate code that is used for standalone key generation. There were some small changes to the key generate code to make it easier to reuse. …

Clean up auth related code with traits, and reuse existing key generation code.

---

crates/core/src/db/datastore/locking_tx_datastore/tx.rs

Change `TxId::num_distinct_values` to return `Option<NonZeroU64>`.
It will now return `None` if either the table doesn't exist, no index
exists for the given column list, or the index is empty.
Otherwise, `Some` non-zero number of distinct values is returned.
Fixes a division-by-zero bug in the query row estimation.
1
No functional change, `estimation::index_row_est` is now statically guaranteed
to not panic due to division-by-zero

core: Make NDV non-zero

---

crates/core/src/estimation.rs

Adds test that fails before https://github.com/clockworklabs/SpacetimeDB/pull/1985

test: No divide by zero for row estimation of empty index

---

.github/workflows/benchmarks.yml
Cargo.lock
crates/bench/Cargo.toml
crates/bench/benches/generic.rs
crates/bench/benches/special.rs
crates/bench/src/database.rs
crates/bench/src/lib.rs
crates/bench/src/spacetime_module.rs
crates/bench/src/spacetime_raw.rs
crates/bench/src/sqlite.rs
crates/bindings-csharp/Runtime/build/SpacetimeDB.Runtime.targets
crates/testing/src/modules.rs
crates/testing/tests/standalone_integration_test.rs
modules/benchmarks-cs/ia_loop.cs

Turns out, there are some APIs that are not covered by any of our tests, except benchmarks.
Benchmarks are executed as both actual benchmarks and as integration tests for Rust, but not for C#. This PR fixes that to ensure that both Rust and C# are tested and measured on the CI from now on.
It also makes some adjustments to integration tests themselves, in particular fixes an issue where in integration tests reducers would be called but the response would never be read, so if a reducer panics, the tests would still succeed. Additionally, on failures the SpacetimeDB logs will be read and added to the error message so that you get a useful stacktrace from the module itself.
I also had to adjust some benchmark numbers (in particular, for `ia_loop`) since they were already very slow on CI for …

Run and test benchmarks against C# as well

---

Cargo.lock
crates/core/src/host/module_host.rs
crates/schema/Cargo.toml
crates/schema/src/def.rs
crates/schema/src/def/validate/v9.rs
modules/benchmarks-cs/ia_loop.cs

This was found while working on #1965. The tests will come in that other PR, but it was suggested that we should land the correctness fix itself sooner.
so that you're confident that …

Preserve reducer order in schema conversion

---

Cargo.lock
crates/core/Cargo.toml
crates/core/src/auth/token_validation.rs

The test_oidc_flow test has had some spurious failures, so this adds the following:
1. We have a few more debug logs that should help figure out whats happening if there are more failures.
2. When starting up an OIDC server in the tests, we wait for a successful request before continuing. This is just in case there is some race condition around server startup.
3. The actual fix is that we encode the key parameters correctly in our tests.
The cause for the failures is that when we encoded keys to JWKS in tests, we used `openssl::bn::BigNum` for our parameters, which is a dynamically sized number. If the 8 most significant digits of a parameter happened to be 8, our JWKs would have a 31 byte parameter. According to the spec, that is invalid [section …

Fix flaky oidc tests

---

Cargo.lock
crates/client-api/Cargo.toml
crates/commitlog/Cargo.toml
crates/commitlog/src/commitlog.rs
crates/commitlog/src/segment.rs
crates/paths/Cargo.toml

The `cmp` arguments were flipped, sabotaging the intent. Add some tests while we're at it.
Also make sure the `spacetimedb-paths` crate selects the features it needs, so that we don't need to rely on workspace feature unification to be able to run said tests.

commitlog: Fix set_epoch

---

crates/table/src/page.rs
crates/table/src/pointer_map.rs

The definition of `FixedHeader` within `Page` previously contained a `#[cfg(debug_assertions)]` member which was used for some extra assertions. This was fine originally, but now that we write pages to disk in snapshots, having the serialized format of the page vary depending on compilation profile is problematic.
This commit removes said `#[cfg(debug_assertions)]` conditional member from `FixedHeader`, so that the structure, and thus the on-disk format, of `Page` is consistent between debug and release builds.
This commit also removes an unrelated but unused `#[cfg(debug_assertions)]` conditional from the pointer map code. We never called this assertion, even in debug builds. If we want to re-enable it in the future, we can restore it from git history; for now, I would prefer not to have …

Remove problematic debug assertions

---

crates/sql-parser/src/parser/errors.rs
crates/sql-parser/src/parser/sql.rs
crates/sql-parser/src/parser/sub.rs

This fixes a couple places where trying to parse an empty string into a query could panic instead of returning an error.
1
Unit tests are in the PR.

Fix some places where trying to parse an empty string could panic.

---

crates/cli/src/lib.rs
crates/cli/src/subcommands/server.rs
crates/standalone/src/subcommands/start.rs

As on the tin - it wasn't finding the data directory properly.
1

Fix spacetime server clear

---

crates/physical-plan/src/plan.rs

1. Optimizes `PhysicalProject::None`
2. Fixes filter pushdown rewrite rule so as not to match a `table_scan + filter`
1

fix: filter pushdown over table scan

---

crates/expr/src/check.rs
crates/expr/src/statement.rs
crates/sql-parser/src/ast/mod.rs
crates/sql-parser/src/ast/sql.rs
crates/sql-parser/src/ast/sub.rs
crates/sql-parser/src/parser/errors.rs
crates/sql-parser/src/parser/sql.rs
crates/sql-parser/src/parser/sub.rs

The parser qualifies all names. Any names that remain unqualified is a parsing error.
n/a
1
Added applicable unit test to the parser

fix: qualified projection columns

---

crates/bindings-macro/src/lib.rs
crates/bindings-macro/src/table.rs
crates/bindings/tests/ui/reducers.rs
crates/bindings/tests/ui/reducers.stderr
modules/rust-wasm-test/src/lib.rs
modules/sdk-test/src/lib.rs
smoketests/tests/modules.py
smoketests/tests/schedule_reducer.py

As edited in the proposal.
Slightly, but deemed okay breakage.
1
UI tests updated, smoketest to check that `at = ...` works.

Tweak scheduled_at macro syntax

---

crates/cli/src/subcommands/publish.rs
smoketests/__init__.py
smoketests/tests/permissions.py

When publishing to a server besides `localhost` or `127.0.0.1`, prompt for confirmation.
Yes; this technically breaks the CLI API for publishing to non-local servers.
1
```
$ "$WORK"/SpacetimeDBPrivate/public/target/debug/spacetime publish -s testnet
checking crate with spacetimedb's clippy configuration
Checking spacetime-module v0.1.0 (/mnt/nutera/work/my_new_project)
Finished `release` profile [optimized] target(s) in 0.14s
Finished `release` profile [optimized] target(s) in 0.11s
Optimising module with wasm-opt...
Could not find wasm-opt to optimise the module.
For best performance install wasm-opt from https://github.com/WebAssembly/binaryen/releases.
Continuing with unoptimised module.
Build finished successfully.
You are about to publish to a non-local server: …
```

CLI - Confirm before publishing to non-local servers

---

crates/cli/src/subcommands/generate/mod.rs

Little QOL improvement.
1
I ran `spacetime generate` to ensure that the spinner shows up and tells the user what it's doing.

Use a spinner to show that wasm is compiling in spacetime generate

---

crates/sdk/src/subscription.rs
crates/sdk/tests/test-client/src/main.rs

Rust client SDK analogue to [com.clockworklabs.spacetimedbsdk #211](https://github.com/clockworklabs/com.clockworklabs.spacetimedbsdk/pull/211).
Currently an abstraction over `SELECT * FROM *`, but that may change in the future. The new subscription API will be unable to cleanly support users supplying `SELECT * FROM *`, but this method we can continue supporting more easily.
Additive change only.
1.

Add `SubscriptionBuilder::subscribe_to_all_tables`

---

tools/publish-crates.sh

We had several crates that were missing from the `publish-crates.sh` script, meaning that manual intervention was required for it to run properly.
No code changes
1
I believe this is where I added them in order to successfully publish to crates.io, but it's hard to re-test after the fact :shrug: Unfortunately the `--dry-run` option doesn't "just work" the way we'd want.
We'd have to set up our own temporary package repository in order to test this comprehensively.
The worst case is that we have to make further corrections next time we publish, which is the same state we're in without this PR.

Add new crates to `publish-crates.sh` script

---

crates/sdk/examples/quickstart-chat/main.rs
crates/sdk/src/credentials.rs
crates/sdk/src/db_connection.rs
crates/sdk/src/websocket.rs
crates/sdk/tests/test-client/src/main.rs

See discussion on https://github.com/clockworklabs/com.clockworklabs.spacetimedbsdk/pull/212
This PR replaces `DbConnectionBuilder::with_credentials` with `::with_token`, which does not require an `Identity` as argument. It also amends our machinery for saving and loading credentials to and from disk to suit the new API.
Yep!
1.

Rust SDK: `with_credentials` -> `with_token`

---

Cargo.lock
Cargo.toml
crates/cli/Cargo.toml
crates/cli/src/lib.rs
crates/cli/src/main.rs
crates/cli/src/start.rs
crates/cli/src/subcommands/subscribe.rs
crates/client-api-messages/src/websocket.rs
crates/client-api/src/routes/subscribe.rs
crates/core/src/db/relational_db.rs
crates/paths/Cargo.toml
crates/paths/src/cli.rs
crates/paths/src/lib.rs
crates/paths/src/utils.rs
crates/standalone/Cargo.toml
crates/standalone/src/lib.rs
crates/standalone/src/subcommands/start.rs
crates/testing/src/lib.rs
crates/testing/src/sdk.rs
crates/update/Cargo.toml
crates/update/src/main.rs
crates/update/src/proxy.rs
smoketests/__init__.py
smoketests/__main__.py

Resolves #1838
Adds a `spacetimedb-update` multicall binary that proxies to `spacetimedb-cli`, and makes `spacetime run` call out to the `spacetimedb-standalone` binary instead of embedding the whole server in the cli. Functionality for the `update` binary itself forthcoming in another PR.
3 - adds the proxy binary and changes how `run` works under-the-hood, but the deeper changes will come in the follow-up.

Split binaries

---

.github/workflows/ci.yml
crates/update/src/proxy.rs
smoketests/__init__.py
smoketests/__main__.py
smoketests/tests/csharp_module.py

~~I don't intend to spend a ton of time on this, but maybe it'll just work~~ yay :)
Only some slight modifications to the smoketest code needed to get this working, and then wrestling with dotnet-sdk in the ci environment. For now this is running on GitHub's windows-latest runner, but we could switch to a self-hosted runner at some point if we wanted to.
1
That's what we're doing here :)

Run smoketests on windows in ci

---

Cargo.lock
crates/client-api/Cargo.toml
crates/client-api/src/routes/database.rs
crates/client-api/src/routes/energy.rs
crates/core/src/messages/control_db.rs
crates/sats/src/de/serde.rs
crates/sats/src/lib.rs
crates/sats/src/ser/serde.rs

No behavior change, but it feels important to be able to see the actual structure of the response, especially as we're stabilizing.
1
Was not able to get spacetime-web working to test this, but it's the same schema as it was before, and it matches with the typedef in typescript in spacetime-web.

Use actual types for api responses, not ad-hoc `json!()` objects

---

crates/execution/src/lib.rs
crates/execution/src/pipelined.rs
crates/physical-plan/src/plan.rs
crates/query/src/delta.rs
crates/query/src/lib.rs

This patch is a prerequisite for computing query cpu metrics.
> Why is a new executor needed?
Tuple at a time iterators are not well suited to gathering per operator metrics.
None
2
Adding new query executors is relatively straightforward since they work off of the same physical plan. We can rely on our current test coverage to catch any issues.
No new tests have been added. We already have correctness tests for the query and subscription code that are executor agnostic.

Query execution updates for cpu metrics

---

Cargo.lock
crates/bindings-macro/Cargo.toml
crates/bindings-macro/src/table.rs
crates/bindings/src/table.rs
crates/bindings/tests/snapshots/deps__spacetimedb_bindings_dependencies.snap

Fixes 2 specific issues:
- invalid syntax (namely, at least, an incomplete if block: `if foo`) in a reducer body would cause autocomplete to break.
- This is fixed by upgrading the `proc-macro2` dependency.
- No completions for methods on unique columns.
- This is fixed by fiddling around with the bounds on the `impl` block for `UniqueColumn`. Best I can tell is that this was hitting some poorly-handled edge case in chalk, related to evaluating bounds that are too dependent on each other (?)
1

Fix autocomplete issues in bindings crate

---

crates/client-api-messages/src/websocket.rs
crates/core/src/client/messages.rs
crates/core/src/subscription/module_subscription_actor.rs

This is pulling out the server side changes that were originally in https://github.com/clockworklabs/SpacetimeDB/pull/2111.
Previously the code was not sending subscription errors for invalid queries (because we were treating those errors as generic internal errors). This fixes that. It also adds the query id to those subscription error messages, so that the clients aren't forced to track the request ids.
1
This change is covered with some end-to-end tests in https://github.com/clockworklabs/SpacetimeDB/pull/2111.
Adding unit tests in the future would be good.

Fix sending of subscription errors.

---

crates/commitlog/Cargo.toml
crates/commitlog/src/lib.rs
crates/commitlog/src/tests.rs
crates/commitlog/src/tests/helpers.rs
crates/core/Cargo.toml
crates/core/src/db/datastore/locking_tx_datastore/committed_state.rs
crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
crates/core/src/db/datastore/system_tables.rs
crates/core/src/db/relational_db.rs
crates/table/src/table.rs

This PR fixes a bug where replaying databases without a snapshot of TX 0, i.e. using the entire commitlog,
would fail when replaying deletes on `st_client`.
This is because `st_client` was in the unique (*) position of:
- Being a system table,
- with a unique index,
- which is mutated after bootstrapping.
(*) Other system tables meet all three criteria in edge cases with schema-changing publishes, but only `st_client` meets them in everyday testing.
In this case, when replaying the entire commitlog, we create the indexes on the system tables during bootstrapping before replay. (I theorize, but have not checked,
that when restoring from a snapshot we do not create these indexes so eagerly, instead waiting for after replaying the commitlog suffix to create them.)
However, we cannot update …

Don't create indexes during bootstrapping; wait until after replay

---

crates/core/src/host/module_host.rs
crates/core/src/subscription/module_subscription_manager.rs

This is fixing an obvious bug in the subscription manager. When a client disconnects, we are removing the queries, but not removing our record of the client. This is a memory leak (and would be an issue if clients reused their connection ids).
@kim this should fix the logs you were seeing when shutting down a worker.
1
Unit tests are now asserting that we remove the clients.

Remove the client from subscription manager on a disconnect

---

Cargo.lock
Cargo.toml
crates/bindings-csharp/BSATN.Codegen/BSATN.Codegen.csproj
crates/bindings-csharp/BSATN.Runtime/BSATN.Runtime.csproj
crates/bindings-csharp/Codegen/Codegen.csproj
crates/bindings-csharp/Runtime/Runtime.csproj
crates/cli/src/subcommands/project/csharp/StdbModule._csproj
crates/cli/src/subcommands/project/rust/Cargo._toml

We have released `v1.0.0-rc3`. This PR bumps us to the next RC version. (Hotfixes will happen on cherrypicked branches, and will therefore not include this PR).
No, just a version bump.
1
None. This just bumps the version.

Bump version to `1.0.0-rc4`

---

crates/core/src/host/wasm_common/module_host_actor.rs
crates/core/src/host/wasmtime/wasmtime_module.rs
crates/core/src/worker_metrics/mod.rs

Add a `record_reducer_allocated_memory` method to `EnergyMonitor`, and call it after every reducer run. The `EnergyMonitor` implementation can decide how much it wants to debounce the event.
1
This just adds a new hook, but there's not yet an implementation of that hook to test.

Meter wasm memory usage

---

crates/core/src/host/wasm_common/module_host_actor.rs
smoketests/tests/panic.py

Log errmsg if reducer fails

---

Cargo.lock
crates/client-api/src/lib.rs
crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
crates/core/src/db/datastore/locking_tx_datastore/mut_tx.rs
crates/core/src/db/datastore/locking_tx_datastore/tx.rs
crates/core/src/db/datastore/system_tables.rs
crates/core/src/sql/compiler.rs
crates/core/src/sql/execute.rs
crates/core/src/sql/parser.rs
crates/core/src/util/slow.rs
crates/execution/Cargo.toml
crates/execution/src/dml.rs
crates/execution/src/lib.rs
crates/execution/src/pipelined.rs
crates/expr/src/expr.rs
crates/expr/src/lib.rs
crates/expr/src/statement.rs
crates/lib/src/lib.rs
crates/lib/src/st_var.rs
crates/physical-plan/src/compile.rs
crates/physical-plan/src/dml.rs
crates/physical-plan/src/lib.rs
crates/physical-plan/src/plan.rs
crates/query/src/delta.rs
crates/query/src/lib.rs

DML was still using the old engine. This patch updates it to use the new engine.
NOTE: Internal tests are failing due to a new dependency in core. Hence this pr will merge with internal tests failing, but they will be fixed immediately afterwards.
None
3
There are a few non-trivial changes:
1. `SET` and `SHOW` statements are rewritten as `INSERT` and `SELECT` respectively
2. We have to parse the query to determine if it is a dml statement and therefore whether it should be executed in a mutable or read-only transaction
All previous tests still apply

Track compute metrics for sql dml with new engine

---

crates/core/proptest-regressions/db/datastore/locking_tx_datastore/delete_table.txt
crates/core/src/db/datastore/locking_tx_datastore/delete_table.rs

A rare-ish edge case in a few of our proptests caused spurious failures when the runner generated two equal row pointers. The test was intended to verify behavior with non-equal pointers, and so was not equipped to handle this case. A simple `prop_assume!` call tells the runner to ignore that case.
N/a
1

`prop_assume!(a != b)` in some tests to fix spurious failures

---

crates/core/src/subscription/module_subscription_actor.rs
crates/core/src/subscription/module_subscription_manager.rs
crates/core/src/subscription/query.rs
crates/core/src/subscription/subscription.rs
crates/physical-plan/src/dml.rs
crates/physical-plan/src/plan.rs
crates/physical-plan/src/rules.rs
crates/query/src/delta.rs
crates/query/src/lib.rs

Instead of invoking `unreachable!` in the query rewrite code, now we return an error. An error means we have an internal logic bug, but we don't want the server to panic in that case. Instead we just log the error. There's a TODO for handling the error appropriately in the subscription code.
None
2
Just a return type change and updating callers.
A simple refactor so no new tests added.

Return errors for invariant violations during query planning

---

crates/core/src/energy.rs
crates/standalone/src/lib.rs

This registers the recently added datasize metrics with our other prometheus stats.
There is also a random one-line comment in a different part of the code that wasn't worth its own PR.
1
If you wanted to verify this manually, you could run a standalone instance with data, curl the `/metrics` endpoint, and look for the data size metrics.

Register data size metrics for standalone.

---

crates/cli/src/tasks/mod.rs
crates/cli/src/util.rs

We used to assume a project was a rust project if it had a `Cargo.toml`, and otherwise assume that it's a .NET project. Now we do something _slightly_ smarter, where we only assume it's a .NET project if there's a `*.csproj` file (and error otherwise).
Fixes #2136 .
No, not for projects that are in any format we expect.
1
```
$ mkdir test-project && cd test-project
$ spacetimedb-cli publish -s local foo
Error: Could not detect the language of the module. Are you in a SpacetimeDB project directory?
```
```
$ mkdir test-project && cd test-project
$ touch Foo.csproj
$ spacetimedb-cli publish -s local foo
MSBuild version 17.8.5+b5265ef37 for .NET
/mnt/nutera/work/foo/Foo.csproj : error MSB4025: The project file could not be loaded. Root element is missing.
Error: command ["dotnet", "publish", …
```

CLI - Better module language inference

---

crates/cli/src/subcommands/login.rs

The helptext used to just say "log in to spacetimedb" which conflicted with e.g. `spacetime login show` which just displayed login info.
No
1
```
$ cargo run -- login help
Manage your login to the SpacetimeDB CLI
Usage: spacetimedb-cli login [OPTIONS]
spacetimedb-cli login <COMMAND>
Commands:
show  Show the current login info
help  Print this message or the help of the given subcommand(s)
Options:
--auth-host <auth-host>         Fetch login token from a different host [default: https://spacetimedb.com]
--server-issued-login <server>  Log in to a SpacetimeDB server directly, without going through a global auth server
--token <spacetimedb-token>     Bypass the login flow and use a login token directly
-h, --help                          Print help
```

CLI - Clarify helptext for `spacetime login`

---

crates/core/src/db/db_metrics/mod.rs
crates/core/src/host/wasm_common/instrumentation.rs
crates/core/src/host/wasm_common/module_host_actor.rs
crates/core/src/host/wasmtime/wasmtime_module.rs

This adds some metrics for reducer runtime and wasmtime fuel usage.
1
I manually tested a version of this on a different branch. By running some reducers and looking at the stats.

Add metrics for fuel usage and reducer runtime totals.

---

Cargo.lock
crates/core/src/host/host_controller.rs
crates/core/src/host/instance_env.rs
crates/core/src/sql/execute.rs
crates/core/src/subscription/module_subscription_actor.rs
crates/core/src/subscription/module_subscription_manager.rs
crates/sqltest/Cargo.toml
crates/sqltest/src/space.rs

When an error occurs during a tx update (subscription evaluation), we will now:
1. Send a `SubscriptionError` to the relevant clients
2. Drop the full set of subscriptions for each such client
To drop the subscriptions, we mark the affected clients when the error occurs (see eval_updates), and an async task will periodically remove them from the mapping.
> Why not drop them when the error occurs (in eval_updates)?
This would require holding a write lock on the `SubscriptionManager` preventing other read only transactions from running.
None
4
Not a big change, but touches concurrency related code.
Added the following new tests:
1. Subscribing with an invalid query returns an error to the client
2. Removing an index and unsubscribing from a query that relied on that index also returns an …

Error handling for incremental evaluation

---

crates/cli/src/subcommands/generate/typescript.rs

Just updated TypeScript code gen to pass in a few more generics params.
Technically a breaking change since the expected error types on `.onConnectError` and `.onDisconnect` are now different.
1
I generated the types for the TypeScript quick start and verified that it was still working.

Added context types to DBConnectionBuilder

---

crates/cli/src/subcommands/call.rs
crates/cli/src/subcommands/describe.rs
crates/cli/src/subcommands/energy.rs
crates/cli/src/subcommands/init.rs
crates/cli/src/subcommands/list.rs
crates/cli/src/subcommands/server.rs
crates/cli/src/subcommands/sql.rs
crates/cli/src/subcommands/subscribe.rs
crates/cli/src/util.rs

Addresses https://github.com/clockworklabs/SpacetimeDB/issues/1820.
Note: I only added this text to the CLI commands list. I did not add it to other binaries, especially `spacetimedb-update`.
Not API/ABI breaking.
1
```
$ cargo run -pspacetimedb-cli -- init --help
Compiling spacetimedb-cli v1.0.0-rc4 (/home/lead/work/clockwork-localhd/SpacetimeDBPrivate/public/crates/cli)
Finished `dev` profile [unoptimized + debuginfo] target(s) in 17.35s
Running `target/debug/spacetimedb-cli init --help`
Initializes a new spacetime project.
WARNING: This command is UNSTABLE and subject to breaking changes.
Usage: spacetimedb-cli init --lang <lang> [project-path]
Arguments:
[project-path]  The path where we will create the spacetime project [default: .]
Options:
-l, --lang <lang>  The spacetime module …
```

CLI - Warn when using an unstable command

---

crates/cli/src/tasks/csharp.rs

Fix confusing csharp workload-install error message

---

crates/cli/src/api.rs
crates/cli/src/subcommands/call.rs
crates/cli/src/subcommands/describe.rs
crates/cli/src/subcommands/list.rs
crates/cli/src/subcommands/subscribe.rs
crates/cli/src/util.rs
crates/client-api/src/auth.rs
crates/client-api/src/routes/database.rs
crates/core/src/host/host_controller.rs
crates/core/src/host/mod.rs
crates/sats/src/lib.rs
crates/sdk/src/websocket.rs
smoketests/tests/describe.py
smoketests/tests/permissions.py

Get rid of the weird stuff in `describe` and just return a RawModuleDef.
2 - changes api a decent amount but only to return an already well-established format.

Remove janky schema from http API

---

crates/cli/src/config.rs

Replaced testnet with maincloud in the default config file.
I did **not** replace it in any of our tests, since those test config files don't actually need to be synced with our real config files. I can replace there too if that's preferred.
Not breaking.
1
```
$ rm ~/.config/spacetime/cli.toml
$ cargo run -p spacetimedb-cli -- server add foo --url https://foo.spacetimedb.com --no-fingerprint
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.24s
Running `target/debug/spacetimedb-cli server add foo --url 'https://foo.spacetimedb.com' --no-fingerprint`
Saving config to /home/lead/.config/spacetime/cli.toml.
WARNING: This command is UNSTABLE and subject to breaking changes.
Host: foo.spacetimedb.com
Protocol: https
Saving config to /home/lead/.config/spacetime/cli.toml.
$ cat …
```

CLI - Default config lists maincloud, not testnet

---

crates/client-api/src/auth.rs

Follow up to #2181. If a client somehow can send basic auth but not bearer, they can also just use the `?token` param.
Breaks http api - not sure what the counts as. Nothing needed from users besides upgrading, though.
1: this is covered by tests, and all the relevant client sdks have been updated to use bearer auth instead of basic.

Only support bearer auth

---

.github/workflows/docker.yml

The old version is becoming deprecated, is currently going through brownout periods, and will become entirely nonfunctional as of March 1, 2025.
See https://github.com/actions/cache/discussions/1510.
No breaking changes. CI only.
1
This has been tested elsewhere (contact @bfops for more details).

CI - Update `actions/cache@v2` -> `@v4`

---

.github/workflows/ci.yml

https://github.com/clockworklabs/com.clockworklabs.spacetimedbsdk/issues/226 renamed the branches in the C# SDK repo.
This PR updates our CI to use the new branch name.
No breaking changes.
1
The CI passes on this PR (specifically, the `SDK Tests` job passes, which was no longer the case without this change).

CI - Fix the `SDK Tests` CI job after branch rename

---

crates/cli/src/subcommands/call.rs
crates/cli/src/subcommands/describe.rs
crates/cli/src/subcommands/energy.rs
crates/cli/src/subcommands/init.rs
crates/cli/src/subcommands/list.rs
crates/cli/src/subcommands/server.rs
crates/cli/src/subcommands/sql.rs
crates/cli/src/subcommands/subscribe.rs

These were causing issues when we rendered the helptext into markdown in https://github.com/clockworklabs/spacetime-docs/pull/168:
They also looked a bit weird when doing `spacetime help`:
```
Usage:
spacetimedb-cli [OPTIONS] <COMMAND>
Options:
--root-dir <root_dir>        The root directory to store all spacetime files in.
--config-path <config_path>  The path to the cli.toml config file
-h, --help                       Print help
-V, --version                    Print version
Commands:
publish    Create and update a SpacetimeDB database
delete     Deletes a SpacetimeDB database
logs       Prints logs from a SpacetimeDB database
call       Invokes a reducer function in a database.
WARNING: This command is UNSTABLE and subject to breaking changes.
describe   Describe the structure of a …
```

CLI - Remove newlines from command helptext

---

Cargo.lock
crates/core/src/estimation.rs
crates/core/src/sql/execute.rs
crates/execution/Cargo.toml
crates/execution/src/iter.rs
crates/execution/src/pipelined.rs
crates/expr/src/check.rs
crates/expr/src/expr.rs
crates/expr/src/lib.rs
crates/expr/src/statement.rs
crates/physical-plan/src/compile.rs
crates/physical-plan/src/plan.rs
crates/physical-plan/src/rules.rs
crates/query/src/lib.rs
crates/sql-parser/src/ast/sql.rs
crates/sql-parser/src/parser/sql.rs
crates/subscription/src/lib.rs

Adds LIMIT to the sql api.
None
2
Changes include:
1. A simple addition to the parser
2. A rewrite rule for merging with a table scan (needed for non-tuple-at-a-time iterators)
3. A new execution stage
Additional tests for both typing and executing a `LIMIT` clause

Add support for LIMIT

---

crates/core/src/estimation.rs
crates/core/src/sql/execute.rs
crates/execution/src/iter.rs
crates/execution/src/pipelined.rs
crates/expr/src/check.rs
crates/expr/src/expr.rs
crates/expr/src/lib.rs
crates/expr/src/statement.rs
crates/physical-plan/src/compile.rs
crates/physical-plan/src/plan.rs
crates/physical-plan/src/rules.rs
crates/query/src/lib.rs
crates/sql-parser/src/ast/mod.rs
crates/sql-parser/src/parser/errors.rs
crates/sql-parser/src/parser/mod.rs
crates/sql-parser/src/parser/sql.rs

Support count queries such as `SELECT COUNT(*) AS n FROM t`
None
1
Note, there is a better way of supporting agg, but that required a larger diff, so I left a descriptive TODO in the code instead.
Parsing, optimization, and execution tests added

Add support for COUNT

---

.github/workflows/package.yml
Cargo.lock
crates/paths/src/lib.rs
crates/update/Cargo.toml
crates/update/spacetime-install.ps1
crates/update/spacetime-install.sh
crates/update/src/cli.rs
crates/update/src/cli/install.rs
crates/update/src/cli/self_install.rs
crates/update/src/cli/upgrade.rs
crates/update/src/main.rs

Based on #2263, might make more sense to combine them as one PR.
This has a couple changes beyond just updating for the new spacetimedb-update functionality, mostly taken from looking at how `rustup-init.sh` does things:
- Uses the `get_architecture` function from `rustup-init.sh`, since it's existing well-tested code that gives us the rust/llvm target tuple, and platform detection code is horrible to write.
- checks for flags passed to the installer:
- if `-h` or `--help` is passed, prints the help text of the installer without having to download and execute it.
- If the download fails, check whether it was because of a 404 and give a good error message ("It seems like we may not have prebuilt binaries for your platform.")
- check for the case `chmod +x` doesn't actually set the …

Update install script

---

crates/core/src/subscription/query.rs
crates/physical-plan/src/plan.rs
crates/physical-plan/src/rules.rs

After swapping the left and right hand sides of a delta join, we were not updating the left and right hand side join fields.
This resulted in a stack overflow when applying a different rewrite rule for translating named arguments into positional ones.
As part of this patch I also modified the rewrite that stack overflowed to error if an invariant is not met.
None
1
Added basic regression test that stack overflowed before this change.
Added an incremental evaluation test similar to the ones we currently have. The current tests we have did not exercise this particular rewrite (left vs right join), and so did not catch this bug.

fix: join order rewrite rule

---

docker-compose.yml

See code comment.
None
1
This patch does not include any actual code changes. Just a comment and one line of commented out code. The commented out code line was tested manually be spinning up the docker dev env.

Add comment on Time Stamp Counter (TSC) for profiling with tracy

---

crates/client-api/src/lib.rs
crates/client-api/src/routes/database.rs
crates/core/src/json/client_api.rs

Now returning the execution duration of SQL queries. The changes include adding timing measurements and updating the API response structure to include the total duration of SQL execution.
Closes https://github.com/clockworklabs/spacetime-web/issues/478#issue-2645325773
AFAIK this should not require a change to the internal stuff.
This is an additive change to the SQL endpoint API.
1
I ran and tested this locally using a local build of SpacetimeDB and checked that it worked against my local build of the website.

Added in a SQL execution time calculation

---

crates/client-api/src/routes/subscribe.rs
crates/sdk/src/websocket.rs

Make the websocket loop send a `Ping` frame when the connection is idle for a while. "idle" includes missing server-side pings.
Writing to the socket will detect if the remote end went away, but FIN / RST went missing for some reason. This is not detected by only reading.
--- 
I haven't touched the scary server-side websocket loop, but we may consider to also make it send pings only if it doesn't have anything else to send.
2
The situation can be approximated by inducing a 100% packet loss scenario.
This can be done in various ways. A convenient one is `docker compose disconnect`, which disables the virtual interface of a container.
Without this patch, you'll see the server timing out the connection after a while (as it did not receive pong), while the client keeps thinking that something …

sdk: Client ping on idle connections

---

Cargo.lock
Cargo.toml
crates/paths/src/cli.rs
crates/update/Cargo.toml
crates/update/src/cli/upgrade.rs

Windows doesn't let you overwrite an exe file that's currently running. Thankfully, the [`self-update`](https://docs.rs/self-update) crate has an implementation for this.
1: can't get more broken that it already is! and we're just using someone else's code :)

Fix self-replace on windows

---

crates/update/src/cli/self_install.rs

As discussed internally, a EULA is not necessary given our existing BuSL and Apache 2.0 licenses.
None
1
I have not tested it, but it is absolutely trivial.

Removed the EULA check in the CLI

---

Dockerfile
crates/update/src/cli/install.rs

This just curls & runs the install script on a blank image. Technically won't work until the new script is up on the website.
1
I've tested a little bit and will test more once this is merged and I can download the artifacts built from CI (my system has too new a glibc version :cry: )

Add dockerfile for cli

---

Dockerfile

`spacetime init` generates a global.json with dotnet 8, so install 8 instead of 9 in the image. Also `rm /var/lib/apt/lists/*`, which is what `apt update` downloads, since that's unnecessary to package when the user can just run `apt update` themselves if they really need to.
1
The rust module generated by `spacetime init` works (including publish, call, logs, etc), since I was able to use a git dependency because rc4 isn't published to crates.io yet, but I couldn't figure out how to use a git dependency in dotnet. 
The invocations for using the image are:
```sh
docker run --init --name mydb -v $PWD:/app spacetime start
docker exec -ti mydb spacetime <init,publish,call,logs,etc>
```

Install dotnet-sdk-8 instead of 9 in Dockerfile

---

crates/bindings/src/table.rs

Also, remove a paragraph from `delete` docs that was intended to be internal, but got pasted here.
A response to an API break that we didn't realize happened, but no code changes in this PR.
1
None relevant.

Update `insert` docs to reflect actual behavior on set-semantic duplicates

---

crates/sdk/src/subscription.rs

Invoking `subscribe_to_all_tables` will no longer result in undefined behavior. Updated doc comment to reflect that.
None
0
No code changes.

Update comment to reflect the new internals of the subscription api

---

Cargo.lock
Cargo.toml
LICENSE.txt
crates/bindings-csharp/BSATN.Codegen/BSATN.Codegen.csproj
crates/bindings-csharp/BSATN.Runtime/BSATN.Runtime.csproj
crates/bindings-csharp/Codegen/Codegen.csproj
crates/bindings-csharp/Runtime/Runtime.csproj
crates/bindings/README.md
crates/cli/src/subcommands/project/csharp/StdbModule._csproj
crates/cli/src/subcommands/project/rust/Cargo._toml

I'm bumping these versions to 1.0.0 in preparation for the release.
**Note:** For some reason, `LICENSE.txt` hasn't been getting updated since `1.0.0-rc1`. I didn't investigate why.
None,
1
None. This just bumps package versions.

Bump Rust and C# package versions to 1.0.0

---

crates/update/src/cli/self_install.rs

Easier flow for macOS.
1
None, but it's just a println.

Print a message with a shell line to add bindir to PATH

---

crates/sdk/examples/quickstart-chat/main.rs

Revealed during John's review of https://github.com/clockworklabs/spacetime-docs/pull/162 . Apparently this code doesn't get linted in CI, or something?
1
so that you're confident that …

Minor updates to the Rust client quickstart

---

crates/update/src/cli/self_install.rs

Because it was a raw string, the `\` wasn't treated as an escape:
```
Downloading installer...
The SpacetimeDB command line tool will now be installed:
CLI configuration directory: /home/spacetime/.config/spacetime/
`spacetime` binary: /home/spacetime/.local/bin/spacetime
directory for installed SpacetimeDB versions: /home/spacetime/.local/share/spacetime/bin
database directory: /home/spacetime/.local/share/spacetime/data
Downloading latest version...
The `spacetime` command has been installed as /home/spacetime/.local/bin/spacetime
\
It seems like this directory is not in your `PATH` variable. Please add the
following line to your shell configuration and open a new shell session:
export PATH="/home/spacetime/.local/bin:$PATH"
The install process is complete; check out our quickstart …
```

Remove errant backslash that got into the 'please add to path' message

---

crates/commitlog/src/segment.rs

If offset index lookup return key as 0, that should be considered as empty index. Hence seek should be done.
This will also stop "Commitlog index offset not usable" warning in logs.
N/A
1
CI

handle offset index empty

---

.github/CODEOWNERS

We removed @jdetter from CLI codeowners because he was out. He's back now, so adding him back.
None
1
None

Add @jdetter back to CLI codeowners

---

crates/cli/src/subcommands/generate/mod.rs
crates/cli/src/subcommands/publish.rs

We (I) changed `--skip-println-checks` into `--lint-dir` in #1928 , but didn't update this helptext.
Fixes #2347 .
None
1

CLI - Fix helptext for `--build-options`

---

crates/core/src/subscription/module_subscription_actor.rs
crates/lib/src/metrics.rs

`bytes_sent_to_clients` was not being updated when merging with another set of metrics. Now it is.
None
1
A new unit test has been added

Update bytes_sent_to_clients when merging metrics

---

Cargo.lock
crates/bindings/tests/snapshots/deps__spacetimedb_bindings_dependencies.snap
crates/expr/src/check.rs
crates/expr/src/lib.rs
crates/lib/Cargo.toml
crates/sats/Cargo.toml
crates/sats/src/timestamp.rs

Adds RFC 3339 formatted timestamps to sql. This only required updates to the type system.
Note this does not introduce any new optimizations. Timestamp columns can be indexed and so all current optimizations related to indexed columns still apply.
None
1.5
Just added timestamp parsing and expanded a typing constraint to allow timestamp values in comparison expressions.
New typing tests

Support RFC 3339 timestamp values in sql

---

crates/cli/src/subcommands/sql.rs

See https://github.com/clockworklabs/SpacetimeDB/issues/2358 for more context on this issue and why this was needed.
I think we recently removed the functionality where we return row counts for `update` and `delete` statements. This means that the CLI can no longer say things like "N rows updated".
No.
1
```
$ "$WORK"/SpacetimeDBPrivate/public/target/debug/spacetimedb-cli sql -s local test-project --interactive
WARNING: This command is UNSTABLE and subject to breaking changes.
┌──────────────────────────────────────────────────────────┐
│ .exit: Exit the REPL                                     │
│ .clear: Clear the Screen                                 │
│                                                          │
│ Give us feedback in our Discord server:                  │
│ …
```

CLI - Fix `sql --interactive` case where returned rows are 0

---

.github/workflows/docker.yml
tools/merge-docker-images.sh

This is a **non-functional change** to make the `tools/merge-docker-images.sh` script more generic/flexible.
This PR is a series of small (stacking) changes:
- [add `sanitize_docker_ref`](https://github.com/clockworklabs/SpacetimeDB/commit/0c3e82dbb74d0e6d7beb2f2dfaeb3eabc907194d#diff-420ad3305b9234b763ba2d2a77c973be716716a4384fe4c1bc14977839855c8b)
- [add IMAGE_NAME param](https://github.com/clockworklabs/SpacetimeDB/commit/1a0ba34f4baa53eb09616f61c11a6ec3fca58166#diff-3f5366f6d6df3ec1179e5efadc6f350bfa88eebf4e2da589b4d94ccb85ae5e94)
- [make TAG and FULL_TAG into params](https://github.com/clockworklabs/SpacetimeDB/commit/f6bcb63a1d0bbe670631970a03015dc37f29da95#diff-3f5366f6d6df3ec1179e5efadc6f350bfa88eebf4e2da589b4d94ccb85ae5e94)
- [tweak output and …

Make the `tools/merge-docker-images.sh` script more generic

---

Cargo.lock
Cargo.toml
LICENSE.txt
crates/bindings-csharp/BSATN.Codegen/BSATN.Codegen.csproj
crates/bindings-csharp/BSATN.Runtime/BSATN.Runtime.csproj
crates/bindings-csharp/Codegen/Codegen.csproj
crates/bindings-csharp/Runtime/Runtime.csproj
crates/cli/src/subcommands/project/rust/Cargo._toml

Bumped Rust and C# versions to 1.0.1.
None. Just a version bump.
1
None

Bump versions to 1.0.1

---

README.md

Closes #2421.
Updates the install instructions in readme to match the website.
I've also removed the instructions for installing from source given #2420.
None
1
Just a readme update, but I did test the links in the readme and the install instructions for macos and docker.

update install instructions in readme

---

crates/cli/src/tasks/rust.rs

Title.
Missed when we changed our randomness API to be tied to the ctx.
[As reported in the public Discord](https://discord.com/channels/1037340874172014652/1348121042454839347/1348121042454839347).
N/a.
0.
None.

Fix outdated advice in `getrandom` warning

---

crates/cli/src/subcommands/generate/typescript.rs
crates/cli/tests/snapshots/codegen__codegen_typescript.snap

Currently if the primary key column is named in snake case, the typescript client won't be able to find it, because it converts the fields to camel case, but doesn't convert the primary key name.
1
I manually tested with the typescript quickstart.

When generating for typescript, convert the primary key to camel case.

---

crates/core/src/host/module_host.rs
crates/core/src/host/scheduler.rs
crates/core/src/host/wasm_common/module_host_actor.rs
crates/core/src/util/lending_pool.rs

Fixes clockworklabs/SpacetimeDBPrivate#1449. Turns out we weren't ever calling `Module::close()`, and thus were never calling `Scheduler::close()`. I'm still not able to actually repro the issue but if anything is the cause, this would be it. I also made it so `exit().await` won't return until the scheduler is fully closed, so that we won't run into race conditions.
1

Close scheduler on module exit

---

crates/commitlog/src/index/indexfile.rs

For some reason, we've been opening the read-only index file with
`.read(true).append(true)`.
This translates to `O_RDWR | O_APPEND` on *nix, but something weird on
Windows. A shared memory map requires `O_RDWR` (or equivalent) on either
platform, though, meaning that we'd always fail to `mmap` the index on
Windows.
Open with `.read(true).write(true)` instead to fix.
1
The impact of this bug is also small, because the offset index is not crucial
for standalone use. Who says, though, that Windows will never become a viable
server platform for SpacetimeDB?
Extends the tests to open an index using all three variants and perform lookups.

commitlog: Fix open flags for read-only offset index

---

crates/core/src/config.rs
crates/standalone/src/lib.rs

From the comment I put in the code:
> set the patch version of newly-created metadata files to 0 [which means that patch number of existing metadata files won't be updated past 0 either] -- v1.0.0 set `cmp.patch = Some(file_version.patch)` when checking version compatibility, meaning it won't be forwards-compatible with a database claiming to be created on v1.0.1, even though that should work. This can be changed once we release v1.1.0, since we don't care about its DBs being backwards-compatible with v1.0.0 anyway.
2 - it's slightly tricky to figure out the right thing to do to maintain compatibility while disallowing incompatibility, but I'm confident this is it :)

Allow databases from 1.0.1 to be run on 1.0.0

---

.github/workflows/ci.yml
smoketests/tests/clear_database.py
smoketests/tests/delete_database.py

Add tests checking that a module stops running when its database is deleted or re-published using the `--clear-database` flag.
Depends on private internals and time.

smoketests: Test database deletion

---

.github/workflows/package.yml

Build for musl

---

Cargo.lock
Cargo.toml
crates/bench/Cargo.toml
crates/bench/benches/generic.rs
crates/bench/benches/special.rs
crates/cli/Cargo.toml
crates/cli/src/main.rs
crates/core/Cargo.toml
crates/core/src/worker_metrics/mod.rs
crates/standalone/Cargo.toml
crates/standalone/src/main.rs
crates/standalone/src/subcommands/start.rs

This uses jemalloc in standalone instead of mimalloc, unless the target env is msvc. The main reason is that jemalloc exposes better stats, and has a way to do heap profiling. This PR doesn't set up profiling, but it does add stats on jemalloc's memory usage.
2. The risk here is that there could be an issue on some platforms. 
This works on mac and at least some linux platforms.

Use jemalloc in standalone and add stats.

---

Cargo.lock
crates/bench/benches/subscription.rs
crates/bindings/src/lib.rs
crates/core/src/estimation.rs
crates/core/src/host/module_host.rs
crates/core/src/sql/ast.rs
crates/core/src/sql/execute.rs
crates/core/src/sql/parser.rs
crates/core/src/subscription/execution_unit.rs
crates/core/src/subscription/module_subscription_actor.rs
crates/core/src/subscription/module_subscription_manager.rs
crates/core/src/subscription/query.rs
crates/core/src/subscription/subscription.rs
crates/expr/src/check.rs
crates/expr/src/lib.rs
crates/expr/src/statement.rs
crates/lib/src/identity.rs
crates/physical-plan/src/plan.rs
crates/query/src/lib.rs
crates/sdk/tests/test-client/src/main.rs
crates/sdk/tests/test.rs
crates/sql-parser/Cargo.toml
crates/sql-parser/src/ast/mod.rs
crates/sql-parser/src/ast/sql.rs
crates/sql-parser/src/ast/sub.rs
crates/sql-parser/src/parser/mod.rs
crates/sql-parser/src/parser/sql.rs
crates/sql-parser/src/parser/sub.rs
crates/subscription/src/lib.rs

Adds sql and subscriptions support for the `:sender` parameter which resolves to the caller identity.
Note that we resolve `:sender` before we type check. Hence right now it is purely a syntactic construct. Ultimately though we'll want to have parameters represented in the physical plan.
None
2
Mostly a straightforward change. The only change that might be unexpected is that now we must explicitly take the `:sender` identity into account when compiling a subscription. This was not automatically handled for us because we don't hash the AST directly.

Add sql support for `:sender` parameter 

---

Cargo.lock
Cargo.toml
crates/commitlog/Cargo.toml
crates/commitlog/src/commit.rs
crates/commitlog/src/commitlog.rs
crates/commitlog/src/error.rs
crates/commitlog/src/lib.rs
crates/commitlog/src/repo/mem.rs
crates/commitlog/src/repo/mod.rs
crates/commitlog/src/segment.rs
crates/commitlog/src/stream.rs
crates/commitlog/src/stream/common.rs
crates/commitlog/src/stream/reader.rs
crates/commitlog/src/stream/writer.rs
crates/commitlog/src/tests/bitflip.rs
crates/commitlog/src/tests/helpers.rs
crates/commitlog/tests/io.rs
crates/commitlog/tests/random_payload/mod.rs
crates/commitlog/tests/streaming/mod.rs

Moves support for streaming (network) transfer of raw commitlog data to the
`commitlog` crate proper, along with some improvements.
Also adds free-standing functions to determine the commitlog metadata and for
truncation. This allows to bypass `open`ing the commitlog in some cases, which
can be both convenient and avoids implicit creation of a segment when the
commitlog is empty.
None
2
Complexity is in diffing against the previous implementation, which lives in a
different repo. Risk is zero, as the code is not used in a released version.
Adds tests.

commitlog: Streaming

---

crates/core/src/auth/token_validation.rs

When looking up oidc configs, we weren't removing trailing slashes from the issuer url, which we are supposed to (according to [section 4.1 of the spec](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfigurationRequest)).
We have gotten some bug reports due to this.
1
I added `test_issuer_slash`, which would fail before this PR.

Remove trailing slashes from isser when looking up oidc configs.

---

Cargo.lock
Cargo.toml
LICENSE.txt
crates/bindings-csharp/BSATN.Codegen/BSATN.Codegen.csproj
crates/bindings-csharp/BSATN.Runtime/BSATN.Runtime.csproj
crates/bindings-csharp/Codegen/Codegen.csproj
crates/bindings-csharp/Runtime/Runtime.csproj
crates/cli/src/subcommands/project/rust/Cargo._toml
crates/core/src/config.rs

Bumped the Rust and C# versions to 1.1.0.
None
1
None. Existing CI only.

Bump versions to 1.1.0

---

.github/workflows/ci.yml
crates/sdk/tests/test-client/src/module_bindings/mod.rs

It is possible to have a diff after running `cargo test --all`, e.g. in `crates/sdk/tests/test-client/src/module_bindings/`. This PR adds a `git diff` check into the CI so that, if any PRs affect this output, they are required to regenerate the bindings.
No breaking changes.
1

CI - Make Test Suite check for dirty `git diff`

---

crates/commitlog/src/stream/writer.rs

Add a ctor for `StreamWriter` that returns the `segment::Metada` alongside the writer. The metadata is extracted anyway, returning it allows callers to avoid a second segment traversal if they want to inspect the it.
1
No functional changes.

commitlog: Open stream writer with metadata

---

crates/core/src/db/datastore/locking_tx_datastore/committed_state.rs
crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
crates/core/src/db/relational_db.rs
crates/core/src/host/host_controller.rs
crates/core/src/replica_context.rs

Instead of updating data-size-related gauges after each transaction, we report the metrics every 15 seconds. This should reduce overhead for databases with high traffic. 
1. The main risk here is extra overhead if there are a large number of idle databases. We could mitigate that in the future by returning the `next_tx_offset` and skipping reports if it hasn't changed.
I ran a standalone instance and checked that:
1. We report data size metrics right after a module is loaded.
2. The size metrics change if I add data.
I haven't really looking into writing unit tests for it, since this is tied in with the module lifecycle logic.

Update data size metrics periodically, not on every transaction.

---

Cargo.lock
Cargo.toml
crates/commitlog/Cargo.toml
crates/commitlog/src/commitlog.rs
crates/commitlog/src/lib.rs
crates/commitlog/src/repo/fs.rs
crates/commitlog/src/repo/mem.rs
crates/commitlog/src/repo/mod.rs
crates/commitlog/src/segment.rs
crates/commitlog/src/stream.rs
crates/commitlog/src/stream/common.rs
crates/commitlog/src/stream/reader.rs
crates/commitlog/src/stream/writer.rs
crates/commitlog/src/tests/bitflip.rs
crates/commitlog/src/tests/partial.rs
crates/commitlog/tests/streaming/mod.rs
crates/core/src/db/relational_db.rs
crates/core/src/host/host_controller.rs
crates/core/src/host/mod.rs
crates/durability/src/imp/local.rs
crates/fs-utils/Cargo.toml
crates/fs-utils/src/compression.rs
crates/fs-utils/src/lib.rs
crates/standalone/src/lib.rs

Resolves #1592. Takes `fs-utils/compression` from #2034.
Not sure which label applies, but this is a change that is not forwards-compatible once you upgrade.
3 - this is a bit tricky but I'm pretty confident in this implementation.

Commitlog compression

---

Cargo.lock
crates/core/src/sql/ast.rs
crates/expr/Cargo.toml
crates/expr/src/check.rs
crates/expr/src/expr.rs
crates/expr/src/lib.rs
crates/expr/src/rls.rs
crates/physical-plan/src/plan.rs

This is the first of several patches that will close/implement #2442. This one in particular adds a utility for expanding or resolving RLS rules in a logical query expression, but it does not integrate it into compiler. That will happen in a follow on patch along with integration tests.
None
2.5
The logic is straightforward. There are a few parts that may be non-obvious like tree rotations and alpha conversion. I've tried to add ample documentation around those parts.
Integration tests will be added with in the integration patch.

Add utility for rls resolution

---

crates/bindings/Cargo.toml
crates/bindings/src/lib.rs
modules/sdk-test/Cargo.toml
smoketests/__init__.py

Adds the `rls` cargo feature to the SpacetimeDB bindings crate and gates the `client_visibility_filter` proc macro with it.
None
0
I enabled the `rls` feature in the `sdk-test` module as well as the smoketests.
Both were already using `#[client_visibility_filter]` but it was, and still is, a noop.

Feature gate #[client_visibility_filter]

---

crates/core/src/db/relational_db.rs
crates/standalone/src/lib.rs

Moves the task from standalone to core and exports the function.
This allows to re-use the definition for non-replicated databases.
1
Only moves code.

core: Export the snapshot watcher / commitlog compressor

---

Cargo.lock
crates/core/src/sql/execute.rs
crates/execution/src/pipelined.rs
crates/expr/Cargo.toml
crates/expr/src/check.rs
crates/expr/src/expr.rs
crates/expr/src/lib.rs
crates/expr/src/rls.rs
crates/expr/src/statement.rs
crates/physical-plan/Cargo.toml
crates/physical-plan/src/compile.rs
crates/physical-plan/src/plan.rs
crates/physical-plan/src/rules.rs
crates/query/src/lib.rs
smoketests/tests/rls.py

Incorporates RLS resolution into the sql code path - but not the subscription code path. Subscriptions will come in a separate patch.
None
1.5
Mostly mechanical updates.

Add rls to the sql api

---

Cargo.lock
Cargo.toml
crates/client-api/src/routes/subscribe.rs
crates/core/src/client/client_connection.rs
crates/core/src/client/message_handlers.rs
crates/sdk/src/websocket.rs

Tungstenite `0.26` switches its `Message` to use `Bytes` instead of `Vec<u8>` for the payload, meaning we can now send messages without making a duplicate allocation for every client.
2: updating a dependency, but it's pretty low risk.
n/a - general optimization

Update tungstenite to 0.26

---

.github/workflows/ci.yml
crates/bindings/src/lib.rs
crates/sats/src/product_type.rs

Like the title says. I noticed we had some broken links in doc comments while working on #2547 , and thought it would be wise to detect them in CI.
N/a.
1.

Add CI job to run `cargo doc` on the bindings crate

---

crates/core/src/worker_metrics/mod.rs

I accidentally commited some debug logs I added for manually testing https://github.com/clockworklabs/SpacetimeDB/pull/2537. This is just going to add noise to the logs (2 meaningless lines every 10 seconds).
-1

Remove some testing logs statements.

---

crates/core/src/subscription/delta.rs
crates/core/src/subscription/module_subscription_actor.rs
crates/core/src/subscription/module_subscription_manager.rs

Previously we were not filtering out empty subscription updates. This would happen if we evaluated a subscription query over set of rows that a transaction updated, and that subscription query returned an empty result set.
None
0

Do not send empty subscription updates to clients

---

Cargo.lock
Cargo.toml
crates/core/src/db/relational_db.rs
crates/fs-utils/src/compression.rs
crates/fs-utils/src/dir_trie.rs
crates/snapshot/Cargo.toml
crates/snapshot/src/lib.rs
crates/snapshot/src/remote.rs
crates/snapshot/tests/remote.rs

This patch seeks to stabilize (for internal use) an API to synchronize a
remote snapshot repository with a local one.
The implementation ensures that:
1. Transferred objects are verified to match the snapshot file's hashes
before being made persistent in the snapshot's object repository.
2. The snapshot file itself is written only after all objects have been
stored successfully.
This makes it possible for the receiving end to infer from an uncorrupted
snapshot file being present that the snapshot as a whole is consistent
with reasonably high confidence. In a replicated setup this is a
valuable property.
2

snapshot: Remote synchronization

---

crates/commitlog/tests/random_payload/mod.rs

Followup to #2504. Not sure why I didn't have this as part of that, I think I thought it would take a while to write this.
n/a

Add integration test for commitlog compression

---

crates/bindings-csharp/Codegen.Tests/fixtures/diag/Lib.cs
crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/ExtraCompilationErrors.verified.txt
crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/Module#FFI.verified.cs
crates/bindings-csharp/Codegen.Tests/fixtures/diag/snapshots/Module.verified.txt
crates/bindings-csharp/Codegen/Module.cs
crates/bindings-csharp/Runtime/Attrs.cs
modules/sdk-test-cs/Lib.cs

Places the `[ClientVisibilityFilter]` behind the `STDB_UNSTABLE` experimental feature flag. Will emit a compiler warning unless the following is added to the module file
```csharp
#pragma warning disable STDB_UNSTABLE // Enable experimental SpacetimeDB features
```
None
0
The build failed until I enabled `STDB_UNSTABLE` in the `sdk-test-cs` module.

Feature gate [ClientVisibilityFilter] in C#

---

crates/expr/src/check.rs
crates/expr/src/statement.rs
crates/sql-parser/src/ast/sql.rs
crates/sql-parser/src/ast/sub.rs

Fixes an issue where we would panic on unqualified column names in join expressions. Now we return an error.
None
1
Added a test to the type checker that previously panicked

Return error for unqualified columns instead of panic

---

crates/core/src/subscription/module_subscription_actor.rs
crates/expr/src/lib.rs
crates/physical-plan/src/plan.rs
crates/sdk/tests/test-client/src/main.rs
crates/sdk/tests/test.rs

Was doing an investigation into subscription updates and discovered a bug that reordered `<` and `>` comparison expressions incorrectly.
I added subscription update tests for exercising the fix.
None
1

fix expression canonicalization

---

crates/core/src/host/instance_env.rs

Heap profiling performed by @jsdt revealed that we had a memory leak in `InstanceEnv::datastore_index_scan_range_bsatn_chunks`. A bit of spelunking pointed to `ChunkPool`, a pool of buffers, which prior to this commit was allowed to grow without limit. `ChunkPool` is per-database, and so it is easy to imagine a scenario in which a large number of databases each occasionally allocate, use and never free very large chunks, resulting in the overall system's memory usage increasing over time.
This commit adds some very simple limits on the heap usage of a `ChunkPool`. Specifically, we introduce two constants,
`MAX_CHUNKS_IN_POOL` and `MAX_CHUNK_SIZE_IN_BYTES`, and when returning a chunk to the pool, we free it if it violates these limits. The values of these constants, 32 and …

Impose limits on the heap usage of `ChunkPool`

---

Dockerfile

Fixes #2509, #2511.
Motivation from the latter:
> Should probably just build from source. Otherwise you could get into a bad situation where a user has clockworklabs/spacetime:1.0.1 but has updated the cli inside to 1.2.0 and is confused why they're running into issues.
The dotnet install script is kinda flaky right now, see https://github.com/dotnet/install-scripts/issues/582. If it's not building correctly replace `https://dot.net/v1/dotnet-install.sh` with `https://builds.dotnet.microsoft.com/dotnet/scripts/v1/dotnet-install.sh` and it should be exactly equivalent.
1

Make clockworklabs/spacetime docker image build from source

---

crates/core/src/subscription/module_subscription_manager.rs

Instead of collecting to a single vec, we collect to a linked list of vecs, which is rayon's [recommended way](https://docs.rs/rayon/latest/rayon/iter/trait.ParallelIterator.html#method.collect_vec_list) of collecting a parallel iterator into a single data structure. This means there will be fewer allocations - for N worker threads and M query plans, it's now N vecs and N linked list nodes with standard amortizable growth, instead of M vecs that get concatenated together one at a time.
2 - I'm pretty confident this doesn't have a behavior change and that the changes are only optimizations, but it'd probably be worth running benchmarks to make sure

Allocate fewer vecs in `eval_updates`

---

.github/workflows/package.yml

This was broken in https://github.com/clockworklabs/SpacetimeDB/pull/2466. Apparently it was not tested after changing to use `debian:bookworm`, which needs to be wrapped in a string.
CI-only change.
1

CI - Fix job that packages the CLI for release

---

crates/auth/Cargo.toml

This PR fixes publishing the `auth` crate by:
- Adding a `LICENSE`
- Adding a `description`
- Adding the `serde` feature to `spacetimedb-lib`, so that the crate builds successfully in isolation
No
1

Fix building and publishing the auth crate

---

crates/core/src/db/relational_db.rs
crates/core/src/host/instance_env.rs

Previously we weren't counting bytes_written inside of `update` (only `insert`). This updates the appropriate execution metrics inside of `InstanceEnv::update`.
1.
I added one unit basic test.

Count bytes_written for updates

---

crates/core/src/host/instance_env.rs
crates/core/src/host/scheduler.rs
crates/core/src/host/wasmtime/wasm_instance_env.rs
crates/core/src/host/wasmtime/wasmtime_module.rs
crates/lib/src/scheduler.rs
crates/sats/src/time_duration.rs

Fixes for timestamps, so that a reducer that happens after another is observed to have a later timestamp. Specifically:
- when running a scheduled reducer, clamp it so that `ctx.timestamp` will be at *least* the timestamp the reducer was scheduled for.
- when scheduling a reducer for `now + delay`, clamp `now` so it is at least the timestamp of the start of the current reducer run.
The first commit is pulled out from the second, to make it clearer what the actual logic change is.
2 - timing stuff is intricate and this could mess with assumptions people have made about the way it works, but I'm pretty confident this is strictly a strong guarantee.
- Triggered the assertion prior to this PR.
- Did not trigger the assertion with this PR.

Monotonic timestamps

---

crates/cli/src/subcommands/generate/typescript.rs
crates/cli/tests/snapshots/codegen__codegen_typescript.snap

Typescript field names use camel case, but indexes were using snake case, which meant they could never find anything if the field has multiple words in it.
For tables in the generated typescript code, this will change the name of the property that is generated for unique indexes. This could be considered a breaking change, but any code using those properties is already broken.
1
I tested by adding a table to the quickstart app with a primary key of `entity_id`, and verifying the behavior of the generated code before and after this change.

Use camel case for typescript unique indexes

---

crates/update/src/cli/self_install.rs

Prior to this PR, when the call to `upgrade` (which installs the latest version) failed, `self-install` would print the error and then go on to print a success message.
This PR updates the logic so that we fail if the version installation fails.
Previous behavior:
```
The SpacetimeDB command line tool will now be installed into /var/folders/qn/7t0vq3ts721cmgt0tgrtgzl80000gn/T/tmp.OEcKoBCvjL
Downloading latest version...
Error: failed to download and install latest SpacetimeDB version: Could not fetch release info: HTTP status client error (403 Forbidden) for url (https://api.github.com/repos/clockworklabs/SpacetimeDB/releases/latest)
The `spacetime` command has been installed as /var/folders/qn/7t0vq3ts721cmgt0tgrtgzl80000gn/T/tmp.OEcKoBCvjL/spacetime
The install process is complete; …
```

`spacetimedb-update self-install` fails if the install fails.

---

crates/core/src/sql/parser.rs
smoketests/tests/auto_migration.py
smoketests/tests/fail_initial_publish.py
smoketests/tests/rls.py

This patch disallows RLS on private tables. Attempting to publish such a module will now fail.
None.
This was always just a no-op since RLS doesn't doesn't apply to module owners, and non-owners cannot query private tables.
1

Do not publish RLS rules on private tables

---

crates/core/src/sql/execute.rs
crates/physical-plan/src/rules.rs

After the introduction of RLS, the filter pushdown rule was no longer guaranteed to reach a fixed point due to the presence of nested filter operations. This patch updates the rule to check if a plan has already been optimized before applying the rule.
None
1

Fix filter pushdowns in the presence of rls

---

Cargo.lock
Cargo.toml
LICENSE.txt
crates/bindings-csharp/BSATN.Codegen/BSATN.Codegen.csproj
crates/bindings-csharp/BSATN.Runtime/BSATN.Runtime.csproj
crates/bindings-csharp/Codegen/Codegen.csproj
crates/bindings-csharp/Runtime/Runtime.csproj
crates/cli/src/subcommands/project/csharp/StdbModule._csproj
crates/cli/src/subcommands/project/rust/Cargo._toml

Bumping versions to 1.1.1.
I also relaxed the patch version constraint in our template `.csproj` file.
No.
1
None, just existing CI.

Bump versions to 1.1.1

---

crates/cli/src/subcommands/generate/typescript.rs

When generating typescript types, if we have an array of unions, we wrap the inner type in parens, to fix https://github.com/clockworklabs/SpacetimeDB/issues/2541.
This should only change the generated code in places that would have been a bug.
1.
I didn't see a good place to add full tests for the typescript generation. We will want to do that at some point.
For this change I created a module with some more complex array types and inspected the generated code.

Typescript Generation: Wrap union types in parens if for arrays

---

crates/core/src/subscription/module_subscription_actor.rs

There's no reason to compress the table updates within an initial subscription, because it is only being sent to a single client.  The outer message will always be compressed.
None
1

Do not double compress subscribe messages

---

crates/schema/Cargo.toml
tools/crate-publish-checks.py

https://github.com/clockworklabs/SpacetimeDB/pull/2593 merged without adding a LICENSE file, so I'm adding that to the CI check.
None. CI only.
2.

CI - Publishable crates check also checks for license file

---

crates/bindings-csharp/BSATN.Runtime/BSATN/Runtime.cs

Makes enum validation faster during deserialization in C# by removing reflection.
None
1

Avoid reflection when validating enums

---

crates/bench/benches/subscription.rs
crates/core/src/host/module_host.rs
crates/core/src/subscription/mod.rs
crates/core/src/subscription/module_subscription_actor.rs
crates/core/src/subscription/module_subscription_manager.rs

Takes compression off the hot path of subscription evaluation while we are holding the tx lock. This means the server may be doing extra work if many clients are subscribed to the same queries, but it also means that extra work will be happening on a separate thread and not blocking transactions. It also means that clients will only have to decompress messages once before deserializing them.
None
1

Do not double compress transaction update messages

---

crates/core/src/subscription/module_subscription_actor.rs
crates/core/src/subscription/module_subscription_manager.rs

Fixes a bug where the subscription manager would not update its metadata for tables that did not have a filter in a join query.
This resulted in row updates not being sent to clients for those tables.
None
1

Fix subscription manager metadata for joins

---

Cargo.lock
Cargo.toml
crates/bindings/tests/snapshots/deps__spacetimedb_bindings_dependencies.snap

Modules generally don't honor the workspace cargo lock file, so may upgrade `ahash` silently, which pulls in a `getrandom` version that is not the one pulled in via `binding`. Thus feature unification doesn't apply and modules fail to compile due to the wasm target not being supported by the transitive `getrandom`.
This also causes smoketests to fail.
1
Smoketests / module compilation fail before this change, and succeed after.

Prevent `ahash` from pulling in `getrandom 0.3`

---

Cargo.lock
crates/snapshot/Cargo.toml
crates/snapshot/src/lib.rs
crates/snapshot/src/remote.rs
crates/snapshot/tests/remote.rs

Repurposes the remote `SnapshotFetcher` for verification of the snapshot's objects. This can be useful when memory usage is of concern.

snapshot: Provide streaming snapshot verification.

---

crates/core/src/db/datastore/locking_tx_datastore/mut_tx.rs
crates/core/src/host/module_host.rs
crates/core/src/host/wasm_common/module_host_actor.rs

We've observed this panic multiple times, somehow. It doesn't have to be a hard error, it's just surprising and not something we thought was possible. This PR drops it down to be an error log instead of a panic, and also adds the database identity to the log.
My hope is that, the next time we see this happen, we can find the replica dir and commitlog for the database with the inconsistent `st_table`, and use that to debug how we reached the unexpected state.
N/a
1.
None. We totally don't know how to reproduce this (that's kind of the point).

Log instead of panicking when missing a row from st_client

---

tools/check-diff.sh

This just simplifies a script used by CI checks. Apparently this is built into `git diff`.
1.

Use the --ignore-matching-lines flag of git diff.

---

crates/core/src/sql/execute.rs
crates/physical-plan/src/plan.rs
crates/physical-plan/src/rules.rs

Fixes a bug introduced in https://github.com/clockworklabs/SpacetimeDB/pull/2208 that used the wrong value for multi-column index scans.
None
1
Updated query planner tests that incorrectly asserted on the wrong values and added a new functional test.

Fix index scan rewrite rule

---

crates/core/src/client/client_connection.rs
crates/core/src/client/message_handlers.rs
crates/core/src/subscription/mod.rs
crates/core/src/subscription/module_subscription_actor.rs

Do not evaluate subscriptions that are statically determined to return empty result sets.
None
1
Added a test that asserts on execution metrics.

Do not evaluate subscriptions that return empty result sets

---

crates/core/src/client/client_connection.rs
crates/core/src/database_logger.rs
crates/core/src/db/relational_db.rs
crates/core/src/host/host_controller.rs
crates/core/src/host/module_host.rs
crates/core/src/util/mod.rs

`with_auto_commit` takes a lock, which we shouldn't be doing in a tokio task. The second commit uses the utility wrapper in more places around `core`, which makes the callsites clearer.
1
Not sure exactly what a test for this would look like, but this is clearly more correct than before.

 Use spawn_blocking for the fallback commit in identity_dis/connected 

---

crates/core/src/client/messages.rs

This fixes our outgoing row count metrics for (un)subscribemulti calls.

Fix row count stats for multi subscription responses.

---

crates/commitlog/src/commitlog.rs
crates/commitlog/src/lib.rs
crates/core/src/db/relational_db.rs
crates/core/src/error.rs
crates/core/src/host/host_controller.rs
crates/durability/src/imp/local.rs
crates/durability/src/lib.rs
crates/snapshot/src/lib.rs

Snapshots may be corrupted on disk or incomplete where the lock file is gone,
but the snapshot file was not written (it is written last after all objects).
This patch handles both cases by ignoring snapshots without a snapshot file when
listing the available snapshots, and trying older snapshots if the latest one
cannot be restored from (for any reason).
It also takes into account that the prefix of the local commitlog could have
been archived.
No
2

Handle snapshot restore more robustly

---

crates/core/src/host/module_host.rs

This moves reducer calls to the blocking thread pool. This is important because they wait for a write lock (which we don't want to do in the main worker pool).
We used to do this, but it was accidentally changed in https://github.com/clockworklabs/SpacetimeDB/pull/2550, and when it was initially reverted (https://github.com/clockworklabs/SpacetimeDB/pull/2624), it was switched to use a normal task.
1. The only risk is a performance regression, which is unlikely.

Call reducers on the blocking pool.

---

crates/core/src/host/module_host.rs

Follow-up to #2737. I added this utility function in #2730, and it makes the logic of these kinds of `spawn_blocking` uses clearer.
1
n/a - the code is equivalent.

Follow-up: use asyncify in ModuleHost::call

---

.github/workflows/ci.yml

Make sure the `Cargo.lock` file of the `wasm_bindings` job reflects the
latest available versions. This is what users would end up with on a
fresh module, so we want to catch any compile errors arising from a
different transitive closure of dependencies than what is in the
workspace lock file.
Follup-up for: https://github.com/clockworklabs/SpacetimeDB/pull/2714
1

ci: Update dependencies for the `wasm_bindings` job

---

crates/core/src/db/datastore/locking_tx_datastore/committed_state.rs
crates/core/src/db/relational_db.rs

Fixes #2758 .
Prior to this commit, system sequences (as in, sequences for columns of system tables) were not being correctly re-initialized after replaying from a commitlog. The reproducer for this was to delete the zero snapshot and then replay, and then to advance the sequence  by publishing a new module version with a new table.
The difference which hid this bug was that, specifically when replaying from nothing, we begin by calling `Locking::bootstrap`, which will `build_sequence_state`, and then after replaying the commitlog,
we `rebuild_state_after_replay`, which will `build_sequence_state` again. When replaying from a snapshot, we bypass `bootstrap`, and so the only call to `build_sequence_state` is in `rebuild_state_after_replay` after replaying the suffix of the commitlog.
The …

`build_sequence_state`: clobber pre-existing in-memory `Sequence`s

---

crates/core/src/client/client_connection.rs
crates/core/src/client/message_handlers.rs
crates/core/src/worker_metrics/mod.rs

This commit changes two metrics, `spacetime_websocket_requests_total` and `spacetime_websocket_request_msg_size`, to be labeled by the database `Identity` of the connection, rather than the replica ID.
Changes metric labels, but we don't offer stability guarantees about our metrics.
1 - I'm reasonably sure we don't even use these metrics.
None - I am unsure how to test metrics.

Make connection metrics keyed on database identity, not replica ID

---

crates/bench/benches/generic.rs
crates/bench/benches/special.rs
crates/core/src/db/relational_db.rs
crates/core/src/worker_metrics/mod.rs
crates/paths/src/lib.rs
crates/update/src/proxy.rs

SpacetimeDB doesn't actually compile on Windows because of bit rot of our various `cfg` flags. This fixes that issue.
It further fixes warnings caused by unused variables that are `cfg`'d out.
None
1
No testing beyond automated testing. No functionality should be changed.

Fixed compile errors and warnings on Windows

---

crates/commitlog/Cargo.toml
crates/commitlog/src/index/indexfile.rs
crates/commitlog/src/segment.rs

fix: Offset index, key lookup returns `(0,0)` key and byte offset pair if it is empty.
fix:`seek_to_offset` was returning `Ok` for key 0. when asked to validate 0th commit at 0 byte offset.
Resulting `reset_to_internal` to miscalculate commit offset and truncating in middle of first commit. Its calculation was shorter by `segment::HEADER::len`

Commitlog: handle empty offset index lookup

---

crates/table/src/page_pool.rs

Re-enables page pool
None
0
Already tested

Re-enable page bool with default size of 128 pages

---

crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
crates/core/src/db/relational_db.rs
crates/core/src/sql/execute.rs
crates/core/src/subscription/module_subscription_actor.rs

Fixes a bug noticed by @joshua-spacetime where we didn't actually merge in the update stats.
None
1

`commit_and_broadcast_event`: `read_tx.merge(update_metrics)`

---

crates/bindings-csharp/BSATN.Codegen/BSATN.Codegen.csproj
crates/bindings-csharp/BSATN.Runtime/BSATN.Runtime.csproj
crates/bindings-csharp/Codegen/Codegen.csproj
crates/bindings-csharp/Runtime/Runtime.csproj

Bump C# versions to 1.1.2 because we need to release a new version of them.
No, just a version bump.
1
None, just CI

Bump C# versions

---

crates/core/src/subscription/module_subscription_actor.rs
crates/core/src/subscription/module_subscription_manager.rs

Removes rayon from subscription evaluation and replaces its parallel iterators with sequential ones, the purpose of which is to optimize the common case of small updates where multithreading just adds overhead.
None
1
Just removes rayon and replaces `into_par_iter()` with `into_iter()`.

Single-threaded subscription evaluation

---

crates/core/src/host/wasm_common/module_host_actor.rs

Instead of dispatching reducer calls to rayon, we run them on the current tokio blocking thread.
None
1
A one line change. But we'll have to run some performance tests to see if it reduces overhead.

Run reducers on tokio blocking thread instead of rayon

---

crates/core/src/db/datastore/locking_tx_datastore/datastore.rs
crates/core/src/db/relational_db.rs
crates/core/src/host/module_host.rs
crates/core/src/host/wasm_common/module_host_actor.rs
crates/core/src/sql/execute.rs
crates/core/src/subscription/mod.rs
crates/core/src/subscription/module_subscription_actor.rs

This removes the dependency of the `TxMetrics` struct on `ExecutionCounters` which is deeply tied to things in the `core` crate that should not be in a potential future `datastore` crate.
This is in the furtherance of making it easier to separate the `datastore` crate.
None
1
None beyond automated. This is a non-functional change.

Datastore Extraction: TxMetrics refactor, small non-functional change to make datastore extraction easier

---

crates/table/src/page.rs

Fixes https://github.com/clockworklabs/SpacetimeDB/issues/2803.
None
The main risk here is that if we continue doing this, we have to give up 
Any semantically meaningful logic should be covered by existing tests.

`Page::reset_for`: stop zeroing pages

---

crates/client-api-messages/src/websocket.rs
crates/core/src/host/host_controller.rs
crates/core/src/host/instance_env.rs
crates/core/src/host/wasm_common/module_host_actor.rs
crates/core/src/sql/execute.rs
crates/core/src/subscription/execution_unit.rs
crates/core/src/subscription/mod.rs
crates/core/src/subscription/module_subscription_actor.rs
crates/core/src/subscription/module_subscription_manager.rs
crates/core/src/subscription/query.rs
crates/core/src/worker_metrics/mod.rs
crates/schema/src/schema.rs
crates/sqltest/src/space.rs
crates/subscription/src/lib.rs

and after releasing the datastore lock.
This commit moves some amount of work off the main `eval_updates_sequential` task and into a new background worker, the `send_worker`. The actual work performed is unchanged, it's just that some of it is moved to a different function which runs asynchronously after releasing the datastore lock. We expect two benefits from this:
1. Most obviously, we're now doing less work while holding the lock, reducing the size of our critical section.
2. We suspect that we had a thundering herd problem where we wake each client's WebSocket worker just before waking the next reducer task, making it wait in the Tokio task queue until all the client messages have been sent. This change should cause the reducer task to wake first, improving transaction throughput. …

Aggregate and broadcast `DbUpdate`s off the main thread

---

crates/commitlog/src/commitlog.rs
crates/commitlog/src/error.rs
crates/commitlog/src/segment.rs
crates/commitlog/src/stream/reader.rs

Much noise is e.g. created when the index is empty. Also consolidate the logic a bit.
1.5

commitlog: Reduce log noise when offset index cannot be used

---

smoketests/tests/replication.py

Needed to ensure subsequent tests that don't inherit from `ReplicationTest` have a functioning cluster, and allows deletion of test database.
1

smoketests: Bring containers back up in tear down of replication tests

---

crates/client-api-messages/src/energy.rs
crates/core/src/host/wasmtime/mod.rs
crates/core/src/host/wasmtime/wasm_instance_env.rs
crates/core/src/host/wasmtime/wasmtime_module.rs

- Change `ReducerBudget::DEFAULT_BUDGET` to 1.3 trillion
- Log a warning for every minute a reducer runs
1

Log every second a reducer takes to run

---

crates/client-api-messages/src/websocket.rs
crates/core/src/client/client_connection.rs
crates/core/src/host/host_controller.rs
crates/core/src/subscription/module_subscription_actor.rs
crates/core/src/subscription/module_subscription_manager.rs

For context, there is a discussion of potential race conditions [here](https://github.com/clockworklabs/SpacetimeDB/pull/2821#discussion_r2124355477).
The short explanation is that to make sure clients see things in a consistent order, we need to add outgoing messages to the `broadcast_queue` while we are still holding the associated database transaction lock.
I still need to do this for one-off queries.
This still has an issue with one-off queries, since I haven't routed those messages through.
The change is mostly a matter of changing code like `sender.send_message(message)` to `broadcast_queue.send_client_message(sender, message)`.
3. I don't have a good idea for how to prevent people from accidentally calling `sender.send_message` when they should be using the broadcast queue, so some …

Send other client messages through the broadcast queue

---

crates/client-api/src/routes/mod.rs
crates/client-api/src/routes/unstable.rs
smoketests/__init__.py
smoketests/tests/timestamp_route.py

Under a new router, `/unstable`, as `/unstable/timestamp`.
Also add a smoketest that this route is reachable and returns a JSON-encoded `Timestamp`.
Introduces a new HTTP route, but marks it unstable.
1.

Add an HTTP route to get the current `Timestamp`

---

crates/core/src/startup.rs

This patch makes it so that we do not pin any threads to core IDs 0 and 1, and instead reserve them for the OS. See the comment for more explanation.
None
1
A very simple change, but because we are taking cores away from the database we _may_ need to change the distribution of the remaining cores.
Before this change we saw the OS preempting reducer threads to handle interrupt requests, after this change - along with mapping these interrupt handlers to the reserved cores - we did not.

Reserve cores 0 and 1 for the OS

---

crates/core/src/host/host_controller.rs

Comment pasted from within `watch_maybe_launch_module_host`:
> `try_init_host` is not cancel safe, as it will spawn other async tasks
> which hold a filesystem lock past when `try_init_host` returns or is cancelled.
> This means that, if `try_init_host` is cancelled, subsequent calls will fail.
>
> This is problematic because Axum will cancel its handler tasks if the client disconnects,
> and this method is called from Axum handlers, e.g. for the subscribe route.
> `tokio::spawn` a task to build the `Host` and install it in the `guard`,
> so that it will run to completion even if the caller goes away.
>
> Note that `tokio::spawn` only cancels its tasks when the runtime shuts down,
> at which point we won't be calling `try_init_host` again anyways.
This fixes (hopefully) the dreaded …

Wrap `try_init_host` futures in `tokio::spawn` so they don't get cancelled

---

crates/core/src/db/db_metrics/mod.rs
crates/core/src/subscription/module_subscription_actor.rs

Adds new metrics for subscriptions such as compilation time and the number of tasks waiting to acquire the subscription lock.
None
1
Tested manually while running performance tests

Add more subscription metrics

---

crates/core/src/host/module_host.rs

If a client disconnected while waiting to send a message to the job queue, we would not decrement the queue counter. Adding a scope guard should handle all cases.
1

Use a scope guard for decrementing queue length.

---

crates/core/src/subscription/module_subscription_actor.rs
smoketests/tests/dml.py

Tests for subscription updates from DML
None
0
Just testing

Test subscription updates for dml

---

crates/core/src/subscription/mod.rs
crates/core/src/subscription/module_subscription_actor.rs
crates/core/src/subscription/module_subscription_manager.rs
crates/physical-plan/src/plan.rs
crates/subscription/src/lib.rs

If a table is subscribed to, and it joins with many different tables, this optimization will attempt to prune joins that it knows are empty.
None
3
A bug will most likely result in incorrect subscription results

Prune more queries when evaluating subscription updates

---

crates/sdk/src/db_context.rs

Since we changed from `with_credentials` to `with_token`, the Rust client SDK no longer knows its `Identity` prior to `on_connect`, even when the connection is not anonymous.
N/a
1
N/a

Fix an outdated docstring on `identity` and `try_identity` in the Rust SDK

---

crates/bindings-csharp/Runtime/bindings.c

`datastore_insert_bsatn` and `datastore_update_bsatn` will write back to the row buffer when passed a row with a 0 in an `auto_inc` column. The Rust imports correctly specify these row pointers as `*mut u8`, but the C# imports in `bindings.c` were declaring them as `const uint8_t*`. This commit removes the incorrect `const` qualifiers from the row pointer arguments in those declarations.
N/a
1
N/a

Remove incorrect `const` qualifiers on two imports in `bindings.c`

---

crates/core/src/subscription/module_subscription_actor.rs

Uses the database identity, not the owner identity, for subscription metrics. They are different. I incorrectly tagged these metrics with the owner identity in https://github.com/clockworklabs/SpacetimeDB/pull/2861.
None
0

Use database identity not owner identity for metrics

---

crates/core/src/subscription/module_subscription_actor.rs
crates/subscription/src/lib.rs

When pruning joins, both join columns do not have to be unique. If we have a set of row updates from a table, we only care that the join column from the opposing table is unique.
None
1

Relax conditions for query pruning

---

crates/client-api/src/routes/subscribe.rs
crates/core/src/client.rs
crates/core/src/client/client_connection.rs
crates/core/src/subscription/module_subscription_actor.rs

If a client's send queue reaches `CLIENT_CHANNEL_CAPACITY`, we drop the client connection by aborting the task that sends and receives messages from the client. If this abort happens before the task pulls the last messages off the queue, the outgoing queue length metric will never be decremented appropriately.
To fix this, we wrap the message receiver with the metric and decrement the metric when we drop the receiver. The receiver's `Drop` method will be called when the future is aborted which will now decrement the metric appropriately.
None
1
TBD

Record the size of a client's outgoing message queue on drop

---

crates/core/src/subscription/module_subscription_manager.rs

Performance tests showed a disproportionate amount of time being spent updating subscription metadata for unsubscribe vs subscribe. This was due to multiple scans of the search argument map in `remove_multi_subscription`. This patch replaces those scans, such as those performed by `retain`, with key lookups into the map.
None
1
This is a refactor and so previous test coverage still applies.

Speed up metadata update on unsubscribe

---

crates/bindings-csharp/BSATN.Codegen/BSATN.Codegen.csproj
crates/bindings-csharp/BSATN.Runtime/BSATN.Runtime.csproj
crates/bindings-csharp/Codegen/Codegen.csproj
crates/bindings-csharp/Runtime/Runtime.csproj

Bump C# versions to 1.2.1 in preparation for an upcoming release.
None
1
CI only

Bump C# versions to 1.2.1

---

crates/core/src/subscription/module_subscription_actor.rs
crates/core/src/subscription/module_subscription_manager.rs

Previously if two clients subscribed to semantically equivalent but syntactically different queries, we could potentially overwrite one resulting in one of the clients not receiving updates for that query.
The fix was to update a type signature from `HashMap<_, QueryHash>` to `HashMap<_, Vec<QueryHash>>`.
None
1

Fix query overwrites in the subscription manager

---

crates/core/src/startup.rs

Introduces a way to reserve another fixed amount from the available
cores, and allows to access the `CpuSet` used for tokio blocking
threads.
This is motivated by wanting to create a separate tokio runtime that can
share the blocking pool.
The patch also allows to adjust the fractional values for the various
pools, and exports methods for inspecting the actual assignments.
1
Used in private :speak_no_evil:

core: Allow adjusting CPU reservation pools

---

Cargo.lock
tools/upgrade-version/Cargo.toml
tools/upgrade-version/src/main.rs

We have sometimes missed this field when doing upgrades. This PR automates it as part of the rest of `tools/upgrade-version`.
Closes https://github.com/clockworklabs/SpacetimeDB/issues/2284.
No runtime changes
2
```
$ ( cd tools/upgrade-version && cargo run -- 1.2.3 ) 2>/dev/null && git diff LICENSE.txt
diff --git a/LICENSE.txt b/LICENSE.txt
index ca1f88fef..adca0d5e3 100644
--- a/LICENSE.txt
+++ b/LICENSE.txt
@@ -5,7 +5,7 @@ Business Source License 1.1
Parameters
Licensor:             Clockwork Laboratories, Inc.
-Licensed Work:        SpacetimeDB 1.2.0
+Licensed Work:        SpacetimeDB 1.2.3
The Licensed Work is
(c) 2023 Clockwork Laboratories, Inc.
@@ -21,7 +21,7 @@ Additional Use Grant: You may make use of the Licensed Work provided your
Licensed Work by creating tables whose schemas …
```

`tools/upgrade-version` updates the Change Date in `LICENSE.txt`

---

crates/core/src/db/mod.rs
crates/core/src/db/relational_db.rs
crates/core/src/host/host_controller.rs
crates/core/src/host/module_host.rs
crates/core/src/host/wasm_common/module_host_actor.rs
crates/core/src/sql/execute.rs
crates/core/src/subscription/module_subscription_actor.rs
crates/core/src/subscription/module_subscription_manager.rs
crates/snapshot/tests/remote.rs

Moves the recording of transaction metrics off the main reducer thread, unblocking the next reducer.
None
1
Just a refactor. Existing test coverage still applies.

Record transaction metrics off the main thread

---

crates/commitlog/src/lib.rs

As per convention, field names are in kebab-case.
We set up defaults for each field individually, such that the external
configuration does not have to enumerate all of them, but only the ones
to override.
None
1.5

commitlog: Set up options for toml configuration

---

.github/workflows/package.yml

Disable musl builds because our new v8 dependency (https://github.com/clockworklabs/SpacetimeDB/pull/2939) is not building successfully, and we currently don't want to investigate it.
None
1
None

Disable musl builds

---

smoketests/tests/replication.py

Forgot to do this for clockworklabs/SpacetimeDBPrivate#1881
1

smoketests: Adjust for node table rename

---

.github/workflows/ci.yml
docker-compose.yml
smoketests/docker.py

Smoketests that restart the server became flaky recently as the readiness
probing was broken. This patch fixes the issue and makes the process more
robust, namely:
- Label the compose services to check for readiness (i.e. spacetimedb
processes) as `app: spacetimedb`.
- When enumerating the containers, consider this label, as well as the
current compose file.
- For each spacetimedb container, try to "ping" all ports exposed on 
the host and succeed if one of them returns 200.
Previously, we would assume a specific container port to be "the"
spacetimedb port, which became false at some point.
Also re-enable `zz_docker` tests.

smoketests: Fix server restarts and make more robust

---

Cargo.lock
Cargo.toml
crates/core/src/db/relational_db.rs
crates/core/src/host/instance_env.rs
crates/testing/src/sdk.rs

We run `cargo update` in CI before testing the bindings, in order to
catch dependency issues for library users (which don't get dependency
pinning via our `Cargo.lock` file).
This turned up two issues, resolved here:
- `jemalloc_pprof` depends on `pprof_util` both directly and indirectly
via `mappings`. Using the `^0.7` version constraint causes conflicting
versions of `pprof_util` to be resolved.
Upgrade to `^0.8` to resolve the issue.
- `tempfile` started to mark `TempDir::into_path` as deprecated in favor
of the newly exported `TempDir::keep`, so bump to the latest version
(recall that `3.20` is semver-compatible with `3.8`).
1

Upgrade `jemalloc_pprof` and `tempfile` crates

---

smoketests/docker.py

Python has a funny way of dealing with absent values.
Fixes (again) restart tests to handle slowly restarting containers.
1
n/a

smoketests: Make gathering container ports None-safe

---

demo/Blackholio/client-unity/.gitattributes
demo/Blackholio/client-unity/Assets/Scripts/autogen/SpacetimeDBClient.g.cs

Just add a `.gitattributes` file that hide Blackholio autogenerated files from GitHub diffs
None
1

Blackholio - Hide generated files from diffs

---

docs/docs/sdks/typescript/index.md

Fixes https://github.com/clockworklabs/SpacetimeDB/issues/3073
None
1
None

Docs - Fix incorrect reference to Rust client SDK

---

sdks/typescript/packages/sdk/package.json

We want to release #2980 for the TS SDK, so I'm bumping our version number.
None
1
None, just a version bump.

TypeScript - Bump version to 1.3.1 for release

---

crates/snapshot/src/lib.rs

On databases with many already-compressed snapshots, this was leading to log spam without providing any useful information.
N/a
1
N/a

Drop log for already-compressed snapshot to debug

---

sdks/typescript/packages/sdk/src/websocket_decompress_adapter.ts

Fixes a Typescript SDK bug where onclose of WebsocketDecompressAdapter is never called
None
Potential risk as Typescript SDK consumers might be currently relying only on onConnectError to report disconnection. Users should instead use onDisconnect, or can simply subscribe to both callbacks with the same function again to get the same functionality. 
This is a trivial change, but could have minor repercussions on current code. I'd still say it's a level 1 change, with consumers able to easily change to the correct callback.

Typescript SDK: Fix to actually use the passed onclose function

---

crates/client-api/src/routes/subscribe.rs

Closes #3170 .
Commit messages:
2048 turned out to be too low a value for BitCraft, as their world upload process requests on the order of 6000 reducers very rapidly. We still feel that having a limit is valuable to prevent malicious or misguided clients from taking an arbitrarily large amount of host memory, so we bump the value to give us a wide safety error for BitCraft's needs but don't remove the limit entirely.
N/a
1

Increase default `incoming_queue_length` limit, log warning when a client violates it

---

tools/find-publish-list.py
tools/publish-crates.sh

I updated `tools/publish-crates.sh` and `tools/find-publish-list.py` to be more flexible to where our crates can be located (rather than hardcoding `crates/foo`). This is in preparation for https://github.com/clockworklabs/SpacetimeDB/pull/3181.
Now, `find-publish-list.py` loads the output of `cargo metadata` to dynamically find the path of the crate in question. This also allows us to "properly" determine which crates are ours, instead of the `spacetimedb-` string prefix check that we were doing before.
It also now supports `--directories` to output directory paths, rather than just crate names. `publish-crates.sh` now uses those output paths rather than assuming that it knows where to find crates.
As a bonus, this approach is also much faster (~0.3s to find the crate list, vs ~8 before …

`tools/publish-crates.sh` is more flexible for crate paths

---

crates/core/src/db/relational_db.rs
crates/standalone/src/lib.rs

In order to facilitate commitlog and snapshot archival, this patch adds channel params to `snapshot_watching_commitlog_compressor`
None
1

Add channel params to commitlog compressor

---

crates/bindings-typescript/package.json
crates/bindings-typescript/src/lib/identity.ts
crates/bindings-typescript/src/react/SpacetimeDBProvider.ts
crates/bindings-typescript/src/react/index.ts
crates/bindings-typescript/src/react/useSpacetimeDB.ts
crates/bindings-typescript/src/react/useTable.ts
crates/bindings-typescript/test-app/src/App.tsx
crates/bindings-typescript/test-app/src/main.tsx
crates/bindings-typescript/tsup.config.ts
docs/docs/sdks/typescript/quickstart.md
pnpm-lock.yaml
sdks/typescript/examples/quickstart-chat/src/App.css
sdks/typescript/examples/quickstart-chat/src/App.integration.test.tsx
sdks/typescript/examples/quickstart-chat/src/App.tsx
sdks/typescript/examples/quickstart-chat/src/main.tsx
sdks/typescript/package.json
sdks/typescript/src/react/index.ts
sdks/typescript/tsup.config.ts

This adds `react` as an optional peer dependency. If the TypeScript SDK is imported into a library that uses React (of the appropriate version) then they will have access to two new React hooks:
```ts
useSpacetimeDB<DbConnection>();
useTable<DbConnection, MyTable>('my_table');
```
This PR also updates the TypeScript `quickstart-chat` tutorial in the docs to use the new React hooks. I will split that tutorial into separate `React` and `TypeScript` tutorials in a future PR.
This is a purely additive change to the SDK
2 because it changes how the SDK is built a bit. Namely it makes the `spacetimedb` library an external dependency.

Implements React Hooks for the TypeScript SDK

---

crates/core/src/db/mod.rs
crates/core/src/db/persistence.rs
crates/core/src/db/relational_db.rs
crates/core/src/db/snapshot.rs
crates/core/src/host/host_controller.rs
crates/core/src/host/mod.rs
crates/core/src/subscription/module_subscription_actor.rs
crates/core/src/worker_metrics/mod.rs
crates/datastore/src/locking_tx_datastore/datastore.rs
crates/durability/Cargo.toml
crates/durability/src/imp/mod.rs
crates/durability/src/lib.rs
crates/fs-utils/src/compression.rs
crates/snapshot/Cargo.toml
crates/snapshot/src/lib.rs
crates/snapshot/tests/remote.rs
crates/standalone/src/lib.rs

The `DurabilityProvider` trait was introduced to enable the `HostController` to procure an alternative `Durability` impl from an external source.
It is also useful to be able to instantiate a `SnapshotWorker` externally, in order to subscribe to snapshot creation events without access to the `RelationalDB` instance it is operating on.
At a later stage, we may also use it to control the snapshot frequency externally.
This patch thus reframes the trait as `PersistenceProvider`, whose job is to provide persistence-related services.
Also separates snapshot creation and compression of older snapshots, and adds instrumentation to gather timing information for both.
1.5
Not a functional change, existing tests should cover that.

Expand scope of `DurabilityProvider` to include snapshotting

---

docs/docs/nav.js
docs/docs/sql/pg-wire.md
docs/nav.ts

Document PG wire format

---

docs/docs/sdks/typescript/quickstart.md

closing code section was missing (` ``` `) at the end of this quick start tutorial
https://spacetimedb.com/docs/sdks/typescript/quickstart

docs: fix closing code section and some grammar improvements

---

smoketests/tests/auto_migration.py

Updates smoketests to check for  following.
- Normal auto migration subscription should not disconnect subcriber.
- Add table columns migration should disconnect subscribers.
Solves #1957 .

Smoketest : Hotswap should not disconnect subscribers.

---

crates/core/src/db/persistence.rs
crates/core/src/db/relational_db.rs
crates/core/src/db/snapshot.rs
crates/snapshot/tests/remote.rs

Make it so the `SnapshotWorker` can be re-configured with a new
committed state. This allows event subscriptions to remain valid while a
replica transitions from leader to follower and vice versa.
This is considerably simpler than keeping the lifetimes of database and
persistence services strictly in-sync, at the expense of an idle task
per replica.
1.5

core: Allow snapshot worker to be reused

---

.github/workflows/ci.yml
.github/workflows/package.yml

It turns out that multi-line `run` statements don't fail properly on Windows. If one of the lines fails, the run won't exit early, and in fact the step will return successful.
CI-only changes.
1

CI - Multi-line runs fail properly on Windows

---

sdks/unreal/src/SpacetimeDbSdk/Source/SpacetimeDbSdk/Private/Connection/DbConnectionBuilder.cpp

Added support for wss:// protocol in Unreal SDK. The SDK previously forced all connections to use ws://, preventing connections to servers behind SSL/TLS proxies. The fix detects if the URI already includes a protocol (ws:// or wss://) and preserves it; otherwise defaults to ws:// for backward compatibility. This enables connections to SpacetimeDB servers hosted with Cloudflare Tunnels or other secure proxies.
This change is fully backwards compatible. URIs without a protocol prefix will continue to work as before, with ws:// being automatically prepended. No API signatures or existing behavior has changed.
Simple string prefix check before URL construction. The core WebSocket connection logic remains unchanged, and the default behavior is preserved when no protocol is specified. …

Adding wss:// support for the Unreal SDK

---

Cargo.toml
crates/cli/src/subcommands/project/rust/Cargo._toml
tools/upgrade-version/src/main.rs

It turns out that cargo automatically uses the latest semver-compatible versions of dependencies, which is not what we expected. tl;dr specifying `1.5.0` actually means `>=1.5.0 <2.0.0`, but we actually intend `1.5.*`.
This PR updates our `upgrade-version` tool, and re-runs it to fix the dep versions.
None.
1

Fix Rust dep versions

---

crates/bindings-macro/src/table.rs
crates/bindings/src/lib.rs
crates/bindings/src/table.rs
crates/bindings/tests/ui/views.rs
crates/bindings/tests/ui/views.stderr
smoketests/tests/filtering.py

The `#[table]` macro now generates read-only table and index handles.
None
1

Generate read-only table handles for `#[table]`
